### PR TITLE
client/assets: Add redeem confirms to utxo assets.

### LINKED ISSUE #1962: utxo assets need redeemed swaps monitored through confirmation too
Although less critical than ETH where txns get clobbered very easily by nonce replacement, Bitcoin's mempool can get so full that transactions are purged (and never mined).  In the last couple days, this threshold has been as high as 11 sat/vB.  With no redeem rebroadcasting for UTXO assets, that was nearly a problem with client configs with very high redeem confirmation targets, like 6.

In addition to txns being evicted from mempool prior to being mined, broadcasting can fail with errors like `error sending redeem transaction: rawrequest (sendtransaction) error: -26: mempool fee not met, 143 < 1924`.  While an error like that from a full-node wallet like bitcoind is good because it will keep trying to rebroadcast, the light clients more readily declare success if peers decide not to respond in error, or we simply move on assuming the publish succeeded.  In this light client case, the neutrino broadcaster should continually rebroadcast, eventually succeeding when network conditions permit, but this could be too late.  It would be best to have logic to change the fee and try a new redeem.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #1962

### CODE REVIEW

File: client/asset/btc/btc.go [hunk 1]
```diff
@@ -5089,3 +5091,71 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+	if err != nil {
+		return nil, err
+	}
+
+	utxo, _, err := btc.node.getTxOut(txHash, vout, pkScript, time.Now().Add(-ContractSearchLimit))
+	if err != nil {
+		return nil, fmt.Errorf("error finding unspent contract %s: %w", redemption.Spends.Coin.ID(), err)
+	}
+	if utxo == nil {
+		// TODO: Spent, but by who. Find the spending tx.
```
Comment (chappjc) [inline client/asset/btc/btc.go:5135]: I actually ran into a similar situation with someone in production where their client has actually redeemed, but because of a dcrd timeout with dcrwallet, Core's call to Redeem returned an error, and Core didn't record the redeem that really did broadcast.  As a result it retried a redeem repeatedly only to fail because the contract output was already spent.

However in the case I'm addressing we wouldn't be trying to confirm a known redemption yet, so it would have to be caught in one of the other ticking checks (isRedeemable).  I recently made a comment in the bonds pr diff where we'd do this:  https://github.com/decred/dcrdex/pull/2036/commits/8e0761761256a94ca17f2a1b59450bd05aab1086#diff-8962b4c526755f0f98ed9f46ae05827e8edbc43ed5671ea4a2624bdf1617496cR1565

Anyway, finding our own (forgotten) redeem would of course be similar to the recent refund search like in https://github.com/decred/dcrdex/pull/2011/files
I had tentatively planned to do similar to that if no one else go to that first.  I suppose the same code would be used for this TODO in `ConfirmRedemption`

File: client/asset/btc/btc.go [hunk 2]
```diff
@@ -5089,3 +5091,71 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+			Confs:  reqiredRedeemConfirms,
+			Req:    reqiredRedeemConfirms,
+			CoinID: coinID,
+		}, nil
+	}
+
+	// The contract has not yet been redeemed, but it seems the redeeming
+	// tx has disappeared. Assume the fee was too low at the time and it
+	// was eventually purged from the mempool. Attempt to redeem again with
+	// a currently reasonable fee.
```
Comment (chappjc) [inline client/asset/btc/btc.go:5149]: Nice.  This is the key thing solved in this PR.

File: client/asset/dcr/dcr.go [hunk 3]
```diff
@@ -4527,3 +4529,124 @@ func float64PtrStr(v *float64) string {
...
+
+	tx, err := dcr.wallet.GetTransaction(dcr.ctx, txHash)
+	if err == nil {
+		spew.Dump(tx)
+		return &asset.ConfirmRedemptionStatus{
+			Confs:  uint64(tx.Confirmations),
+			Req:    reqiredRedeemConfirms,
+			CoinID: coinID,
+		}, nil
+	}
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr.go:4547]: It does not seem like dcr spv will ever let go of a bad transaction. I have one in my testnet node that I planted, and now am stuck here as it will always find the fake transaction even though it is spending a spent contract.

So, for dcr, I'm not sure we can ever lose a transaction that is not mined. It seems as if there could be the opposite problem and we hang on to an impossible transaction forever.

We could check if the contract is spent yet first.

But I wonder if this should either check the redeem's fee vs the current fee and/or how long the transaction has been sitting and we `abandontransaction` if it looks like it is being ignored by miners and send a new one.

Comment (JoeGruffins) [reply client/asset/dcr/dcr.go]: Adding a map for dcr that will abandon transactions if they were first seen two hours ago and still have no confirmations.

File: client/asset/dcr/externaltx.go [hunk 4]
```diff
@@ -328,7 +328,7 @@ func (dcr *ExchangeWallet) isOutputSpent(ctx context.Context, output *outputSpen
 	nextScanHeight := lastScannedHeight + 1
 
 	bestBlock := dcr.cachedBestBlock()
-	if nextScanHeight >= bestBlock.height {
+	if nextScanHeight > bestBlock.height {
```
Comment (JoeGruffins) [inline client/asset/dcr/externaltx.go:331]: This was awkward during testing and I think it was incorrect. It skipped the best block, which has one confirm, so transactions were not searched there. I do not see an comments about a reason for this.

Comment (chappjc) [reply client/asset/dcr/externaltx.go:331]: @itswisdomagain See if this is correct please.

Comment (itswisdomagain) [reply client/asset/dcr/externaltx.go:331]: Yeah, looks correct per the comment below this if statement. I think that was supposed to be and I think it should be changed to `if lastScannedHeight >= bestBlock.height`.

The `nextScanHeight := lastScannedHeight + 1` should be moved to after this if statement.

The idea, per the comment inside the if statement, is ...
```
if lastScannedHeight == bestBlock.height {
	// this is fine, just return, no more blocks to scan
	return ...
}
if lastScannedHeight > bestBlock.height {
	// not fine, how did it scan a height above the best height?
	// log a warning, should never happen anyways
	// return too, since there're obviously no more blocks to scan
	return ...
}
```

Comment (JoeGruffins) [reply client/asset/dcr/externaltx.go]: This look right? https://github.com/decred/dcrdex/compare/db62034bae674721bf653a8b666faf8e1d4b5ad3..53bd2f1384b8ba7c09ac0ff40302d7c1085de111

File: client/asset/btc/btc.go [hunk 5]
```diff
@@ -5090,3 +5092,71 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+	}
+
+	txHash, vout, err := decodeCoinID(redemption.Spends.Coin.ID())
+	if err != nil {
+		return nil, err
+	}
+
+	utxo, _, err := btc.node.getTxOut(txHash, vout, pkScript, time.Now().Add(-ContractSearchLimit))
+	if err != nil {
+		return nil, fmt.Errorf("error finding unspent contract %s: %w", redemption.Spends.Coin.ID(), err)
```
Comment (norwnd) [inline client/asset/btc/btc.go:5133]: Just a nit: I noticed that here you are using `%w` to wrap this error while in other places you use `%v`, 

I'm curious whether you have some convention for this ? It seems both styles are used all across `client/asset/btc/btc.go` (I thought `%w` is usually preferred, unless you explicitly want to "disable" unwrapping for some reason)

Comment (JoeGruffins) [reply client/asset/btc/btc.go:5133]: Probably %w is always correct for errors. I am just in the habit of using %v. Will change the error %v's to %w's

Comment (chappjc) [reply client/asset/btc/btc.go:5133]: %w is almost always the "right thing to do" but we've had an annoying issue where we unwrap some errors recursively and only report the inner error ...  https://github.com/decred/dcrdex/issues/1488
One of the most annoying DEX (non)issues TBH.

Comment (JoeGruffins) [reply client/asset/btc/btc.go:5133]: v to w for errors https://github.com/decred/dcrdex/compare/53bd2f1384b8ba7c09ac0ff40302d7c1085de111..10f3413dbd2f2fdc612d6129e891a5792f2bb893

File: client/asset/dcr/dcr.go [hunk 6]
```diff
@@ -4527,3 +4546,178 @@ func float64PtrStr(v *float64) string {
...
+	if !abandonTx && !errors.Is(err, asset.CoinNotFoundError) {
+		return nil, fmt.Errorf("problem searching for redemption transaction %s: %w", txHash, err)
+	}
+
+	// Redemption transaction is missing from the point of view of our node!
+	// Unlikely, but possible it was redeemed by another transaction. We
+	// assume a contract past its locktime cannot make it here, so it must
+	// not be refunded. Check if the contract is still an unspent output.
+
+	txHash, vout, err := decodeCoinID(redemption.Spends.Coin.ID())
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:4614]: `txHash` is used above for the redemption tx. How about `swapHash` or something here to differentiate? Same in **btc**.

File: client/asset/dcr/dcr.go [hunk 7]
```diff
@@ -88,6 +88,8 @@ const (
 	// freshFeeAge is the expiry age for cached fee rates of external origin,
 	// past which fetchFeeFromOracle should be used to refresh the rate.
 	freshFeeAge = time.Minute
+
+	reqiredRedeemConfirms = 2
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:92]: Missing a `u`. req**u**iredRedeemConfirms

File: client/asset/dcr/dcr.go [hunk 8]
```diff
@@ -4527,3 +4546,178 @@ func float64PtrStr(v *float64) string {
...
+				_, height, err := dcr.wallet.GetBestBlock(dcr.ctx)
+				if err != nil {
+					return nil, err
+				}
+				hash := spendTx.TxHash()
+				return &asset.ConfirmRedemptionStatus{
+					Confs:  uint64(height - block.height),
+					Req:    reqiredRedeemConfirms,
+					CoinID: toCoinID(&hash, uint32(vin)),
+				}, nil
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:4679]: If `Confs` is `< reqiredRedeemConfirms` should we add this redemption to `mempoolRedeems` so we can avoid future calls to `externalTxOutput`?

File: client/asset/dcr/dcr.go [hunk 9]
```diff
@@ -4527,3 +4546,178 @@ func float64PtrStr(v *float64) string {
...
+			}
+		}
+		dcr.log.Warnf("Contract coin %v spent by someone but not sure who.", redemption.Spends.Coin.ID())
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:4682]: Any point in examining the output address(es) for the tx to see if it's us?

File: client/asset/dcr/dcr_test.go [hunk 10]
```diff
@@ -182,38 +182,39 @@ func signFunc(msgTx *wire.MsgTx, scriptSize int) (*wire.MsgTx, bool, error) {
...
+	passErr               error
+	disconnected          bool
+	rawRes                map[string]json.RawMessage
+	rawErr                map[string]error
+	blockchain            *tBlockchain
+	lluCoins              []walletjson.ListUnspentResult // Returned from ListLockUnspent
+	lockedCoins           []*wire.OutPoint               // Last submitted to LockUnspent
+	listLockedErr         error
+	estFeeErr             error
+	abandonTransactionErr error
```
Comment (buck54321) [inline client/asset/dcr/dcr_test.go:217]: How about `abandonTxErr` so we don't blow up the diff?

File: client/asset/dcr/dcr.go (hunk 9 above)
Comment (chappjc) [reply client/asset/dcr/dcr.go:4682]: I know you're asking @JoeGruffins, but I have this question some thought in context of the recently-added refund detection code (https://github.com/decred/dcrdex/pull/2011). Ultimately, I decided the client primarily needs a path forward instead of retrying and failing forever.  If we did detect it was paid to address X, we could log it, maybe even try to see if wallet owns the address, but aside from detecting if we were hacked, I didn't see it being helpful.  User can bring up the tx on an explorer, so maybe we log the located refund txid?

Comment (buck54321) [reply client/asset/dcr/dcr.go:4682]: Good points. A good log message is probably the best we can do. This will probably never happen anyway. No change needed.

**Comment by JoeGruffins** [comment]
Just rebased.

File: client/asset/btc/btc.go [hunk 11]
```diff
@@ -5090,3 +5092,71 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+			CoinID: coinID,
+		}, nil
+	}
+
+	// The contract has not yet been redeemed, but it seems the redeeming
+	// tx has disappeared. Assume the fee was too low at the time and it
+	// was eventually purged from the mempool. Attempt to redeem again with
+	// a currently reasonable fee.
+
+	form := &asset.RedeemForm{Redemptions: []*asset.Redemption{redemption}}
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5146]: Adding a fee rate argument.

File: client/asset/dcr/dcr.go (hunk 6 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4608]: Changed to `swapHash` in both places.

File: client/asset/dcr/dcr.go (hunk 7 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:92]: Corrected.

File: client/asset/dcr/dcr.go (hunk 8 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4673]: Good idea, done.

File: client/asset/dcr/dcr.go (hunk 9 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4676]: Leaving as is for now.

File: client/asset/dcr/dcr_test.go (hunk 10 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr_test.go:217]: shortened

**Comment by JoeGruffins** [comment]
buck's review changes https://github.com/decred/dcrdex/compare/570ea76accfebd5203d28b86a3b1242e473c7121..d9084f18b7795eddd92fa5afecd0c82b111d9d1a

File: client/asset/dcr/dcr.go [hunk 12]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
...
+	var abandonTx bool
+	tx, err := dcr.wallet.GetTransaction(dcr.ctx, txHash)
+	if err == nil {
+		if have && mRedeem.txHash == *txHash {
+			if tx.Confirmations == 0 && time.Now().After(mRedeem.firstSeen.Add(maxRedeemMempoolAge)) {
+				// Transaction has been sitting in the mempool
+				// for a long time now. Attempt to abandon.
+				abandonTx = true
+				if err := dcr.wallet.AbandonTransaction(dcr.ctx, txHash); err != nil {
+					dcr.log.Warnf("Unable to abandon redemption mempool transaction %v: %v.", txHash, err)
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr.go:4574]: %w was not correct for errors that are logged.

File: client/core/trade.go [hunk 13]
```diff
@@ -2854,8 +2854,14 @@ func (t *trackedTrade) confirmRedemption(match *matchTracker) {
...
-		return
+
+	// In some cases the wallet will need to send a new redeem transaction.
+	didUnlock, err := t.wallets.toWallet.refreshUnlock()
+	if err != nil { // Just log it and try anyway.
+		t.dc.log.Errorf("refreshUnlock error checking redeem %s: %v", t.wallets.toWallet.Symbol, err)
+	}
+	if didUnlock {
+		t.dc.log.Warnf("Unexpected unlock needed for the %s wallet to check a redemption", t.wallets.toWallet.Symbol)
 	}
```
Comment (JoeGruffins) [inline client/core/trade.go:2865]: Since this may need to create a new redemption, for eth too, I think we need this check.

File: client/core/trade.go [hunk 14]
```diff
@@ -2867,10 +2873,24 @@ func (t *trackedTrade) confirmRedemption(match *matchTracker) {
...
+	// one if we don't have one cached.
+	var feeSuggestion uint64
+	if _, is := t.accountRedeemer(); is {
+		feeSuggestion = t.metaData.RedeemMaxFeeRate
+	} else {
+		feeSuggestion = t.redeemFeeSuggestion.get()
+	}
+	if feeSuggestion == 0 {
+		feeSuggestion = t.dc.bestBookFeeSuggestion(t.wallets.toWallet.AssetID)
+	}
```
Comment (norwnd) [inline client/core/trade.go:2888]: seems like copy-paste ? maybe wrap it in helper **func** like `trackedTrade. redeemFeeSuggestion()` ?

Comment (JoeGruffins) [reply client/core/trade.go:2888]: I is. Sure. I think used in 3 places so good idea.

Comment (JoeGruffins) [reply client/core/trade.go]: or 2... added redemptionFee method https://github.com/decred/dcrdex/compare/d9084f18b7795eddd92fa5afecd0c82b111d9d1a..b946db78fa3409c28bd67c3b2df81498f5ed8e9e

File: client/asset/dcr/dcr.go [hunk 15]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
...
+	swapHash, vout, err := decodeCoinID(redemption.Spends.Coin.ID())
+	if err != nil {
+		return nil, err
+	}
+
+	var spent bool
+	_, err = dcr.wallet.UnspentOutput(dcr.ctx, swapHash, vout, 0)
+	if err != nil {
+		if errors.Is(err, asset.CoinNotFoundError) {
+			spent = true
```
Comment (chappjc) [inline client/asset/dcr/dcr.go:4617]: The naming of `spent` here is misleading here since in SPV mode we can't know it's spent based on `UnspentOutput`.  It's more like `maybeSpent`.  In SPV mode, it's _expected_ to not know if the contract is spent until you do a cfilters scan.  See the weak guarantees documented for `UnspentOutput` in the `asset.Wallet` interface docs.

Also, you do follow this with a block filters scan to determine, but why don't we use `lookupTxOutput` instead of using `UnspentOutput` directly before the scan like in the other places we do this check like in `refundTx`?  It's a bit smarter when not in spv mode.

File: client/asset/dcr/dcr.go [hunk 16]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
...
+			}
+			return &asset.ConfirmRedemptionStatus{
+				Confs:  uint64(tx.Confirmations),
+				Req:    requiredRedeemConfirms,
+				CoinID: coinID,
+			}, nil
+		}
+	}
+
+	if !abandonTx && !errors.Is(err, asset.CoinNotFoundError) {
```
Comment (chappjc) [inline client/asset/dcr/dcr.go:4599]: It's a bit challenging to reason out if it's possible to have a `nil` `err` and `abantonTx=false`.  Can that happen?
I keep thinking that before this it should do:

```go
if err == nil {
    if have && ...
    ...
} else if !errors.Is(err, asset.CoinNotFoundError) {
    return ...
}

// We are here if the tx not found, or found but abandoning...
````
?

File: client/asset/dcr/dcr.go [hunk 17]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
...
+					dcr.mempoolRedeemsMtx.Unlock()
+				}
+				return &asset.ConfirmRedemptionStatus{
+					Confs:  confs,
+					Req:    requiredRedeemConfirms,
+					CoinID: toCoinID(&hash, uint32(vin)),
+				}, nil
+			}
+		}
+		dcr.log.Warnf("Contract coin %v spent by someone but not sure who.", redemption.Spends.Coin.ID())
```
Comment (chappjc) [inline client/asset/dcr/dcr.go:4685]: You'd also be here if `isOutputSpent` returned `spent = false`... meaning the cfilters scan just failed to fine the spender (it's actually unspent).

**Review by chappjc — CHANGES_REQUESTED** [review]
We seem to be drawing incorrect conclusions about the returns from `UnspentOutput`.  If it finds an output it is definitely unspent; if it does not find it, it's spend status is *unknown* and we must scan to know spent or not.  If the filters scan then says **un**spent, that's not incorrect or contradicting `UnspentOutput`, it's the real result.

**Comment by JoeGruffins** [comment]
Just rebased.

File: client/asset/dcr/dcr.go [hunk 18]
```diff
@@ -102,6 +104,8 @@ var (
 	conventionalConversionFactor = float64(dexdcr.UnitInfo.Conventional.ConversionFactor)
 	walletBlockAllowance         = time.Second * 10
 
+	maxRedeemMempoolAge = time.Hour * 2
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:107]: Added a comment.

File: client/asset/dcr/dcr.go [hunk 19]
```diff
@@ -569,6 +578,10 @@ type ExchangeWallet struct {
 
 	externalTxMtx   sync.RWMutex
 	externalTxCache map[chainhash.Hash]*externalTx
+
+	// TODO: Consider persisting mempool redeems on file.
+	mempoolRedeemsMtx sync.RWMutex
+	mempoolRedeems    map[[32]byte]*mempoolRedeem
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:600]: Added the doc.

File: client/asset/dcr/dcr.go [hunk 20]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
 	}
 	return strconv.FormatFloat(*v, 'f', 8, 64)
 }
+
+func (dcr *ExchangeWallet) ConfirmRedemption(coinID dex.Bytes, redemption *asset.Redemption, feeSuggestion uint64) (*asset.ConfirmRedemptionStatus, error) {
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4933]: Added a doc.

File: client/asset/dcr/dcr.go [hunk 21]
```diff
@@ -4521,3 +4540,190 @@ func float64PtrStr(v *float64) string {
...
+				if err := dcr.wallet.AbandonTransaction(dcr.ctx, txHash); err != nil {
+					dcr.log.Warnf("Unable to abandon redemption mempool transaction %v: %v.", txHash, err)
+				} else {
+					dcr.log.Infof("Abandoned redemption mempool transaction: %v.", txHash)
+					deleteMempoolRedeem = true
+				}
+			}
+		} else {
+			// Will hit this if node was restarted with an actively
+			// redeeming swap.
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4971]: I mean dexc, yes. Correcting the doc.

The `mempoolRedeems` are not persisted and are added in `Redeem` so restarting after starting the redeem process would remove them.

File: client/asset/dcr/dcr.go (hunk 15 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:5006]: Using `lookupTxOutput` now.

File: client/asset/dcr/dcr.go (hunk 16 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4988]: I'm not sure what I was thinking here. I moved `!errors.Is(err, asset.CoinNotFoundError)` up because if it is not that error we should fail anyway.

File: client/asset/dcr/dcr.go (hunk 17 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:5074]: Now if `isOutputSpent` return false with no error, breaking to the bottom and sending a new tx

**Comment by JoeGruffins** [comment]
Now trusting the cfilters scan https://github.com/decred/dcrdex/compare/38be0018222f04592e9e964b27980deb94897f25..4160ae204bc60e9dceaf37dfb54aae553bf85861

File: client/asset/dcr/dcr.go [hunk 22]
```diff
@@ -4910,3 +4934,199 @@ func float64PtrStr(v *float64) string {
...
+			}
+		}
+		if vin >= 0 {
+			if spentStatus == -1 {
+				_, height, err := dcr.wallet.GetBestBlock(dcr.ctx)
+				if err != nil {
+					return nil, err
+				}
+				confs = uint64(height - block.height)
+			}
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr.go:5075]: Wait, that can't be right. These are the swap tx confirms.

**Comment by JoeGruffins** [comment]
Use correct confirms https://github.com/decred/dcrdex/compare/4160ae204bc60e9dceaf37dfb54aae553bf85861..a70b12c14044dfd1b46e04dd03484629e7c5096c

File: client/asset/dcr/dcr_test.go [hunk 23]
```diff
@@ -2779,3 +2790,214 @@ func TestEstimateSendTxFee(t *testing.T) {
...
+		txRes:          txFn([]bool{false}),
+		abandonTxErr:   errors.New(""),
+		mempoolRedeems: map[[32]byte]*mempoolRedeem{secretHash: {txHash: txHash, firstSeen: time.Now().Add(-maxRedeemMempoolAge - time.Second)}},
+		txOutRes:       map[outPoint]*chainjson.GetTxOutResult{newOutPoint(&txHash, 0): makeGetTxOutRes(0, 5, nil)},
+	}, {
+		name:       "ok and spent",
+		coinID:     coinID,
+		txRes:      txFn([]bool{true, false}),
+		redemption: redemption,
+		wantConfs:  1, // one confirm becasue this tx is in the best block
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr_test.go:2926]: because

**Comment by chappjc** [comment]
Priority feature for 1.0.

**Comment by JoeGruffins** [comment]
just rebased and fixed a typo

File: client/asset/dcr/dcr.go [hunk 24]
```diff
@@ -4908,3 +4932,196 @@ func float64PtrStr(v *float64) string {
...
+				// for a long time now. Attempt to abandon.
+				abandonTx = true
+				if err := dcr.wallet.AbandonTransaction(dcr.ctx, txHash); err != nil {
+					dcr.log.Warnf("Unable to abandon redemption mempool transaction %v: %v.", txHash, err)
+				} else {
+					dcr.log.Infof("Abandoned redemption mempool transaction: %v.", txHash)
+					deleteMempoolRedeem = true
+				}
+			}
+		} else {
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:4986]: `else if !have`?

File: client/asset/dcr/rpcwallet.go [hunk 25]
```diff
@@ -890,6 +891,16 @@ func (w *rpcWallet) rpcClientRawRequest(ctx context.Context, method string, args
 	return nil
 }
 
+// AbandonTransaction attempts to abandon a mempool transaction.
+// Part of the Wallet interface.
+func (w *rpcWallet) AbandonTransaction(ctx context.Context, hash *chainhash.Hash) error {
+	err := w.rpcClientRawRequest(ctx, methodAbandonTransaction, anylist{hash.String()}, nil)
```
Comment (chappjc) [inline client/asset/dcr/rpcwallet.go:897]: Hopefully this won't be a problem:

```
abandontransaction "hash"

Remove an unconfirmed transaction and all dependent transactions
```

Say the redeem created a UXTO that while unconfirmed was then selected to fund a new swap...
Detecting that might be a challenge though.

File: client/asset/dcr/dcr_test.go [hunk 26]
```diff
@@ -1766,6 +1770,10 @@ func TestFindRedemption(t *testing.T) {
 		},
 		Hex: txHex,
 	}
+	walletTxErr := new(error)
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr_test.go:1773]: So later we can set the value inside the function without rewriting the entire function.

But since it is confusing will set the entire function.

The reason for changing to a function is because the new method I added will need two or more walletTx there so this way tests can produce different txn based on some logic.

File: client/asset/dcr/dcr.go (hunk 24 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4986]: If `have` is true here, I think it is an error. Core has given this method a different redeem for this secret hash. It is this method's job to assign a new transaction so something is off. Perhaps the method was run concurrently for the same redeem and this is the result of a race if hit. Adding an error return here so we do not erase what the first call to this method must have done.

File: client/asset/dcr/rpcwallet.go (hunk 25 above)
Comment (JoeGruffins) [reply client/asset/dcr/rpcwallet.go:897]: I can remove this if you would like as it is not really part of the issue, I guess it's a separate issue but something I have hit by trying to redeem dust transactions with dcrwallet in spv mode. Then the wallet uses those same inputs for something else. But then it still keeps the bad transaction around in its db.

Or I could be misremembering.

Maybe this is a bug in dcrwallet that it keeps the tx around even after the inputs were spent by something else. I think I will just remove abandoning here, try to discern if it is a bug in dcrwallet, and try to get it fixed there if possible.

Incidentally, the vspd fee payment logic has AbandonTransaction as part of its wallet interface, so may have the same worry there.

**Comment by JoeGruffins** [comment]
https://github.com/decred/dcrdex/compare/7b4d93d04f02584c39ddae9ff7baad167ede33f5..dc96c6466c669306bd604983df7583217ea63326

buck fixes a couple more pushes though hold

**Comment by JoeGruffins** [comment]
just rebased

**Comment by JoeGruffins** [comment]
Removed abandon transaction for now, probably needs a separate issue and may be a dcrwallet bug that I was seeing. https://github.com/decred/dcrdex/compare/4059a0e1b331e280a0cdd55a48068ea2f00d1af6..78f763286de1192acf5fcc6bab092d618149716f

**Comment by JoeGruffins** [comment]
fixing doc https://github.com/decred/dcrdex/compare/78f763286de1192acf5fcc6bab092d618149716f..13c04a34166b9f4ba0217285af84d41e6ac61f5f

File: client/asset/dcr/dcr.go [hunk 27]
```diff
@@ -4909,3 +4933,200 @@ func float64PtrStr(v *float64) string {
 	}
 	return strconv.FormatFloat(*v, 'f', 8, 64)
 }
+
+// ConfirmRedemption returns how many confirmations a redemption has. Normally
+// this is very straitforward. However there are two situations that have come
+// up that this also handles. One is when the wallet can not find the redemption
+// transaction. This is most likely because the fee was set too low and the tx
+// was removed from the mempool. In the case where it is not found, this will
+// send a new fee tx using the provided fee suggestion. The second situation
```
Comment (martonp) [inline client/asset/dcr/dcr.go:4942]: "new fee tx" -> "new tx"

File: client/asset/dcr/dcr.go [hunk 28]
```diff
@@ -4909,3 +4933,200 @@ func float64PtrStr(v *float64) string {
...
+		}
+	}()
+
+	tx, err := dcr.wallet.GetTransaction(dcr.ctx, txHash)
+	if err != nil && !errors.Is(err, asset.CoinNotFoundError) {
+		return nil, fmt.Errorf("problem searching for redemption transaction %s: %w", txHash, err)
+	}
+	if err == nil {
+		if have && mRedeem.txHash == *txHash {
+			if tx.Confirmations == 0 && time.Now().After(mRedeem.firstSeen.Add(maxRedeemMempoolAge)) {
```
Comment (martonp) [inline client/asset/dcr/dcr.go:4977]: In this case, shouldn't we check to see if the contract output is still unspent, and resubmitting if it isn't, instead of just returning 0 confirmations?

File: client/asset/btc/btc.go [hunk 29]
```diff
@@ -5792,3 +5794,74 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
 	return deserializeMsgTx(bytes.NewReader(txB))
 }
+
+func (btc *baseWallet) ConfirmRedemption(coinID dex.Bytes, redemption *asset.Redemption, feeSuggestion uint64) (*asset.ConfirmRedemptionStatus, error) {
+	txHash, _, err := decodeCoinID(coinID)
+	if err != nil {
+		return nil, err
+	}
+
+	_, confs, err := btc.rawWalletTx(txHash)
```
[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/btc/btc.go:5804]: > to see if the fee needs to be bumped

Maybe could treat the redeem tx, which has a single output, as a transaction comprising a single change output.

I'm not excited about having Core start tracking a new set of "acceleration coins" for the redeem though.

We can make a TODO here unless it's simpler than I think.

However, if it doesn't get purged from mempool, I think it's alright.  The user just has to wait longer.  Still, there's a subtle possible vuln if you are the maker because your redeem really shouldn't hang around unmined after the taker's contract has expired.  But we've survived without this so far.

File: client/asset/btc/btc.go [hunk 30]
```diff
@@ -5792,3 +5794,74 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+		return nil, err
+	}
+
+	utxo, _, err := btc.node.getTxOut(swapHash, vout, pkScript, time.Now().Add(-ContractSearchLimit))
+	if err != nil {
+		return nil, fmt.Errorf("error finding unspent contract %s: %w", redemption.Spends.Coin.ID(), err)
+	}
+	if utxo == nil {
+		// TODO: Spent, but by who. Find the spending tx.
+		btc.log.Warnf("Contract coin %v spent by someone but not sure who.", redemption.Spends.Coin.ID())
```
Comment (chappjc) [inline client/asset/btc/btc.go:5839]: Let's use `swapHash, vout` in this log and the two `error`s that use it.

**Review by chappjc — CHANGES_REQUESTED** [review]

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (chappjc) [reply client/asset/dcr/dcr.go:4977]: We just found the spending transaction (the redeem) here.  Do you mean go look for a different mined spender of the contract output as we do in the flow later in this function in the case where `dcr.wallet.GetTransaction` could not find the redeem?

The wallet should periodically rebroadcast the unconfirmed redeem that it initially broadcasted.  Abandoning it and making an entirely new transaction is fairly perilous since the outputs from the initial redeem may be used already.

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5804]: I don't think neutrino has a purge transaction option like dcrwallet spv does either. So even if you thought a tx needed to go I don't think there's anything you can do about it?

File: client/asset/dcr/dcr.go [hunk 31]
```diff
@@ -4909,3 +4933,200 @@ func float64PtrStr(v *float64) string {
...
+
+// ConfirmRedemption returns how many confirmations a redemption has. Normally
+// this is very straitforward. However there are two situations that have come
+// up that this also handles. One is when the wallet can not find the redemption
+// transaction. This is most likely because the fee was set too low and the tx
+// was removed from the mempool. In the case where it is not found, this will
+// send a new fee tx using the provided fee suggestion. The second situation
+// this watches for is a transaction that we can find but has been sitting in
+// the mempool for a long time. This has been observed with the wallet in SPV
+// mode and the transaction inputs having been spent by another transaction. The
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4945]: I have not observed it so far, but I do test with dcr and other coins more than btc... because the testnet btc block times are longer.

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4977]: Resubmit the same transaction?

File: client/asset/btc/btc.go [hunk 32]
```diff
@@ -5792,3 +5794,74 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
 func msgTxFromBytes(txB []byte) (*wire.MsgTx, error) {
 	return deserializeMsgTx(bytes.NewReader(txB))
 }
+
+func (btc *baseWallet) ConfirmRedemption(coinID dex.Bytes, redemption *asset.Redemption, feeSuggestion uint64) (*asset.ConfirmRedemptionStatus, error) {
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5798]: Oh I forgot this in both assets, adding.

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (chappjc) [reply client/asset/dcr/dcr.go:4977]: > Resubmit the same transaction?

It would surely just say "already have transaction" or similar.  `GetTransaction` just reported it.

File: client/asset/dcr/dcr.go [hunk 33]
```diff
@@ -662,6 +680,7 @@ var _ asset.LiveReconfigurer = (*ExchangeWallet)(nil)
 var _ asset.TxFeeEstimator = (*ExchangeWallet)(nil)
 var _ asset.Bonder = (*ExchangeWallet)(nil)
 var _ asset.Authenticator = (*ExchangeWallet)(nil)
+var _ asset.RedemptionConfirmer = (*ExchangeWallet)(nil)
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:683]: Oh yeah! Great! Doing that. The wallet traits are just a runtime thing right? They don't need to keep order do they?

[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/dcr/dcr.go:683]: Just check the values on the frontend

File: client/asset/dcr/dcr.go (hunk 27 above)
Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4942]: Fixed.

File: client/asset/btc/btc.go [hunk 34]
```diff
@@ -82,6 +82,8 @@ const (
 	// testnetExternalApiUrl is the URL of the testnet external API in case of
 	// fallback.
 	testnetExternalApiUrl = "https://mempool.space/testnet/api/"
+
+	requiredRedeemConfirms = 2
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:86]: Setting to one for btc and adding docs.

File: client/core/trade.go (hunk 13 above)
Comment (JoeGruffins) [reply client/core/trade.go:2873]: Adding. For the peerCount, the xcWallet has this field but should it be checked live or good enough to use the field?

Comment (chappjc) [reply client/core/trade.go:2873]: Current field value is good.

File: client/asset/btc/btc.go [hunk 35]
```diff
@@ -5792,3 +5794,74 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+		}, nil
+	}
+
+	if !errors.Is(err, WalletTransactionNotFound) {
+		return nil, fmt.Errorf("problem searching for redemption transaction %s: %w", txHash, err)
+	}
+
+	// Redemption transaction is missing from the point of view of our node!
+	// Unlikely, but possible it was redeemed by another transaction. We
+	// assume a contract past its locktime cannot make it here, so it must
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5820]: Removing.

File: client/asset/btc/btc.go (hunk 30 above)
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5839]: Adding them to the log and two error returns following obtaining it.

**Comment by JoeGruffins** [comment]
I think covering all recent comments. Most notably removing the `RedemptionConfirmer` interface and adding that to the main interface. https://github.com/decred/dcrdex/compare/13c04a34166b9f4ba0217285af84d41e6ac61f5f..0819a9455112cde1c7f836c0a8d89d6117844334

File: client/asset/interface.go [hunk 36]
```diff
@@ -16,19 +16,18 @@ import (
...
-	WalletTraitRescanner           WalletTrait = 1 << iota // The Wallet is an asset.Rescanner.
-	WalletTraitNewAddresser                                // The Wallet can generate new addresses on demand with NewAddress.
-	WalletTraitLogFiler                                    // The Wallet allows for downloading of a log file.
-	WalletTraitFeeRater                                    // Wallet can provide a fee rate for non-critical transactions
-	WalletTraitAccelerator                                 // This wallet can accelerate transactions using the CPFP technique
-	WalletTraitRecoverer                                   // The wallet is an asset.Recoverer.
-	WalletTraitWithdrawer                                  // The Wallet can withdraw a specific amount from an exchange wallet.
-	WalletTraitSweeper                                     // The Wallet can sweep all the funds, leaving no change.
-	WalletTraitRestorer                                    // The wallet is an asset.WalletRestorer
-	WalletTraitRedemptionConfirmer                         // The wallet has a process to confirm a redemption.
```
Comment (JoeGruffins) [inline client/asset/interface.go:28]: These do not need to be kept in order, correct?

File: client/core/trade.go [hunk 37]
```diff
@@ -2844,24 +2830,50 @@ func (c *Core) sendRedeemAsync(t *trackedTrade, match *matchTracker, coinID, sec
...
+	if !toWallet.synchronized() {
+		t.dc.log.Errorf("Unable to confirm redemption. %s still syncing.", unbip(toWallet.AssetID))
 		return
 	}
-	if !t.wallets.toWallet.connected() {
+
+	didUnlock, err := toWallet.refreshUnlock()
+	if err != nil { // Just log it and try anyway.
+		t.dc.log.Errorf("refreshUnlock error checking redeem %s: %v", t.wallets.toWallet.Symbol, err)
 		return
```
Comment (JoeGruffins) [inline client/core/trade.go:2872]: This return is new. I think correct to return if unable to unlock? Maybe not necessary though if the redeem only needs to check confirms and not send a new transaction, which is most of the time. But I think wallet is expected to be unlocked with active trades anyhow.

File: client/asset/interface.go (hunk 36 above)
Comment (chappjc) [reply client/asset/interface.go:28]: They do not afaik, but I mean check and adjust the frontend where they are mirrored.

File: client/core/trade.go (hunk 37 above)
Comment (chappjc) [reply client/core/trade.go:2872]: Why not let the action requiring an unlocked wallet throw the error then?

File: client/asset/interface.go (hunk 36 above)
Comment (JoeGruffins) [reply client/asset/interface.go:28]: Ok sorry, missed that. Will do.

**Comment by JoeGruffins** [comment]
If the RedemptionConfirmer was 9 then the two after that need to come down two. Hopefully this is what was needed in the frontend https://github.com/decred/dcrdex/compare/0819a9455112cde1c7f836c0a8d89d6117844334..ec9b60f984a62538efe4b35bfb91d0539b35ffd8

File: client/core/trade.go (hunk 37 above)
Comment (JoeGruffins) [reply client/core/trade.go:2872]: Ok. Will remove the return then.

Comment (chappjc) [reply client/core/trade.go:2872]: Ok.  I mean you could still try to `refreshUnlock` here but if there's something downstream that really needed it to succeed, it can bomb.

**Comment by JoeGruffins** [comment]
Oh yeah it has the doc `// Just log it and try anyway.`

Not returning on unlock error. https://github.com/decred/dcrdex/compare/ec9b60f984a62538efe4b35bfb91d0539b35ffd8..f8022cad997135328e28e73cd0730c0045a87cb5

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (chappjc) [reply client/asset/dcr/dcr.go:4980]: > it says that if the transaction has been sitting in the mempool for a long time, it means that the inputs have been spent by another transaction

That has to be an insane wallet bug.  Sitting in mempool for a long time does not in general mean the inputs were double spent.

> Which basically means another transaction redeemed the swap somehow.  In this case shouldn't we check to see if the contract output is no longer unspent, and if so, return that the redemption is confirmed?

"no longer unspent" doesn't make sense to me.  It will definitely not be unspent the second the redeem tx enters mempool via the wallet.

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/btc/btc.go:5812]: So a kvdb for dcr to track a chain of accelerations of the redeem.  I guess so.  Feels messy and error prone.

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (martonp) [reply client/asset/dcr/dcr.go:4980]: This is what's in the comment:

```
The second situation
// this watches for is a transaction that we can find but has been sitting in
// the mempool for a long time. This has been observed with the wallet in SPV
// mode and the transaction inputs having been spent by another transaction. 
```

Comment (chappjc) [reply client/asset/dcr/dcr.go:4980]: I don't believe that comment is correct in general.  What I recall is that Joe hit a pathological case where the core startup match resolution actions fired of a refund or redeem before the wallet was synced, tricking wallet to double spend.  We've since resolved this with synchronized checks

Comment (chappjc) [reply client/asset/dcr/dcr.go:4980]: > If it's not this strange wallet issue, then the reason the tx has been sitting in the mempool for 2 hours must be that the fee is too low. In which case I think we should resubmit with a higher fee.

What do you mean be "resubmit with a higher fee"?  That sounds like RBF, but a Decred node will not relay a double spend, and the wallet will not publish the transaction either (it only got to that failure mode for the reason I described in my previous comment).

Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:4980]: Ok to punt on this for now? Maybe whatever I experienced is fixed. Maybe better to go further down this road if we can reliably reproduce something.

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5812]: Does the accelerator drop the old tx or does the wallet handle that? Need to look.

File: client/asset/interface.go [hunk 38]
```diff
@@ -593,11 +598,6 @@ type LogFiler interface {
 // Will also error if the secret in the contractData is not found in the
 // transaction secrets.
 type DynamicSwapOrRedemptionFeeChecker interface {
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/interface.go:600]: Will rename.

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/btc/btc.go:5812]: It's doesn't drop or replace.  It spends the change. CPFP.
This is what I was getting at a few comments above.

**Comment by JoeGruffins** [comment]
DynamicSwapOrRedemptionFeeChecker -> DynamicSwapper

https://github.com/decred/dcrdex/compare/f8022cad997135328e28e73cd0730c0045a87cb5..b3965a95e4e4e8b8e1d3b52a4de8232faa2e1954

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (martonp) [reply client/asset/btc/btc.go:5812]: I was proposing to do RBF. I think the server might have to be updated for this to start searching for the replacement tx instead of the original one though.

> So a kvdb for dcr to track a chain of accelerations of the redeem. I guess so. Feels messy and error prone.

I agree, it's kind of annoying in ETH, but probably worth it since BTC can have fee spikes. Since it also could require server changes I think it can be done later as a separate piece of work.

[the remark this answers is not in the document]
Comment (martonp) [reply client/asset/btc/btc.go:5812]: ETH is doing RBF/replace nonce, not CPFP. Couldn't we do the same thing here?

[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/btc/btc.go:5812]: RBF is not a thing in Decred.  And in BTC it's not trivial (need to fiddle with sequence values) or without consequences (new txid and any spenders of the replaced 0-conf UTXOs are hosed so we have to prevent that like our lives depend on it).

File: client/asset/dcr/dcr.go (hunk 28 above)
Comment (chappjc) [reply client/asset/dcr/dcr.go:4980]: > Ok to punt on this for now? Maybe whatever I experienced is fixed. Maybe better to go further down this road if we can reliably reproduce something.

Yes, I think so.  I think it was an edge case, but even if we want to consider abandoning, that's just a wallet concept and the rest of the network probably already has the initial tx (unless it was this wallet double spend bug) and a new one that tries to spend the already-spent contract output will be rejected by the network.

File: client/asset/btc/btc.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/btc/btc.go:5812]: `CPFP` oh yeah it ups the entire fee of the chain of txn. I remember now.

File: client/asset/btc/btc.go [hunk 39]
```diff
@@ -5792,3 +5797,82 @@ func deserializeMsgTx(r io.Reader) (*wire.MsgTx, error) {
...
+		}, nil
+	}
+
+	if !errors.Is(err, WalletTransactionNotFound) {
+		return nil, fmt.Errorf("problem searching for redemption transaction %s: %w", txHash, err)
+	}
+
+	// Redemption transaction is missing from the point of view of our node!
+	// Unlikely, but possible it was redeemed by another transaction. Check
+	// if the contract is still an unspent output.
```
Comment (chappjc) [inline client/asset/btc/btc.go:5832]: For both DCR and BTC, in the case where the wallet/node gives a result for the transaction, and we declare "mempool for a long amount of time" (the case from about 15 lines above), it could jump down here to attempt to locate a different spender.

If it found a different spender, that would really be indicative of a wallet bug because the wallet should automatically abandon/remove a transaction if its inputs are spent, but it's something we might want to try in the future, for robustness.

Regarding doing an explicit `AbandonTransaction` (with DCR) or otherwise attempting to replace the original, I still maintain that is dangerous because there is a chance that:

1. It is still on the network waiting to be mined, and any replacement may be rejected by the network on broadcast
2. The outputs of the original redeem may be spent, and abandoning/replacing the redeem will have adverse consequences for those 0-conf spenders
3. The redeem may **actually be mined** and our node/wallet could just have lost connection or gotten stuck or corrupted or whatever, and we're falsely concluding it's not mined.  We could be creating tons of unnecessary issues for ourselves if we start abanonding, replacing, trying to bump with cpfp, etc.  A restart or rescan of the wallet may very well be the best and only real resolution.

File: client/asset/dcr/externaltx.go [hunk 40]
```diff
@@ -328,13 +328,13 @@ func (dcr *ExchangeWallet) isOutputSpent(ctx context.Context, output *outputSpen
...
 		// When a transaction is initially found in a block, that block is also
 		// scanned for spending transactions (see findTxInBlock) as an
 		// optimization since the block was pulled. As such, it is normal for
 		// the lastScannedHeight for newly located transactions to be the best
 		// block, so there is no need to warn, only return.
-		if nextScanHeight > bestBlock.height+1 {
+		if lastScannedHeight > bestBlock.height {
 			dcr.log.Warnf("Attempted to look for output spender in block %d but current tip is %d!",
 				nextScanHeight, bestBlock.height)
 		}
```
Comment (chappjc) [inline client/asset/dcr/externaltx.go:340]: This new logic looks right, although the pseudocode from Wisdom still reads easier to me even though there are separate `return`s

```go
if lastScannedHeight == bestBlock.height {
	// this is fine, just return, no more blocks to scan
	return false, nil
}
if lastScannedHeight > bestBlock.height {
	// not fine, how did it scan a height above the best height?
	// log a warning, should never happen anyways
	dcr.log.Warn("shouldnt happen asdf")
	// return too, since there're obviously no more blocks to scan
	return false, nil
}
```

**Review by chappjc — APPROVED** [review]
All looks fine to me.  Just wanted to take the opportunity to comment one more time about the meaning of the "in mempool for hours" scenario, and what we could and shouldn't do in that case.

**Comment by chappjc** [comment]
Will merge as soon as the interface conflict is resolved.

File: client/asset/dcr/externaltx.go (hunk 40 above)
Comment (JoeGruffins) [reply client/asset/dcr/externaltx.go:340]: Will change to the more readable code here.

**Comment by JoeGruffins** [comment]
Make if more readable https://github.com/decred/dcrdex/compare/ad9d460f5e0865e33c88467660aa690aedc0dce7..52b2fff0fc3bd69f857dfb31c7f4a35e8a294201
