### PR TITLE
server/comms: fix synchronization issues and drop sleeps in tests

### LINKED ISSUE #394: eliminate time.Sleep from server/comms/comms_test.go
We should plan to refactor the `comms` tests to eliminate sleeps by making use of the `wsConnStub.recv chan` that was added in https://github.com/decred/dcrdex/pull/287/commits/30fec9c817f7f9c575261a443f84a72233f177e2 for interested tests in to know when `(*wsConnStub).WriteMessage` did it's thing.

`time.Sleep` is quick but dirty unfortunately and CI apparently loves to preempt the test thread's CPU, breaking our assumptions about goroutine execution timing.

e.g.
https://github.com/decred/dcrdex/runs/694068914#step:5:92
have also seen `comms_test.go:427: error decoding last message (): unexpected end of JSON input`

### PR DESCRIPTION
**Pull request by buck54321**
Resolves #394

Eliminate sloppy `time.Sleep` sync patterns in tests. Improves `WSLink.Send` synchronization so that a graceful shutdown will wait for messages to finish sending.

### CODE REVIEW

File: dex/ws/wslink.go [hunk 1]
```diff
@@ -100,15 +101,19 @@ func (c *WSLink) Send(msg *msgjson.Message) error {
...
+		c.writeMtx.Lock()
+		b := <-c.outChan
+		c.conn.SetWriteDeadline(time.Now().Add(writeWait))
+		err := c.conn.WriteMessage(websocket.TextMessage, b)
+		c.writeMtx.Unlock()
+		c.sendWG.Done()
+		if err != nil {
+			c.Disconnect()
+		}
+	}()
```
Comment (buck54321) [inline dex/ws/wslink.go:116]: This pattern is quite different than before, when there was a persistent goroutine to handle pings and outgoing messages. Doing it like this with the `sendWg sync.WaitGroup` allows us to have a "graceful" shutdown, and not be racy with any messages sent right before `Disconnect` is called. The `outChan` is still used to sequence the sends.

File: server/comms/comms_test.go [hunk 2]
```diff
@@ -34,14 +37,51 @@ func newServer() *Server {
 	}
 }
 
+func giveItASecond(f func() bool) bool {
```
Comment (buck54321) [inline server/comms/comms_test.go:40]: Even though we are eliminating `time.Sleep` for synchronization, there are still some times where a channel isn't convenient or would add significant complexity. `giveItASecond` can be used to sync to some arbitrary condition, e.g. the client's presence in the server's client map, with a 1 ms delay between checks.

File: server/comms/comms_test.go [hunk 3]
```diff
@@ -77,40 +114,31 @@ func (conn *wsConnStub) ReadMessage() (int, []byte, error) {
...
 		default:
 		}
 		return nil
 	}
-	conn.lastMsg = msg
 	// Send the message if their is a receiver for the current test.
 	if conn.recv != nil {
 		conn.recv <- msg
 	}
-	conn.write++
```
Comment (buck54321) [inline server/comms/comms_test.go:106]: `write` wasn't being used.

File: server/comms/comms_test.go [hunk 4]
```diff
@@ -633,22 +605,19 @@ func TestOnline(t *testing.T) {
...
 	server, err := NewServer(&RPCConfig{
-		ListenAddrs: []string{portAddr},
+		ListenAddrs: []string{":0"},
 		RPCKey:      keyPath,
 		RPCCert:     certPath,
 	})
 	if err != nil {
 		t.Fatalf("server constructor error: %v", err)
 	}
+	address := "wss://" + server.listeners[0].Addr().String() + "/ws"
```
Comment (buck54321) [inline server/comms/comms_test.go:618]: This allows testing in parallel.

File: client/rpcserver/rpcserver.go [hunk 5]
```diff
@@ -269,16 +269,15 @@ func New(cfg *Config) (*RPCServer, error) {
 	return s, nil
 }
 
-// Run starts the web server. Satisfies the dex.Runner interface.
-func (s *RPCServer) Run(ctx context.Context) {
+// Connect starts the RPC server. Satisfies the dex.Connector interface.
+func (s *RPCServer) Connect(ctx context.Context) (error, *sync.WaitGroup) {
```
[the remark this answers is not in the document]
Comment (chappjc) [reply client/rpcserver/rpcserver.go:273]: TBH, I'm thinking this PR goes in before #408, even though that creates some resolution work for @kevinstl .  I think having the canonical pattern laid out first is good.  How would you prefer to proceed, @buck54321 ?

File: dex/ws/wslink.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (chappjc) [reply dex/ws/wslink.go:116]: Although goroutines are not terribly heavy, we will be churning goroutines quite a bit this way.

To summarize what we're trying to accomplish here:  With a sending goroutine that receives on `outChan` as before we run the risk of filling that channel's buffer in `Send`.  Relying on a channel buffer was convenient, but Send might block if that buffer fills.  That maybe is not too bad because the `quit` change was the arbiter of connections status and messages were not dropped when the channel was full, just blocking.

We realized that a queue for the outgoing messages might needed.  The present solution solves the queuing issue via the Go scheduler, with a goroutine created for each message sent, at the cost of goroutine churn.  This may become a problem; I don't know.

Other solutions:
- A more complex implementation is to append under lock the messages to a slice of queued outgoing messages, while a `outHandler` goroutine pops entries off and sends them.  It's complex because a slice is not a synchronization mechanism.   The epochPump is an example, and that's pretty hairy.
- Have each `Send` block until it can actually `WriteMessage` itselft.  This would involve acquiring a semaphore (using a channel with buffer length 1, not a mutex, to select with quit in another case), and it would make `Send` blocking...

I actually think having `Send` block might be desirable so that the caller gets the error from `WriteMessage`, whereas now `nil` does not mean the send was successful.

File: dex/ws/wslink.go [hunk 6]
```diff
@@ -124,57 +129,54 @@ func (c *WSLink) SendError(id uint64, rpcErr *msgjson.Error) {
...
+func (c *WSLink) Connect(ctx context.Context) (error, *sync.WaitGroup) {
 	// Set the initial read deadline now that the ping ticker is about to be
 	// started. The pong handler will set subsequent read deadlines. 2x ping
 	// period is a very generous initial pong wait; the readWait provided to
 	// NewConnection could be stored and used here (once) instead.
+	if !atomic.CompareAndSwapUint32(&c.on, 0, 1) {
+		return fmt.Errorf("Attempted to Start a running WSLink"), nil
+	}
+	linkCtx, quit := context.WithCancel(ctx)
+	c.quit = quit
```
[the remark this answers is not in the document]
Comment (chappjc) [reply dex/ws/wslink.go:142]: Sort of, would need to declare linkCtx first and use `=` instead of `:=`.

File: dex/ws/wslink.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (chappjc) [reply dex/ws/wslink.go:116]: Anyway, we've chatted on matrix and I think we can run with this (a goroutine for each message sent) for now.  A requirement with `Send` is that a misbehaving client cannot gum up the works for up to `writeWait` (seconds).  Would we each connection to have a single goroutine for the life of the connection? Yes, but I think that using goroutines to handle this concurrency requirement is appropriate.

File: server/comms/server.go [hunk 7]
```diff
@@ -341,12 +349,14 @@ func (s *Server) disconnectClients() {
 }
 
 // addClient assigns the client an ID and adds it to the map.
```
Comment (chappjc) [inline server/comms/server.go:351]: Let's also add that it now attempts connection.

File: dex/ws/wslink.go [hunk 8]
```diff
@@ -124,57 +129,54 @@ func (c *WSLink) SendError(id uint64, rpcErr *msgjson.Error) {
...
-	c.wg.Wait()
 }
 
 // inHandler handles all incoming messages for the websocket connection. It must
 // be run as a goroutine.
-func (c *WSLink) inHandler() {
+func (c *WSLink) inHandler(ctx context.Context) {
+	// Ensure the connection is closed.
+	defer c.Disconnect()
+	defer c.wg.Done()
```
Comment (chappjc) [inline dex/ws/wslink.go:174]: last in first out, so `defer c.Disconnect` should be after `defer c.wg.Done()` to ensure Disconnect gets called.
