### PR TITLE
dex/testing/dcr: fix reorg script

### LINKED ISSUE #646: dex/testing/dcr: simnet harness: beta node hangs mining second block after disconnecting from alpha
This behavior breaks the reorg script.

To repro, you can just run the `./reorg` script in the simnet harness. It might be more informative to do it manually though. 
1. `./beta addnode 127.0.0.1:19571 remove`
2. `./mine-beta 1`
3. `./mine-beta 1`

I do see a debug-level message in the beta nodes logs that says `Too few voters found on any HEAD block, recycling a parent block to mine on`. I tried to set `ENABLE_TICKET_BUYER="1"` for the beta wallet, but to no avail.

### PR DESCRIPTION
**Pull request by itswisdomagain**
The dcr reorg script is modified to accept 2 optional arguments:
`./reorg (node depth), where
- `node` is the node that should undergo a reorg, either "alpha" or "beta" (default: alpha)
- `depth` is the number of blocks that should be purged from `node` (default: 2).
At the end of the reorg, both nodes will have `depth+1` new blocks.

During reorg, a clone of the alpha wallet is connected to the beta node after the beta node
is disconnected from the alpha node. This is done to enable mining multiple blocks on the
beta node.
The alpha wallet clone uses the same seed as the alpha wallet and is thus able to vote on
tickets purchased by the alpha wallet when the alpha node was connected to the beta node,
supplying enough votes to the beta node to validate previous blocks and allow the creation
of new blocks.

Resolves #646.

### CODE REVIEW

File: dex/testing/dcr/harness.sh [hunk 1]
```diff
@@ -89,19 +89,53 @@ chmod +x "${NODES_ROOT}/harness-ctl/mine-beta"
...
+  REORG_DEPTH=\$2
+fi
+
+# TODO: Cannot currently cause a 1+ block re-org on alpha because
+# beta cannot mine more than 1 main chain block while disconnected
+# from alpha.
+if [ "\${REORG_NODE}" = "alpha" ] && [ \${REORG_DEPTH} -gt 1 ]; then
+  echo "Cannot cause a re-org of more than 1 block on alpha."
+  exit 1
+fi
```
Comment (itswisdomagain) [inline dex/testing/dcr/harness.sh:112]: This can be fixed following @davecgh's recommendation [here](https://github.com/decred/dcrdex/issues/646#issuecomment-683225733) to use the same seed and enable voting on both alpha and beta wallets, to ensure beta wallet can vote on tickets purchased with the alpha wallet after the nodes are disconnected.

I'm hesitant to do that because it could cause issues for simnet tests relying on these wallets having different different utxo sets and balances.

File: dex/testing/dcr/harness.sh [hunk 2]
```diff
@@ -89,19 +89,53 @@ chmod +x "${NODES_ROOT}/harness-ctl/mine-beta"
...
 #!/bin/sh
+REORG_NODE="alpha"
+VALID_NODE="beta"
+REORG_DEPTH=1
+
+if [ "\$1" = "beta" ]; then
+  REORG_NODE="beta"
+  VALID_NODE="alpha"
+  REORG_DEPTH=3
+fi
```
Comment (itswisdomagain) [inline dex/testing/dcr/harness.sh:100]: I've had a need to cause reorg on either nodes while testing the FindRedemption feature on simnet, decided to add it here for convenience. I ultimately plan to use this feature in the simnet trading tests.

File: dex/testing/dcr/harness.sh (hunk 1 above)
Comment (chappjc) [reply dex/testing/dcr/harness.sh:112]: Would need to create a new wallet instead of replacing w-beta.

But I'm not sure that we're really creating a true reorg with the current change.  I think we have to hook up a voting wallet to the beta node. @davecgh is it not actually a reorg with only a single block on the beta node (where there's no voting wallet).  @itswisdomagain says he's creating a reorg by mining a single block on the beta node with the votes received prior to disconnecting alpha and beta, and then causing a reorg on reconnect by mining more blocks.

Comment (davecgh) [reply dex/testing/dcr/harness.sh:112]: You can create a single block reorg without hooking up a wallet to the second node if you mine one block on the second node, and two on the first, but it may or may not work for the desired goal.

e.g.

* Starting state:
α: tip A (height: 100), mempool has votes for A
β: tip A (height: 100), mempool has votes for A
* Disconnect them and mine a block on β using the votes it has in the mempool
* β state is now: A (100) -> B (101), mempool does NOT have votes for B
* Mine a block on α
* α state is now: A (100) -> B' (101), mempool has votes for B'
* Mine another block on α
* α state is now: A (100) -> B' (101) -> C (102), mempool has votes for C
* Reconnect the nodes
* β notices α has more work and reorgs to state: A (100) -> B' (101) -> C (102)
* β also now gets the votes for C from α's mempool

However, notice this means the reorg happen on β, not α, which may or may not be acceptable.  Typically, testing works from the viewpoint of α, because it has the wallet connected, and there is no way to force the reorg to happen on **α** without doing what I described where more blocks are mined on β than α via having a second wallet that can independently deliver the votes.

Comment (itswisdomagain) [reply dex/testing/dcr/harness.sh:112]: Here's how I've got reorg to happen on α:
Starting state:
- α: tip A (height: 100), mempool has votes for A
- β: tip A (height: 100), mempool has votes for A
- Disconnect them and mine a block on β using the votes it has in the mempool
- β state is now: A (100) -> B (101), mempool does NOT have votes for B
- Mine a block on α
- α state is now: A (100) -> B' (101), mempool has votes for B'
- Reconnect the nodes
- β now has votes for B
- Mine another block on β
- β state is now: A (100) -> B (101) -> C (102), mempool has votes for C
- α notices β has more work, purges B' (101) and reorgs to state: A (100) -> B (101) -> C (102)

Does that look correct? It works that way on testing though.

Comment (davecgh) [reply dex/testing/dcr/harness.sh:112]: That will work as long as both blocks have all 5 votes since it reverts to first-seen behavior in that case, however, it won't work in the general case when you start testing with less than 5 votes on some blocks.  As long as that is acceptable for this particular case of the DEX tests, then that should be fine.

Comment (itswisdomagain) [reply dex/testing/dcr/harness.sh:112]: Hmm, I see.
- Assuming B (101) on node β has 3 votes, and B' (101) on node α has 5 votes.
- β mines another block C (102), so β is now A (100) -> B (101) -> C (102)
- Could β end up purging B (101) because it has fewer votes and become A (100) -> B' (101) -> C (102)?

Comment (davecgh) [reply dex/testing/dcr/harness.sh:112]: Yep, that's what will happen.  When you connect the nodes back up, β will learn about B' from α and since B' has more votes, the miner on β will choose to mine on B' instead resulting in A (100) -> B' (101) -> C (102) which will force a reorg on β, but not α.

**Review by JoeGruffins — COMMENTED** [review]
Looks ok to me. But we want the three block reorg on alpha? Adding a new wallet?

**Comment by itswisdomagain** [comment]
Yeah... Add a second wallet to beta that can vote on tickets purchased by the alpha wallet i.e. shares the same seed with the alpha wallet. Gave that a rough trial but didn't work as expected. Will get back to it once I have some time.

**Comment by chappjc** [comment]
Convert to draft?

**Review by JoeGruffins — APPROVED** [review]
Really awesome. Working perfectly.

**Review by chappjc — APPROVED** [review]
Looks good. I also like the alpha/beta port changes to make them more orderly.
