### PR TITLE
dcr: Allow ticket purchasing for rpc spv wallets

### LINKED ISSUE #2611: dcr: Allow ticket purchasing for rpc spv wallets.
The biggest blocker for this is that currently the `GetTickets` rpc call will not work over rpc with an spv wallet. That will need to be "fixed" over in dcrwallet. The second problem is that, if a vsp is not set, purchasing will fail, and we currently have no way to know if an spv is set. If it's ok to just fail sometimes, maybe with a message asking the user to make sure a vsp is set, then maybe that's fine. Maybe we can also add some data to `GetTickets` or a new command to see if a vsp is currently set.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #2611 

Testers must update their system's `vspd` to latest or it will panic in the harness.

### CODE REVIEW

**Comment by JoeGruffins** [comment]
I guess the rpcwallet also needs to be a `ticketPager`

File: client/asset/dcr/rpcwallet.go [hunk 1]
```diff
@@ -1216,3 +1255,23 @@ func isAccountLockedErr(err error) bool {
...
+	var walletInfo newWalletInfo
+	err := w.rpcClientRawRequest(ctx, methodWalletInfo, nil, &walletInfo)
+	return &walletInfo, translateRPCCancelErr(err)
+}
+
+var _ ticketPager = (*rpcWallet)(nil)
+
+func (w *rpcWallet) TicketPage(ctx context.Context, scanStart int32, n, skipN int) ([]*asset.Ticket, error) {
+	return make([]*asset.Ticket, 0), nil
+}
```
Comment (JoeGruffins) [inline client/asset/dcr/rpcwallet.go:1277]: Without this there will be an error:
```
2024-05-07 08:50:36.970 [ERR] WEB: error retrieving ticket page for 42: ticket pagination not supported for this wallet
```

But it doesn't look like the pager is needed. Should this error be silence somewhere else?

Also the statuses are all unknown, which I think is a separate issue.

File: client/asset/dcr/rpcwallet.go [hunk 2]
```diff
@@ -1030,10 +1055,23 @@ func (w *rpcWallet) PurchaseTickets(ctx context.Context, n int, _, _ string) ([]
...
-	// GetTickets only works for clients with a dcrd backend.
+	return w.tickets(ctx, true)
+}
+
+func (w *rpcWallet) tickets(ctx context.Context, includeImmature bool) ([]*asset.Ticket, error) {
+	w.ticketCache.Lock()
+	defer w.ticketCache.Unlock()
+	if w.ticketCache.stamp.Add(ticketCacheExpiry).After(time.Now()) {
+		return w.ticketCache.tickets, nil
+	}
```
Comment (JoeGruffins) [inline client/asset/dcr/rpcwallet.go:1070]: Sometimes this was returning tickets then none if called close together. I guess a cache is alright to have?

**Comment by JoeGruffins** [comment]
This looks ok for purchasing tickets but viewing them afterwards seems to have a lot of problems still.

File: client/asset/dcr/rpcwallet.go [hunk 3]
```diff
@@ -1030,10 +1055,23 @@ func (w *rpcWallet) PurchaseTickets(ctx context.Context, n int, _, _ string) ([]
...
 func (w *rpcWallet) Tickets(ctx context.Context) ([]*asset.Ticket, error) {
-	const includeImmature = true
-	// GetTickets only works for clients with a dcrd backend.
+	return w.tickets(ctx, true)
+}
+
+func (w *rpcWallet) tickets(ctx context.Context, includeImmature bool) ([]*asset.Ticket, error) {
+	w.ticketCache.Lock()
+	defer w.ticketCache.Unlock()
+	if w.ticketCache.stamp.Add(ticketCacheExpiry).After(time.Now()) {
```
Comment (JoeGruffins) [inline client/asset/dcr/rpcwallet.go:1068]: Can use time.Since

File: client/asset/dcr/dcr.go [hunk 4]
```diff
@@ -5299,9 +5299,13 @@ func (dcr *ExchangeWallet) StakeStatus() (*asset.TicketStakingStatus, error) {
...
 		return nil, errors.New("not connected, login first")
 	}
-	// Try to get tickets first, because this will error for RPC + SPV wallets.
+	// Try to get tickets first, because this will error for older RPC + SPV
+	// wallets.
 	tickets, err := dcr.tickets(dcr.ctx)
 	if err != nil {
+		if errors.Is(err, oldSPVWalletErr) {
+			return nil, nil
+		}
```
Comment (martonp) [inline client/asset/dcr/dcr.go:5308]: In this case the UI doesn't show any information that the current version of dcrwallet is too low. Might be helpful to show that.

File: client/asset/dcr/rpcwallet.go (hunk 1 above)
Comment (martonp) [reply client/asset/dcr/rpcwallet.go:1277]: Without `TicketPage` will it show the tickets that have already voted?

> Also the statuses are all unknown, which I think is a separate issue.

The native wallet doesn't show undefined.

File: client/asset/dcr/dcr.go (hunk 4 above)
Comment (buck54321) [reply client/asset/dcr/dcr.go:5308]: Is there a reasonably easy way to do that? I don't expect the number of rpc+spv users will be high. If it's more that a few lines of work to properly communicate this message to the front end, I'm okay with how you have it, @JoeGruffins.

File: client/asset/dcr/rpcwallet.go [hunk 5]
```diff
@@ -72,6 +87,10 @@ type rpcWallet struct {
 	// or a stub for testing.
 	rpcClient rpcClient
 
+	// Calling w.rpcClient.GetTickets too close together will return no
+	// tickets for the second call. A ticket cache alleviates this.
```
Comment (buck54321) [inline client/asset/dcr/rpcwallet.go:91]: It's a dcrwallet bug?

File: client/asset/dcr/rpcwallet.go (hunk 1 above)
Comment (buck54321) [reply client/asset/dcr/rpcwallet.go:1277]: I guess we should consider using the tx history db for paginating ticket history. At least for spv wallet but maybe for all. No need to do it in this PR though. Sounds like a bit of work.

**Review by buck54321 — CHANGES_REQUESTED** [review]
Can you configure the vsp for our harness beta wallet?

**Comment by JoeGruffins** [comment]
Configuring beta wallet with the vsp https://github.com/decred/dcrdex/compare/b7484aa8719d11b1c97285d7410a58c035b7971a..ed4c676d50d7467941a233d26a7ba9664d3700f4

File: client/asset/dcr/rpcwallet.go (hunk 1 above)
Comment (JoeGruffins) [reply client/asset/dcr/rpcwallet.go:1277]: > Without TicketPage will it show the tickets that have already voted?

The already voted tickets always seem to go away. Without being a `TicketPage` you can't view any pages with under 10 tickets.

File: client/asset/dcr/rpcwallet.go (hunk 5 above)
Comment (JoeGruffins) [reply client/asset/dcr/rpcwallet.go:91]: Unsure...

Comment (JoeGruffins) [reply client/asset/dcr/rpcwallet.go:91]: I think I was wrong about this. Removing for now.

**Comment by JoeGruffins** [comment]
Looking again today I'm not seeing blank results. Removing the cache for now...

https://github.com/decred/dcrdex/compare/ed4c676d50d7467941a233d26a7ba9664d3700f4..916f2490e56b83ac40244c18957bf776fd88cf30

**Comment by JoeGruffins** [comment]
@buck54321 updated the dcrwallet version to latest

File: dex/testing/dcr/harness.sh [hunk 6]
```diff
@@ -302,50 +302,54 @@ ENABLE_VOTING="2" # 2 = enable voting and ticket buyer
...
+USE_SPV="0"
+ENABLE_VOTING="1"
+MANUAL_TICKETS="1"
+"${HARNESS_DIR}/create-wallet.sh" "$SESSION:7" "vspdwallet" ${VSPD_WALLET_SEED} \
+${VSPD_WALLET_RPC_PORT} ${USE_SPV} ${ENABLE_VOTING} "_" ${MANUAL_TICKETS} "_"
+
+echo "Creating simnet vspd"
+ALPHA_WALLET_PUBKEY=$("${NODES_ROOT}/harness-ctl/alpha" "getmasterpubkey")
+"${HARNESS_DIR}/create-vspd.sh" "$SESSION:8" "${VSPD_PORT}" "${ALPHA_WALLET_PUBKEY}"
+
```
Comment (buck54321) [inline dex/testing/dcr/harness.sh:323]: I had to update the vspd commit in **create-vspd.sh**, otherwise vspd crashed.

File: client/asset/dcr/spv.go [hunk 7]
```diff
@@ -95,20 +94,31 @@ type dcrWallet interface {
...
+	AgendaChoices(ctx context.Context, ticketHash *chainhash.Hash) (choices map[string]string, voteBits uint16, err error)
+	NewVSPTicket(ctx context.Context, hash *chainhash.Hash) (*wallet.VSPTicket, error)
 	// TODO: Rescan and DiscoverActiveAddresses can be used for a Rescanner.
+
+	// VSP client methods
+	SetPublished(ctx context.Context, hash *chainhash.Hash, published bool) error
+	AbandonTransaction(ctx context.Context, hash *chainhash.Hash) error
+	SignMessage(ctx context.Context, msg string, addr stdaddr.Address) (sig []byte, err error)
+	CreateVspPayment(ctx context.Context, tx *wire.MsgTx, fee dcrutil.Amount,
+		feeAddr stdaddr.Address, feeAcct uint32, changeAcct uint32) error
```
Comment (buck54321) [inline client/asset/dcr/spv.go:115]: I commented these out and everything still worked fine. What's the purpose of adding these to the interface?

**Review by buck54321 — CHANGES_REQUESTED** [review]
Two comments illustrated [here](https://github.com/buck54321/dcrdex/compare/a8d7dbf...buck54321:dcrdex:update-vspd).

File: client/asset/dcr/spv.go (hunk 7 above)
Comment (JoeGruffins) [reply client/asset/dcr/spv.go:115]: Yeah I'm sorry. I was planning to add an interface over in dcrwallet. Not needed now so removing.

**Comment by JoeGruffins** [comment]
Just rebased.

File: dex/testing/dcr/harness.sh (hunk 6 above)
Comment (JoeGruffins) [reply dex/testing/dcr/harness.sh:323]: hmm, its crashing for me after updating

Comment (JoeGruffins) [reply dex/testing/dcr/harness.sh:323]: Oh, I had to update my system's vspd binary

File: client/asset/dcr/spv.go (hunk 7 above)
Comment (JoeGruffins) [reply client/asset/dcr/spv.go]: Removed.

File: dex/testing/dcr/harness.sh (hunk 6 above)
Comment (JoeGruffins) [reply dex/testing/dcr/harness.sh:323]: Updated to latest release version `release-v1.3.2`

**Comment by JoeGruffins** [comment]
Removed the interface methods and updated vspd version in the harness https://github.com/decred/dcrdex/compare/ced0579ac849baf5dd086af4df2ca36d796ea7a3..e4a9b00143d071d040ac282750e4031696aeabc4

**Review by buck54321 — APPROVED** [review]
Just needs a rebase.

**Comment by JoeGruffins** [comment]
Rebased and updated to 4.1.1
