### PR TITLE
multi: house cleaning and bug fixes

### LINKED ISSUE #3276: Invalid Identical Comparison
>  identical expressions on the left and right side of the '==' operator (staticcheck)

@JoeGruffins is this intended? I doubt.

This change was introduced in: https://github.com/decred/dcrdex/issues/3221

I'm fixing in an incoming housecleaning PR.

https://github.com/decred/dcrdex/blob/36ce1b55fcd22c8e6403719bb3ea687256efc26a/tatanka/client/orderbook/orderbook.go#L121-L127

### PR DESCRIPTION
**Pull request by ukane-philemon**
This PR fixes over 40% of issues reported by `golangci-lint -c ./.golangci.yml run`.

Commits include fixes for bugs e.g (https://github.com/decred/dcrdex/commit/c0e05fb0f9f05ccfdfab56ab32af3e8418546651, https://github.com/decred/dcrdex/commit/548524eb696b718c7d31dca9f5c3fdccb5972b18, https://github.com/decred/dcrdex/commit/0c588f35cf27786e822017ccd2b0370f94b6be16), code improvements, removal or commenting of unused var/methods.

Closes #3276

### CODE REVIEW

File: client/mm/exchange_adaptor.go [hunk 1]
```diff
@@ -2428,14 +2429,17 @@ func (u *unifiedExchangeAdaptor) tryCancelOrders(ctx context.Context, epoch *uin
...
 			u.log.Errorf("Error canceling CEX trade %s: %v", tradeID, err)
+		} else {
+			cexCancels++
 		}
 	}
 
-	return done
+	totalCancels := dexCancels + cexCancels
+	expectedCancels := len(u.pendingDEXOrders) + len(u.pendingCEXOrders)
+	return totalCancels == expectedCancels
```
Comment (JoeGruffins) [inline client/mm/exchange_adaptor.go:2442]: This looks different. It was checking order status, not the number of all orders. This will have more expectedCancels than is really expected. They aren't all expected to be canceled.

Comment (ukane-philemon) [reply client/mm/exchange_adaptor.go:2442]: i.e expectedCancels = number of uncompleted  trades(if cex) + number of orders in the free cancel orders (dex)

We need to be able to keep track of them in this function to be able to accurately report to the caller whether or not all “cancel-able”orders were actually cancelled.

Will update this.

Comment (JoeGruffins) [reply client/mm/exchange_adaptor.go:2442]: I'm don't understand what the problem is. `cancels` looks unused, so remove that, but I don't see why the rest was wrong.

Comment (JoeGruffins) [reply client/mm/exchange_adaptor.go:2442]: maybe @martonp can comment if they see this

Comment (martonp) [reply client/mm/exchange_adaptor.go:2442]: The function `tryCancelOrders` cancels all cancellable orders, but it reports when no further orders remain to be canceled. Its return value is used in `cancelAllOrders` to signal that the function can complete and the bot can shut down. If there are still orders on the books that were placed too recently to be cancelled, we don't want to shut down the bot yet.

Comment (martonp) [reply client/mm/exchange_adaptor.go:2442]: Why are you changing this btw? Did you encounter any issues related to this?

**Comment by JoeGruffins** [comment]
@martonp said this can be removed, unsure though.

```
if !cancelCEXOrders {
		return false
}
```

Should it return true if all the dex orders are canceled then instead of false?

I guess I see the initial problem, you want to still return true if we are able to cancel the cancel-able ones?

Also, I don't think there needs to be two `successfulXXX` variables, cant they be combined like expected?

File: client/mm/exchange_adaptor.go (hunk 1 above)
Comment (JoeGruffins) [reply client/mm/exchange_adaptor.go]: @martonp said this can be removed, unsure though.

```
if !cancelCEXOrders {
		return false
}
```

Should it return true if all the dex orders are canceled then instead of false?

I guess I see the initial problem, you want to still return true if we are able to cancel the cancel-able ones?

Also, I don't think there needs to be two `successfulXXX` variables, cant they be combined like expected?

Comment (ukane-philemon) [reply client/mm/exchange_adaptor.go]: From the way the method is used, we can’t remove that early return and I think the rationale for returning false is because there might be some cancel-able CEX orders.

Yes.

Errm, yes.

Comment (martonp) [reply client/mm/exchange_adaptor.go]: Sorry, my mistake, that block should not be removed.
The current update is not correct though, because don't to be returning true if all cancellable orders were cancelled. We want to be returning true when all the orders have already been cancelled.

Comment (JoeGruffins) [reply client/mm/exchange_adaptor.go]: Ok, sorry for the long back and forth, but I think all that needs to change is the removal of the unused slice, the done variable was fine.

Comment (ukane-philemon) [reply client/mm/exchange_adaptor.go]: I will revert the changes in this function, I think @martonp can look through it at a later time to see what needs improvement. 

IMO, done is never true unless cancel was not tried on any order.

Comment (JoeGruffins) [reply client/mm/exchange_adaptor.go]: it starts true

**Review by JoeGruffins — APPROVED** [review]

File: client/mm/exchange_adaptor.go (hunk 1 above)
Comment (martonp) [reply client/mm/exchange_adaptor.go]: > IMO, done is never true unless cancel was not tried on any order.

Yes, that's the point.

Comment (ukane-philemon) [reply client/mm/exchange_adaptor.go]: Ah okay…gotcha.
