### PR TITLE
UI: fix incorrect usd fee error when sending usdc

### LINKED ISSUE #3457: USDC/Polygon wallet irregularities
I am working with a frtesh dcrdex 1.0.5 install, restored from seed from other working instance and noticing a couple of issues:
 
- Inbound UDSC/Polygon transactions  don't appear in the Transaction History. The balance does update correctly.

Image

- Incorrect calculation of fee estimate in USD:

Image

### PR DESCRIPTION
**Pull request by JustinBeBoy**
~Close #3457~

This PR: 
- fix incorrect usd fee error when sending usdc.
- Add a polling-based scanner with block-range chunking to retrieve transaction history.

Screen Shot:
- USD fee:
<p align="center">
p1
p2
p3
</p>

- Transaction history

before:

<p align="center">
p1
p2
</p>

after:

pr1

### CODE REVIEW

**Review by peterzen — APPROVED** [review]
LGTM. Thank you for working on this @JustinBeBoy .

**Comment by JustinBeBoy** [comment]
> LGTM. Thank you for working on this @JustinBeBoy .

There's still an issue regarding the transaction history that I'm trying to resolve.

**Comment by JoeGruffins** [comment]
Looks good. I notice there is a usd price here for the base coin but not for the token. Under Amount. Can you try to fix it too?

image
image

**Comment by JustinBeBoy** [comment]
> Looks good. I notice there is a usd price here for the base coin but not for the token. Under Amount. Can you try to fix it too?
> 
> image image

Let me fix it.

**Comment by JoeGruffins** [comment]
I'm not sure the transactions not showing up is a bug. Will put more on the issue.

**Comment by JoeGruffins** [comment]
As @martonp said on the issue, we might not be able to get the incoming transactions. If you just fix the amounts with this pr it's fine. Maybe a note in the UI about not showing incoming transactions if you are ok with making that. Don't worry about it too much as may be impossible currently.

**Comment by JustinBeBoy** [comment]
> Looks good. I notice there is a usd price here for the base coin but not for the token. Under Amount. Can you try to fix it too?
> 
> image image

I've researched this issue, and it might not be a bug, but rather that rate sources could be disabled or failing (network error, API rate limit), hiding the USD element. It seems that stablecoins like USDC might not be supported by all APIs.

**Comment by JoeGruffins** [comment]
> I've researched this issue, and it might not be a bug, but rather that rate sources could be disabled or failing (network error, API rate limit), hiding the USD element. It seems that stablecoins like USDC might not be supported by all APIs.

Ok no big deal. If it's not a bug just leave it.

File: client/asset/eth/eth.go [hunk 1]
```diff
@@ -7265,6 +7284,376 @@ func (w *TokenWallet) WalletTransaction(ctx context.Context, txID string) (*asse
...
+	const maxChunkSize = 5000
+	const largeGapThreshold = 10000
+
+	// Get last scanned block
+	lastScanBlock, err := w.txDB.GetLastIncomingScanBlock(&w.assetID)
+	if errors.Is(err, ErrNeverScanned) {
+		lastScanBlock = 0
+	} else if err != nil {
+		w.log.Errorf("Error getting last scan block for asset %d: %v", w.assetID, err)
+		return fmt.Errorf("error getting last scan block: %w", err)
```
Comment (JoeGruffins) [inline client/asset/eth/eth.go]: Will this log twice? If so no need for the extra log.

File: client/asset/eth/eth_test.go [hunk 2]
```diff
@@ -651,6 +661,33 @@ func (db *tTxDB) getBridgeCompletions(initiationTxID string) ([]*extendedWalletT
...
+	}
+	key := "ETH"
+	if assetID != nil {
+		key = fmt.Sprintf("%d", *assetID)
+	}
+	db.lastIncomingScanBlocks[key] = block
+	return nil
+}
+
+func (db *tTxDB) GetLastIncomingScanBlock(assetID *uint32) (uint64, error) {
```
Comment (JoeGruffins) [inline client/asset/eth/eth_test.go]:
```suggestion
func (db *tTxDB) LastIncomingScanBlock(assetID *uint32) (uint64, error) {
```

Can leave out the Get in golang.

File: client/asset/eth/eth.go [hunk 3]
```diff
@@ -5277,10 +5279,27 @@ func (eth *ETHWallet) checkForNewBlocks(ctx context.Context) {
...
+			}
+		}
+	}
+
+	// Scan incoming ETH transfers for base wallet
+	// Note: ETH scanning is expensive and may be skipped in production
+	// For now, we focus on token transfers which use event logs
+	if err := eth.scanIncomingETHTransfers(ctx, bestHdr.Number.Uint64()); err != nil {
+		eth.log.Errorf("Error scanning incoming ETH transfers: %v", err)
 	}
```
Comment (JoeGruffins) [inline client/asset/eth/eth.go]: It looks like this doesn't do anything currently. Can remove all code related to it.

Scanning every block for transactions is not feasible. There are over 24 million blocks atm and the block time is 12 seconds. We MUST have the transactions already indexed, somehow, somewhere. Probably would need to just ask a block explorer.

File: client/asset/eth/eth.go [hunk 4]
```diff
@@ -7265,6 +7284,376 @@ func (w *TokenWallet) WalletTransaction(ctx context.Context, txID string) (*asse
...
+
+	// Determine scan range
+	var startBlock uint64
+	isInitialSync := lastScanBlock == 0
+	if isInitialSync {
+		// Initial sync: scan last 1000 blocks
+		if tip > 1000 {
+			startBlock = tip - 1000
+		} else {
+			startBlock = 0
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/eth/eth.go]: Oh sorry, it's only going 1000 blocks back if initial sync. Its should be from the app birthday though... eth would be making 3600 blocks a day? idk...
