### PR TITLE
client/core: Check deposit addr in reconfigure.

### LINKED ISSUE #1136: cannot reconfigure wallet even though it's the same wallet
I've gotten the new error even when it's the same wallet:

2021-07-23 10:25:20.548 [ERR] WEB: reconfig error: new wallet cannot be used with current active trades: unable to change wallets **with active trades**. Trades with this wallet must match or be canceled in order to change settings

image

This one was DCR, but the issue could be Core logic.

### PR DESCRIPTION
**Pull request by JoeGruffins**
Rather than search for addresses in contracts, use the deposit address
    to determine if the new wallet is the same as the old one.

closes #1136

### CODE REVIEW

File: client/core/core.go [hunk 1]
```diff
@@ -2008,66 +2009,27 @@ func (c *Core) ReconfigureWallet(appPW, newWalletPW []byte, assetID uint32, cfg
...
-					"order to change settings")
+		}
+		if hasActiveTrade {
+			owns, err := wallet.OwnsAddress(oldDepositAddr)
+			if err != nil {
+				return err
+			}
+			if !owns {
+				return errors.New("new wallet does not own old deposit address")
+
```
Comment (JoeGruffins) [inline client/core/core.go:2032]: Extra new line.

**Review by martonp — APPROVED** [review]
Looks good.

File: client/core/core.go [hunk 2]
```diff
@@ -2016,66 +2017,26 @@ func (c *Core) ReconfigureWallet(appPW, newWalletPW []byte, assetID uint32, cfg
...
-					// If we did not find a refund address,
-					// we cannot be sure that this is the
-					// same wallet.
-					//
-					// TODO: Implement a way to check that
-					// these accounts are the same or not.
-					maybeDifferentWallet = true
+				if trade.wallets.toAsset.ID == waID || trade.wallets.fromAsset.ID == waID {
+					hasActiveTrade = true
+					break
```
Comment (chappjc) [inline client/core/core.go:2029]: Without the `RefundAddress` work going on, we can reduce this with `hasActiveAssetOrders`:

```go
			if dc.hasActiveAssetOrders(wallet.AssetID) {
				hasActiveTrade = true
				break
			}
```

File: client/core/core.go [hunk 3]
```diff
@@ -2016,66 +2017,26 @@ func (c *Core) ReconfigureWallet(appPW, newWalletPW []byte, assetID uint32, cfg
...
-					"trades with this wallet must match or be canceled in " +
-					"order to change settings")
+		}
+		if hasActiveTrade {
+			owns, err := wallet.OwnsAddress(oldDepositAddr)
+			if err != nil {
+				return err
+			}
+			if !owns {
+				return errors.New("new wallet does not own old deposit address")
```
Comment (chappjc) [inline client/core/core.go:2039]: Best to mention that this is a problem because there are active trades.

**Review by chappjc — CHANGES_REQUESTED** [review]

File: client/core/core.go (hunk 2 above)
Comment (JoeGruffins) [reply client/core/core.go]: Using.

File: client/core/core.go [hunk 4]
```diff
@@ -1959,66 +1960,25 @@ func (c *Core) ReconfigureWallet(appPW, newWalletPW []byte, assetID uint32, cfg
...
-			}
-			return nil
-		}
+		hasActiveTrade := false
 		for _, dc := range c.dexConnections() {
-			maybeDifferentWallet := false
 			for _, trade := range dc.trackedTrades() {
 				if !trade.isActive() {
 					continue
 				}
```
Comment (chappjc) [inline client/core/core.go:1968]: I think you wanted to get rid of the `dc.trackedTrades` loop entirely, right?

Comment (JoeGruffins) [reply client/core/core.go]: Is it correct now?

Comment (chappjc) [reply client/core/core.go]: Yup pretty sure.  hasActiveAssetOrders loops through for us

**Review by chappjc — APPROVED** [review]
