### PR TITLE
client/asset/eth: Fix eth receipt locktime.

### LINKED ISSUE #1592: eth: Bad locktime.
Have seen this lately. Not sure why, but a recent change seems to have caused locktime to not be set sometimes on simnet. 

```
2022-04-21 10:38:15.015 [INF] CORE: Broadcasted transaction with 1 swap contracts for order 7ea3b9ba72cb6ba2e736dee946ac048a2e6a8d21b855f75fd7c97f360277de15. Assigned fee rate = 200. Receipts (eth): [{ tx hash: 9e2c1a54758baff2cdd332c3f33da13758fd4647788d756f1cd14af70f7f7a72, contract address: 0x2f68E723b8989BA1C6a9F03E42F33cb7Dc9D606f, secret hash: 24b95c6d09bfa306db01ace478b8bc21c955f83e8f5354927bfd8c95f81020bc }].
2022-04-21 10:38:15.016 [INF] CORE: Contract coin 9e2c1a54758baff2cdd332c3f33da13758fd4647788d756f1cd14af70f7f7a72 (eth), value = 10000000000, refundable at 1970-01-20 02:29:37.095 +0000 UTC (script = 0000000024b95c6d09bfa306db01ace478b8bc21c955f83e8f5354927bfd8c95f81020bc), match = 287e1435c2465670e4a2911994a39683f53c922f32483e9a1b6213e762dee3ed
```

refundable at 1970-01-20 02:29:37.095 +0000 UTC

So, not completely nil? I guess locktime taker added to zero time rather than now somewhere.

### PR DESCRIPTION
**Pull request by JoeGruffins**
Parse locktime as seconds because it is seconds and not milliseconds.

closes #1592

### CODE REVIEW

**Comment by JoeGruffins** [comment]
With shorter locktimes, eth swaps never complete. Even if the tx has been mined 20 blocks ago and the tx can for sure be fetched by the console. Related to  #1561

File: client/asset/eth/eth.go [hunk 1]
```diff
@@ -780,7 +780,7 @@ func (eth *ExchangeWallet) Swap(swaps *asset.Swaps) ([]asset.Receipt, asset.Coin
 		copy(secretHash[:], swap.SecretHash)
 		receipts = append(receipts,
 			&swapReceipt{
-				expiration:   encode.UnixTimeMilli(int64(swap.LockTime)),
+				expiration:   time.Unix(int64(swap.LockTime), 0),
```
Comment (chappjc) [inline client/asset/eth/eth.go:783]: Wow, good catch @JoeGruffins. Yikes.  I can confirm the other assets like DCR are indeed treating this `Contract.LockTime` field as seconds.   Also that `(*Core).swapMatchGroup` is preparing it in **seconds** like `matchTime.Add(t.lockTimeTaker).UTC().Unix()`.

So, righteous fix!  Only thing I think we should change is the docs on the `client/asset.Contract.LockTime` field so that it states the units.

File: client/cmd/dexcctl/simnet-setup.sh [hunk 2]
```diff
@@ -2,6 +2,9 @@
 # Set up DCR and BTC wallets and register with the DEX.
 # dcrdex, dexc, and the wallet simnet harnesses should all be running before
 # calling this script.
+#
+# dexc should be built with -ldflags "-X 'decred.org/dcrdex/dex.testLockTimeTaker=30s' -X 'decred.org/dcrdex/dex.testLockTimeMaker=1m'"
+# in order to mirror the default server simnet locktimes.
```
Comment (chappjc) [inline client/cmd/dexcctl/simnet-setup.sh:7]: BTW, when doing interactive testing, I usually rebuild server with longer lock times.
With eth and propagation often taking a minute on testnet, I suspect we'll want to change increase this.

File: client/asset/eth/eth.go (hunk 1 above)
Comment (buck54321) [reply client/asset/eth/eth.go:783]: > Also, looks to have been broken in November, so it was once correct anyway.

Damn. That was me.

File: client/cmd/dexcctl/simnet-setup.sh (hunk 2 above)
Comment (buck54321) [reply client/cmd/dexcctl/simnet-setup.sh:7]: Any thoughts on using a Makefile for this stuff?

Comment (chappjc) [reply client/cmd/dexcctl/simnet-setup.sh:7]: Could.  I like your `build` and `run` scripts you added for server though.  But to start up the harness without the short lock times, I can see how a make file would be nice, like `make interactive` for longer lock times suitable for interactive testing vs `make scripted` suitable for the scripted harness trade tests.

@JoeGruffins I'm not sure what everyone's workflow looks like, but I should clarify that in general, I advise against any kind of interactive tests with these 30sec/1min lock times.  They are only good for for the *scripted* simnet tests.

Comment (JoeGruffins) [reply client/cmd/dexcctl/simnet-setup.sh]: Changed the wording to only inform it can be changed in that manner.

**Review by chappjc — APPROVED** [review]

File: client/asset/eth/eth.go (hunk 1 above)
Comment (JoeGruffins) [reply client/asset/eth/eth.go:783]: is "UNIX seconds" correct English
