### PR TITLE
Fix logout error when have no active orders

### LINKED ISSUE #397: cannot logout with active orders when there are no active orders
Make two trades, have them completely settle:

image

(note "excecuted" typo is fixed in https://github.com/decred/dcrdex/pull/399)

Click logout:

image

Restarting dexc, logging back in, and trying again lets you logout.

@song50119

### PR DESCRIPTION
**Pull request by song50119**
#### Resolves #397 

Refresh dexConnection, retrieve all active orders in database updating to dexConnection and establishes a ws connection to a DEX server

### CODE REVIEW

File: client/webserver/api.go [hunk 1]
```diff
@@ -219,7 +219,13 @@ func (s *WebServer) apiLogin(w http.ResponseWriter, r *http.Request) {
...
 // apiLogout handles the 'logout' API request.
 func (s *WebServer) apiLogout(w http.ResponseWriter, r *http.Request) {
-	err := s.core.Logout()
+	err := s.core.RestartDEXConnections()
+	if err != nil {
+		s.writeAPIError(w, "logout error: %v", err)
+		return
+	}
+
+	err = s.core.Logout()
```
Comment (buck54321) [inline client/webserver/api.go:228]: I'm not quite following the reasoning here. Why are we reconnecting in order to sign out?

Comment (buck54321) [reply client/webserver/api.go:228]: Ah. Probably because it refreshes the order list. If so, this is pretty heavy handed. I think what we really need is a function `func (dc *dexConnection) hasActiveOrders() bool` that just says whether the `dexConnection` has any orders that are `< order.MakerRedeemed`.

Comment (song50119) [reply client/webserver/api.go:228]: Sure, I'll look around with

File: client/core/core.go [hunk 2]
```diff
@@ -128,6 +128,18 @@ func (dc *dexConnection) hasOrders(assetID uint32) bool {
 	return false
 }
 
+// hasActiveOrders checks whether there are any active orders for the dexConnection.
+func (dc *dexConnection) hasActiveOrders() bool {
+	dc.tradeMtx.RLock()
+	defer dc.tradeMtx.RUnlock()
+	for _, trade := range dc.trades {
+		if trade.metaData.Status < order.OrderStatus(order.MakerRedeemed) {
```
Comment (chappjc) [inline client/core/core.go:136]: A couple issue with this:
1. Casting from `MatchStatus` to `OrderStatus` isn't meaningful.
2. We can't do arithmetic reliably with `order.OrderStatus`.  We'd have to `switch` on `OrderStatus` to determine if it is active (active orders are `OrderStatusEpoch` and `OrderStatusBooked`).

Comment (buck54321) [reply client/core/core.go]: And an order can also be cancelled or executed, but still have active matches with `(*matchTracker).MetaData.Status < order.MakerRedeemed`. That needs to be checked as well.

Comment (song50119) [reply client/core/core.go]: Screen Shot 2020-05-28 at 02 22 21

There is three orders with diff status, but when I log the length of `dc.trades[order.OrderID].matches` always return 0

File: client/core/core.go [hunk 3]
```diff
@@ -128,6 +128,24 @@ func (dc *dexConnection) hasOrders(assetID uint32) bool {
...
+func (dc *dexConnection) hasActiveOrders() bool {
+	dc.tradeMtx.RLock()
+	defer dc.tradeMtx.RUnlock()
+
+	for _, trade := range dc.trades {
+		for _, match := range trade.matches {
+			if match.MetaData.Status < order.MakerRedeemed {
+				return true
+			}
+		}
```
Comment (buck54321) [inline client/core/core.go:141]: You'll need to lock the `(*trackedTrade).matchMtx` while iterating `trade.matches`. I'd suggest you move this loop to a method on the `trackedTrade` and use a `defer` to unlock.
