### PR TITLE
client/comms: ensure server goroutine runs before attempting ws conns

### LINKED ISSUE #407: client/comms: server not listening when client connection is attempted
After merge of PR  , I occasionally get errors in CI and on my local machine at https://github.com/decred/dcrdex/blob/master/client/comms/wsconn_test.go#L227

`TestWsConn: wsconn_test.go:227: failed to get ErrCertRequired for no cert connection`

I supplemented the error and it seems that the cause is the server not yet listening when the connection attempt is made:

```
 $   go test -v -short -race -count 1 -tags pgonline ./client/comms/...
=== RUN   TestWsConn
2020-05-25 11:15:59.368 [INF] Debug: Generating TLS certificates...
2020-05-25 11:15:59.446 [INF] Debug: Done generating TLS certificates
    TestWsConn: wsconn_test.go:227: failed to get ErrCertRequired for no cert connection, got dial tcp 127.0.0.1:6060: connect: connection refused
http: Server closed
--- FAIL: TestWsConn (0.11s)
FAIL
FAIL	decred.org/dcrdex/client/comms	0.122s
FAIL
```

This is because the server is started in a goroutine, and a connection attempt is made immediately after.  This demonstrates how we should never assume the code inside a goroutine is run immediately:

https://github.com/decred/dcrdex/blob/1bc5777289db4d612521e18b7ddfd3c30b6d51fa/client/comms/wsconn_test.go#L197-L203 

We need to wait for ListenAndServer to actually start listening.

### PR DESCRIPTION
**Pull request by itswisdomagain**
Resolves #407.

### CODE REVIEW

File: client/comms/wsconn_test.go [hunk 1]
```diff
@@ -194,14 +194,19 @@ func TestWsConn(t *testing.T) {
...
+		serverReady <- struct{}{}
 		err := server.ListenAndServeTLS(certFile.Name(), keyFile.Name())
 		if err != nil {
 			fmt.Println(err)
 		}
 	}()
 
+	// wait for server to start listening before connecting
+	<-serverReady
+
```
Comment (itswisdomagain) [inline client/comms/wsconn_test.go:209]: I thought about adding a sleep here as well, but this should suffice, right?  This ensures that the server listen goroutine has begun execution before connections are attempted, but the server actually starts listening a very brief moment later, so before connections are attempted, the server should already be listening.

Comment (chappjc) [reply client/comms/wsconn_test.go:209]: The catch is that the channel send happens before it begins listening.  I don't see any way around a sleep unless we abandon `ListenAndServeTLS` in favor of something like

```
listen()
serverReady <- struct{}{}
serve()
```

Comment (itswisdomagain) [reply client/comms/wsconn_test.go]: What you've described is basically what `ListenAndServeTLS` does, so that's a preferred approach I think.
