### PR TITLE
electrum: Use wallet version 4.5.5 and up.

### LINKED ISSUE #2837: electrum: Unable to sign transactions on simnet.
I was unable to run electron on simnet at the current version `4.3.0a` but was after updating to `4.5.5`. Everything seems to be fine up until signing a transaction. I will get an error from client:
```
2024-06-21 06:36:32.125 [ERR] CORE: notify: |ERROR| (send) Send error - Error encountered while sending btc: signing error: code 2: "internal error while executing RPC", raw tx: 01000000013bce0b69d6da04e40be0290b6d46547b72e315ef272b677ca623fcdacfbbc3d70000000000ffffffff0100e1f50500000000160014d9f7ed80387da2e0b57afc93b7fd2a06eecc3f9700000000
2024-06-21 06:36:32.125 [ERR] WEB: send/withdraw error: signing error: code 2: "internal error while executing RPC", raw tx: 01000000013bce0b69d6da04e40be0290b6d46547b72e315ef272b677ca623fcdacfbbc3d70000000000ffffffff0100e1f50500000000160014d9f7ed80387da2e0b57afc93b7fd2a06eecc3f9700000000
```

The electrum client says:
```
2665.74 | E | daemon.CommandsServer | internal error while executing RPC
Traceback (most recent call last):
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/daemon.py", line 252, in handle
    response['result'] = await f(**params)
                         ^^^^^^^^^^^^^^^^^
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/commands.py", line 163, in func_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/commands.py", line 476, in signtransaction
    wallet.sign_transaction(tx, password, ignore_warnings=iknowwhatimdoing)
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/wallet.py", line 2543, in sign_transaction
    raise TransactionPotentiallyDangerousException('Not signing transaction:\n' + sh_danger.get_long_message())
electrum.wallet.TransactionPotentiallyDangerousException: Not signing transaction:
Warning: The fee could not be verified!
Warning: The input amounts could not be verified as the previous transactions are missing.
The amount of money being spent CANNOT be verified.
```

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes  #2837

### CODE REVIEW

File: client/asset/btc/electrum.go [hunk 1]
```diff
@@ -125,6 +127,28 @@ func (btc *ExchangeWalletElectrum) Connect(ctx context.Context) (*sync.WaitGroup
...
+	gotVer, err := dex.SemverFromString(verStr)
+	if err != nil {
+		return nil, err
+	}
+	if !dex.SemverCompatible(*wantVer, *gotVer) {
+		return nil, fmt.Errorf("wanted electrum wallet version %s but got %s", wantVer, gotVer)
+	}
+	// Patch 4.5.5 contains a breaking change that requires "iknowwhatimdoing"
+	// to be set to true when signing transactions. Lower versions will error
+	// if an unused arg is included.
```
Comment (JoeGruffins) [inline client/asset/btc/electrum.go:147]: I'm fairly sure this is true but unsure. I can downgrade to test.

Comment (JoeGruffins) [reply client/asset/btc/electrum.go]: I tried and was wrong about this.

**Comment by JoeGruffins** [comment]
Also work with ltc electrum https://github.com/decred/dcrdex/compare/e9ac3cba737ff996d03de9ed76cf16599bd03a8d..3303ccc462139048d215d7fe9254382d077d9785

File: client/asset/btc/electrum.go [hunk 2]
```diff
@@ -19,6 +19,11 @@ import (
 	"github.com/btcsuite/btcd/chaincfg/chainhash"
 )
 
+const (
+	needBTCElectrumVersion = "4.5.5"
+	needLTCElectrumVersion = "4.2.2"
+)
```
Comment (buck54321) [inline client/asset/btc/electrum.go:25]: There's a `MinNetworkVersion` field in the `BTCCloneCFG`. Can we use that so that these versions are set in their respective packages?

Comment (buck54321) [reply client/asset/btc/electrum.go:25]: Oh, that's an int and you need a string.

**Comment by buck54321** [comment]
> Also work with ltc electrum https://github.com/decred/dcrdex/compare/e9ac3cba737ff996d03de9ed76cf16599bd03a8d..3303ccc462139048d215d7fe9254382d077d9785
> 
> What others should I check?

Firo doesn't appear to be working. You should check Bitcoin Cash too.

File: client/asset/btc/electrum.go (hunk 2 above)
Comment (JoeGruffins) [reply client/asset/btc/electrum.go]: Added `MinElectrumVersion` and firo is working.. but not the txhistory, as firo does not to have the `onchain_history` method. https://github.com/decred/dcrdex/compare/4bc7ecb667be572b2580ca816621dd7c314b6009..202269e3de3c5220f38e2080b2c8ff6a5d0d38c0

**Comment by JoeGruffins** [comment]
> You should check Bitcoin Cash too.

Where is this? https://electroncash.org/ ?

File: client/asset/btc/electrum.go (hunk 2 above)
Comment (JoeGruffins) [reply client/asset/btc/electrum.go]: I was unable to build the firo electrum client, unsure how to fix and just used the binary

**Comment by dev-warrior777** [comment]
> You should check Bitcoin Cash too.

https://github.com/decred/dcrdex/blob/cb8327919526933a85d121e640665ce2f957d9c8/client/asset/bch/bch.go#L238


Creating BCH `walletTypeElectrum` wallet is currently commented out in `client/asset/bch/bch.go`

**Comment by JoeGruffins** [comment]
So, there can be btc, ltc, and firo. This should work with those three, with the tx history being broken for firo...

File: client/asset/btc/electrum.go [hunk 3]
```diff
@@ -130,16 +134,38 @@ func (btc *ExchangeWalletElectrum) Connect(ctx context.Context) (*sync.WaitGroup
...
+	if !dex.SemverCompatible(btc.minElectrumVersion, *gotVer) {
+		return nil, fmt.Errorf("wanted electrum wallet version %s but got %s", btc.minElectrumVersion, gotVer)
+	}
 
-	wg.Add(1)
-	go func() {
-		defer wg.Done()
-		dbWG.Wait()
-	}()
+	if btc.minElectrumVersion.Major >= 4 && btc.minElectrumVersion.Major >= 5 {
```
Comment (buck54321) [inline client/asset/btc/electrum.go:149]: Doesn't the second condition imply the first? And is this version correct for all assets?

Comment (JoeGruffins) [reply client/asset/btc/electrum.go:149]: Sorry that second one should be minor... did I even test this.

Only btc has made it to this version so far. 4.5.x

Comment (JoeGruffins) [reply client/asset/btc/electrum.go]: Changed the second Major to Minor. Sorry I forgot to push the rebase, but that was the only change.

**Review by buck54321 — APPROVED** [review]
