### PR TITLE
client/providers: Update EVM RPC providers

### LINKED ISSUE #3447: client/providers: Update free evm providers.
Some of the hard coded providers we have are no longer working. We need to update them. We are able to see which are working using the tests in /dcrdex/client/asset/eth

I commented out the ones we know should fail and ran with `go test --tags rpclive --run TestFreeServers`. The results:

```
!!!! "https://eth.drpc.org" PASSED 
!!!! "https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7" PASSED 
XXXX "https://rpc.builder0x69.io" FAILED : connect error: failed to connect to even a single provider among: builder0x69.io 
XXXX "https://rpc.ankr.com/eth" FAILED : connect error: failed to connect to even a single provider among: ankr.com 
XXXX "https://ethereum.blockpi.network/v1/rpc/public" FAILED : connect error: failed to connect to even a single provider among: blockpi.network 
XXXX "https://rpc.flashbots.net" FAILED : "TransactionReceipt" error: not found 
XXXX "wss://eth.llamarpc.com" FAILED : "TransactionReceipt" error: context deadline exceeded
```

We may need to remove some and would be good to add some more. Same for polygon and testnet on both.

### PR DESCRIPTION
**Pull request by JustinBeBoy**
Close #3447 

This PR replace non-functional RPC providers with reliable alternatives for Ethereum and Polygon networks.

### CODE REVIEW

File: client/asset/eth/eth.go [hunk 1]
```diff
@@ -708,23 +708,26 @@ func newWallet(assetCFG *asset.WalletConfig, logger dex.Logger, net dex.Network)
...
-			"wss://eth.llamarpc.com",
-			"https://eth.drpc.org",
+			"https://ethereum-rpc.publicnode.com", // PublicNode - 99.9% uptime, no rate limits
+			"https://eth.drpc.org",                // dRPC - 210M CU/30 days
+			"https://1rpc.io/eth",                 // 1RPC - privacy focused
+			"https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7", // NodeReal
+			"https://ethereum.blockpi.network/v1/rpc/public",                      // BlockPI - 10 req/sec
+			"https://rpc.flashbots.net",                                           // Flashbots - 80 req/sec
+			"https://rpc.builder0x69.io",                                          // MEV builder
 		}
```
Comment (JoeGruffins) [inline client/asset/eth/eth.go]: Test's show that only three of these work properly, should remove the others.

I see you added "https://1rpc.io/eth" for example, but for me the test is not finding a tx receipt for some reason. Do you know why?

**Review by JoeGruffins — COMMENTED** [review]
Looks great but the tests shows these don't seem to all be working at %100.

File: client/asset/eth/multirpc_live_test.go [hunk 2]
```diff
@@ -56,55 +56,36 @@ func TestRPC(t *testing.T) {
...
+	"https://eth.drpc.org",
+	"https://1rpc.io/eth",
+	"https://ethereum.blockpi.network/v1/rpc/public",
+	"https://rpc.flashbots.net",
+	"https://rpc.builder0x69.io",
+	"https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79",
+	"https://nodes.mewapi.io/rpc/eth",
+	"https://eth-mainnet-public.unifra.io",
+	"https://cloudflare-eth.com/",
 }
```
[the remark this answers is not in the document]
Comment (JustinBeBoy) [reply client/asset/eth/multirpc_live_test.go]: It seems those providers aren't operating reliably.

File: client/asset/eth/multirpc.go [hunk 3]
```diff
@@ -1548,6 +1548,9 @@ const (
 	providerAlchemy     = "alchemy.com"
 	providerAnkr        = "ankr.com"
 	providerdRPC        = "drpc.org"
+	providerBlastAPI    = "blastapi.io"
+	providerLlamaRPC    = "llamarpc.com"
+	providerPublicNode  = "publicnode.com"
```
Comment (JoeGruffins) [inline client/asset/eth/multirpc.go]: Should remove all the ones we know are not working now. so remove "drpc.org", "ankr.com", "flashbots.net", ....

File: client/asset/eth/multirpc_live_test.go [hunk 4]
```diff
@@ -56,55 +56,25 @@ func TestRPC(t *testing.T) {
...
-	"https://rpc.flashbots.net",                                           // Limits unknown
-	"wss://eth.llamarpc.com",                                              // Limits unknown
-	"https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7", // Limits might be 100M compute units at 300 CU/s
-	// Failing 03-26-2024
-	"https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79", // connect error: failed to connect to even a single provider among: pokt.network
-	"https://ethereum.publicnode.com",                                      // "TransactionReceipt" error: not found
-	"https://nodes.mewapi.io/rpc/eth",                                      // connect error: failed to connect to even a single provider among: mewapi.io
-	"https://eth.api.onfinality.io/public",                                 // connect error: failed to connect to even a single provider among: onfinality.io
-	"https://eth-mainnet-public.unifra.io",                                 // connect error: failed to connect to even a single provider among: unifra.io
-	"https://cloudflare-eth.com/",                                          // "SuggestGasTipCap" error: Method not found
```
Comment (JoeGruffins) [inline client/asset/eth/multirpc_live_test.go]: I think we should leave the failing ones in, even if you want to comment out so we know what didnt work in the past.

**Review by JoeGruffins — COMMENTED** [review]
I think just remove dRPC and this is good.

Unless the code can be changed to only need one of the header methods. I don't know currently if we can do this though.

**Review by JoeGruffins — APPROVED** [review]
