### PR TITLE
multi: Fix maxOrders panic.

### LINKED ISSUE #1085: rate below the rate step causes divide-by-zero panic
The recoverer middleware catches it.

image

image

### PR DESCRIPTION
**Pull request by JoeGruffins**
Ignore prices below the rate step in markets.js.

    Error on zero lots in MaxOrder.

    Use an estimation for number of starting lots that includes a basic fee.
    This lets estimations for very large orders start closer to the final
    fee.

closes #1085

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Extremely large orders would start with an initial lots estimate tens of millions of lots off of what we end up with. You can test this out with the simnet harness. I believe this code puts the initial lots closer to what we end up with.

**Comment by buck54321** [comment]
Seems righteous to prevent division by zero in the asset packages, but should we reject invalid parameters in **core** before it gets that far too?

**Comment by JoeGruffins** [comment]
Do mean specifically in core's `MaxBuy` and `MaxSell`?

**Comment by buck54321** [comment]
> Do you mean specifically in core's `MaxBuy` and `MaxSell`?

That sounds about right.

File: client/asset/btc/btc.go [hunk 1]
```diff
@@ -772,8 +773,9 @@ func (btc *ExchangeWallet) maxOrder(lotSize, feeSuggestion uint64, nfo *dex.Asse
 	if err != nil {
 		return nil, nil, fmt.Errorf("error parsing unspent outputs: %w", err)
 	}
-	// Start by attempting max lots with no fees.
-	lots := avail / lotSize
+	// Start by attempting max lots with a basic fee.
+	basicFee := nfo.SwapSize * nfo.MaxFeeRate
+	lots := avail / (lotSize + basicFee)
```
Comment (buck54321) [inline client/asset/btc/btc.go:778]: What is this `basicFee` adjustment for? This seems wrong. `estimateSwap` will use the feeSuggestion internally.

Comment (JoeGruffins) [reply client/asset/btc/btc.go:778]: I think it is returning before using the feeSuggestion at `tryFund`. 

The problem I am seeing is that the below estimateSwap will run an extreme number of times for large numbers of swaps if not including a fee. Please try on master with a small lot size and large amount of asset (dcr) and I believe your client will hang. Does it not?

Enter values similar to these on simnet.

image

Comment (chappjc) [reply client/asset/btc/btc.go:778]: Yes, confirmed.  It's a problem.  Even for more reasonable values, the loop (`for lots > 0 {`) iterates excessively and we don't always realize it.

When the starting `lots` is huge, as Joe described, it has to iterate a lot more to hit on the appropriate fees.  Note than the btc ExchangeWallet.maxOrder method, `avail` and `lotSize` are sats, so when you type 0.0001 as the rate in a buy order in a DCR-BTC market with 10 DCR lot size, it starts the method with `lotSize` of 100000.  With the default simnet BTC wallet, 44000000000 sats available, and that's 440000 starting lots.  It iterates down to 381611 lots, one lot less at a time.

It is correct that `estimateSwap` returns because fund/tryfund has an error with the provided number of lots, so the loop continues with one less lot, but it's often needing to iterate thousands of times and it effectively hangs.

I think we need to start with some fees as Joe is suggesting or rethink the maxOrder algo.  `basicFee := nfo.SwapSize * nfo.MaxFeeRate` does seem correct here.

Comment (chappjc) [reply client/asset/btc/btc.go:778]: With the proposed change:

```
avail: 44000000000  lotSize: 100000
start btc lots: 381613
final btc lots:  381611
```

So it only has to iterate twice to get the highest possible lots.

File: client/core/core.go [hunk 2]
```diff
@@ -2717,6 +2717,11 @@ func (c *Core) MaxBuy(host string, base, quote uint32, rate uint64) (*MaxOrderEs
 	}
 
 	quoteLotEst := calc.BaseToQuote(rate, baseAsset.LotSize)
+
+	if quoteLotEst == 0 {
+		return nil, errors.New("cannot divide by lot size zero")
+	}
+
```
Comment (chappjc) [inline client/core/core.go:2724]: Can go before `c.dex` and `c.feeSuggestion`, right after getting `baseAsset` from `marketWallets`

File: client/core/core.go [hunk 3]
```diff
@@ -2767,6 +2772,10 @@ func (c *Core) MaxSell(host string, base, quote uint32) (*MaxOrderEstimate, erro
 		return nil, fmt.Errorf("failed to get redeem fee suggestion for %s at %s", unbip(quote), host)
 	}
 
+	if baseAsset.LotSize == 0 {
+		return nil, errors.New("cannot divide by lot size zero")
+	}
```
Comment (chappjc) [inline client/core/core.go:2777]: Same move.

File: client/asset/interface.go [hunk 4]
```diff
@@ -93,7 +93,8 @@ type Wallet interface {
 	// associated fees that the wallet can support for the specified DEX. The
 	// fees are an estimate based on current network conditions, and will be <=
 	// the fees associated with the Asset.MaxFeeRate. For quote assets, lotSize
-	// will be an estimate based on current market conditions.
+	// will be an estimate based on current market conditions. lotSize must
+	// not be zero and will cause a panic if so.
```
Comment (chappjc) [inline client/asset/interface.go:97]: "will cause a panic if so" wording is awkward in an interface definition because it seems to instruct backend developers to have the backend panic instead of return error, but I think this comment was noting the observed behavior of the current backends, and the comment was meant as a caution to consumers.  I don't see a problem with an asset backend developer checking for zero lot size and returning an error rather than panic.

**Review by chappjc — APPROVED** [review]
This PR looks and works well.

For the squashed commit, is it accurate to summarize like the following (but I can do the actual squash)?

- client/asset: maxOrder fix for starting number of lots
- client/core: reject lot sizes of zero 
- js: Ignore prices below the rate step entered on Markets page

File: client/core/core.go (hunk 2 above)
Comment (JoeGruffins) [reply client/core/core.go:2724]: Ok.

File: client/core/core.go (hunk 3 above)
Comment (JoeGruffins) [reply client/core/core.go:2777]: Ok.

File: client/asset/interface.go (hunk 4 above)
Comment (JoeGruffins) [reply client/asset/interface.go:97]: Ok.

Comment (JoeGruffins) [reply client/asset/interface.go]: Hopefully did that right.

Comment (chappjc) [reply client/asset/interface.go]: I might have miscommunicated a bit.  "don't see a problem with an asset backend developer checking for zero lot size and returning an error rather than panic". So I just meant the interface comment saying it will panic was out of place.  I have absolutely no objection to the `if lotSize == 0 {` in maxOrder.  That was good.  Just that interface comments are fundamentally different from implementation comments in their purpose.

Comment (chappjc) [reply client/asset/interface.go]: > Hopefully did that right.

Yah, last commit looks great
