### PR TITLE
client/eth: balance change trigger pending txs recheck

### LINKED ISSUE #2243: client/testing/simnet-trade-tests: "notakerswap" on dcreth fails with client 2 as maker.
These tests have a history of being flakey, but `notakerswap` is consistently failing for dcr_eth only when client 2 is maker.
```
ERROR: test "notakerswap" failed with client 2 as maker: eth balance change not in expected range 0.005591700 - 0.006180300, got 0.000518972
```

### PR DESCRIPTION
**Pull request by buck54321**
Resolves #2243

Since tips are cached for 10 seconds, this adds a secondary method of recognizing a new state that requires confirmation checks on pending txs.

### CODE REVIEW

File: client/asset/eth/eth.go [hunk 1]
```diff
@@ -3828,18 +3839,15 @@ func (w *assetWallet) balanceWithTxPool() (*Balance, error) {
 		}
 	}
 
+	confirmed, err := getBal()
+	if err != nil {
+		return nil, fmt.Errorf("balance error: %v", err)
+	}
```
Comment (buck54321) [inline client/asset/eth/eth.go:3845]: This change was recommended by @martonp at https://github.com/decred/dcrdex/pull/2211#discussion_r1140800213. I thought I had already done this, but apparently not.

**Review by martonp — APPROVED** [review]

**Review by chappjc — APPROVED** [review]
