### PR TITLE
client: authDEX on reconnect.

### LINKED ISSUE #230: dexc: broken connection does not reauthorize on reconnect
I hit a bug with `dcrdex` (server side) that required me to restart the server.  I did not restart `dexc` however, and it did not seem to reconnect and authorize as expected:

```
[ERR] WEB: error placing order: cannot send on a broken connection
[INF] CORE: DEX at https://dex-test.ssgen.io:7232 has reconnected
[TRC] CORE: processing tip change for btc
[ERR] WEB: error placing order: rpc error: 26: cannot use route 'limit' on an unauthorized connection
[TRC] WEB: message of type 1 received for route unmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[ERR] WEB: error placing order: not enough to cover requested funds + fees = 734414800
[ERR] WEB: error cancelling order 248e2a93650a7da0eb9abcbcc58894b25c15a53bdf5949fa3da4b13694c3f898: rpc error: 26: cannot use route 'cancel' on an unauthorized connection
[TRC] WEB: message of type 1 received for route unmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route unmarket
[TRC] WEB: message of type 1 received for route loadmarket
[TRC] WEB: message of type 1 received for route unmarket
[TRC] WEB: message of type 1 received for route loadmarket
```

It did reconnect, but only after commanding the web UI to do something, not automatically.

### LINKED ISSUE #265: core: need to re-auth on dex reconnect
**client/comms** is passed a `ReconnectSync` function as part of it's configuration, so the core will be notified when a reconnection is made. Right now `(*Core).handleReconnect` just logs a message. The client should be re-authenticated (new `connect` request) when a reconnection is made.

### PR DESCRIPTION
**Pull request by JoeGruffins**
Re-auth connections found in the conns map.

Make reconnect intervals increase incrementally so that a user may not
have to wait a full minute for a reconnect.

Give comms a logger.

closes #230 
closes #265

### CODE REVIEW

File: client/comms/wsconn.go [hunk 1]
```diff
@@ -393,10 +403,6 @@ func (conn *wsConn) Send(msg *msgjson.Message) error {
 // Request sends the message with Send, but keeps a record of the callback
 // function to run when a response is received.
 func (conn *wsConn) Request(msg *msgjson.Message, f func(*msgjson.Message)) error {
-	if !conn.isConnected() {
-		return fmt.Errorf("cannot send on a broken connection")
-	}
-
```
Comment (JoeGruffins) [inline client/comms/wsconn.go:399]: Because this check happens at the beginning of Send, I thought it was redundant to have it here too.

File: client/core/core.go [hunk 2]
```diff
@@ -2066,6 +2066,11 @@ func (c *Core) setEpoch(epochIdx uint64) {
 // handleReconnect is called when a WsConn indicates that a lost connection has
 // been re-established.
 func (c *Core) handleReconnect(uri string) {
+	if dc, found := c.conns[uri]; found {
+		if err := c.authDEX(dc); err != nil {
+			log.Errorf("unable to authorize DEX at %s: %v", uri, err)
+		}
+	}
```
[the remark this answers is not in the document]
Comment (chappjc) [reply client/core/core.go:2073]: And a `c.notify(newOrderNote(...` for any error from `signAndRequest` [in `Trade`](https://github.com/decred/dcrdex/blob/492cce2fb210a5686dbb5c35d01b0f5269a24b34/client/core/core.go#L1280) and [in `Cancel`](https://github.com/decred/dcrdex/blob/492cce2fb210a5686dbb5c35d01b0f5269a24b34/client/core/core.go#L1436).

I feel like a similar notification regarding the reconnection attempt(s) would be nice too.

[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/core/core.go:2073]: I don't think a server is included in conns until authDEX is called. So, in the stages before the dex is registered, for example to get the fee, we have a ws client and a connection, but the server is not yet in the conns map.
Let me double check though.

[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/core/core.go:2073]: Spelling on line 1971, `initializing`? Clicking the link didn't show me anything for some reason.

[the remark this answers is not in the document]
Comment (chappjc) [reply client/core/core.go:2073]: > Ok, so it's in `Register` that it is added to the map. `PreRegister` is just a bit odd, but it looks like the connection might just be cut after a 'preregister' request in #328 so logging an error here is the right move.

They're also added in `(*Core).initialize` when starting dexc with DEXs configured in a previous session, so just by logging in it starts the authDEX process.

File: client/core/log.go [hunk 3]
```diff
@@ -25,4 +26,5 @@ func UseLoggerMaker(maker *dex.LoggerMaker) {
 	loggerMaker = maker
 	log = maker.Logger("CORE")
 	orderbook.UseLogger(maker.Logger("ORDBOOK"))
+	comms.UseLogger(maker.Logger("COMMS"))
```
[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/log.go:29]: Also `client/order` should be `client/orderbook` or maybe `client/core/orderbook`.

File: client/comms/wsconn.go [hunk 4]
```diff
@@ -298,13 +302,18 @@ func (conn *wsConn) keepAlive(ctx context.Context) {
 				log.Errorf("Reconnect failed: %v", err)
 				conn.reconnects++
 				if conn.reconnects+1 < maxReconnects {
-					conn.queueReconnect()
+					conn.queueReconnect(rcInt)
+					// Increment the wait up to PingWait.
+					if rcInt < conn.cfg.PingWait {
+						rcInt += reconnectInterval
+					}
```
Comment (buck54321) [inline client/comms/wsconn.go:309]: Should we cap `rcInt` at maybe a minute or two? `maxReconnects` is 20,000,000, and we want the client to be responsive when the DEX comes back online.

**Comment by JoeGruffins** [comment]
Now sending notifications on reconnections, but not attempts. Just want to make sure you want those as notifications, because it could potentially be a lot of notifications.

**Comment by buck54321** [comment]
What we really want to know is when the state of the connection **changes**. Right now, we only know when the connection is restored, not when it is lost. A disconnect callback similar to `WsCfg.ReconnectSync` is probably needed, and you'd have to distinguish between normal and erroneous shutdowns.

You'd also want `Core` to track the connection status internally in the `dexConnection` and add a field for connection status to the `Exchange`?

**Comment by JoeGruffins** [comment]
> What we really want to know is when the state of the connection **changes**. Right now, we only know when the connection is restored, not when it is lost. A disconnect callback similar to `WsCfg.ReconnectSync` is probably needed, and you'd have to distinguish between normal and erroneous shutdowns.
> 
> You'd also want `Core` to track the connection status internally in the `dexConnection` and add a field for connection status to the `Exchange`?

If you really think it is a good idea, ok. But there has been discussion about this in dcrd, and @davecgh would say that you simply can't say whether something is connected. You can say it has connected, and you can guess towards current connection status, but you can't say for certain that yes, this is connected, you can only try to communicate and deal with failures accordingly.

As only a notification to the user, the I think that it is fine, but it shouldn't be relied upon for operation.

https://github.com/decred/dcrd/issues/1877

**Comment by buck54321** [comment]
> As only a notification to the user, then I think that it is fine, but it shouldn't be relied upon for operation.

That's the intention, but good point. We should document that very loudly. 

Ultimately, I'd like to see a little indicator next to the DEX name in the markets view if the DEX is known to be disconnected.

**Comment by chappjc** [comment]
> But there has been discussion about this in dcrd, and @davecgh would say that you simply can't say whether something is connected. You can say it has connected, and you can guess towards current connection status, but you can't say for certain that yes, this is connected, you can only try to communicate and deal with failures accordingly.
> 
> As only a notification to the user, then I think that it is fine, but it shouldn't be relied upon for operation.
> 
> [decred/dcrd#1877](https://github.com/decred/dcrd/issues/1877)

You can say when it is NOT connected, with absolutely certainty.  We have direct access to the gorilla types, unlike witih rpcclient, we are ping/ponging at a known rate, we get errors when we try to send on a broken connection, and if the server hangs up gracefully with a Close controll frame then our connection knows immediately

I don't think that notifying of a disconnect implies that that it didn't disconnect earlier, just that it is definitely disconnected **now**.

**Comment by chappjc** [comment]
If submitting an order is the first of the actions that reveals the disconnect, that's fine, but it is then known to be disconnected and the UI should show that.

**Comment by JoeGruffins** [comment]
connected

Adds a connected symbol that is hidden/shown based on connection status. Please don't be shy when reviewing, I know my web is lacking.

**Comment by JoeGruffins** [comment]
Not sure this failure is my fault. I'm unable to hit it locally. I made an issue just in case #356 

However, while trying, I did hit this once, but not again:
<details closed>
<summary>log</summary>

```
2020-05-12 12:17:03.504 [INF] CORE: Notifying dex somedex.tld of fee payment.
2020-05-12 12:17:03.513 [INF] CORE: Attempting registration fee payment for someaddr of 100000000 units of dcr
==================
WARNING: DATA RACE
Write at 0x00c000522068 by goroutine 26:
  decred.org/dcrdex/client/core.(*Core).Register()
      /home/joe/git/dcrdex/client/core/core.go:918 +0x191c
  decred.org/dcrdex/client/core.TestRegister.func6()
      /home/joe/git/dcrdex/client/core/core_test.go:1054 +0xb9
  decred.org/dcrdex/client/core.TestRegister()
      /home/joe/git/dcrdex/client/core/core_test.go:1198 +0x1736
  testing.tRunner()
      /home/joe/.local/go/src/testing/testing.go:991 +0x1eb

Previous read at 0x00c000522068 by goroutine 34:
  decred.org/dcrdex/client/core.(*dexAccount).checkSig()
      /home/joe/git/dcrdex/client/core/types.go:358 +0x48
  decred.org/dcrdex/client/core.(*Core).notifyFee.func1()
      /home/joe/git/dcrdex/client/core/core.go:1154 +0x33d
  decred.org/dcrdex/client/core.TestRegister.func2.1()
      /home/joe/git/dcrdex/client/core/core_test.go:999 +0x22d
  decred.org/dcrdex/client/core.(*TWebsocket).Request()
      /home/joe/git/dcrdex/client/core/core_test.go:215 +0x193
  decred.org/dcrdex/client/core.(*Core).notifyFee()
      /home/joe/git/dcrdex/client/core/core.go:1142 +0x6d2
  decred.org/dcrdex/client/core.(*Core).Register.func2()
      /home/joe/git/dcrdex/client/core/core.go:952 +0x3d2
  decred.org/dcrdex/client/core.(*Core).tipChange.func1()
      /home/joe/git/dcrdex/client/core/core.go:2425 +0xa1

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /home/joe/.local/go/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /home/joe/.local/go/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /home/joe/.local/go/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /home/joe/.local/go/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /home/joe/.local/go/src/testing/testing.go:1199 +0x2ff
  decred.org/dcrdex/client/core.TestMain.func1()
      /home/joe/git/dcrdex/client/core/core_test.go:620 +0x7e
  decred.org/dcrdex/client/core.TestMain()
      /home/joe/git/dcrdex/client/core/core_test.go:622 +0x258
  main.main()
      _testmain.go:76 +0x223

Goroutine 34 (running) created at:
  decred.org/dcrdex/client/core.(*Core).tipChange()
      /home/joe/git/dcrdex/client/core/core.go:2418 +0x299
  decred.org/dcrdex/client/core.TestRegister.func3.1()
      /home/joe/git/dcrdex/client/core/core_test.go:1015 +0x2a0
==================
FAIL    decred.org/dcrdex/client/core   2.208s
?       decred.org/dcrdex/client/db     [no test files]
```
</details>

But idk if it was a fluke.

**Comment by chappjc** [comment]
@JoeGruffins Resolved the race in https://github.com/decred/dcrdex/pull/357, although the order id caching is a pain that we should reconsider or guard with a mutex.

File: client/core/core.go [hunk 5]
```diff
@@ -1473,6 +1482,8 @@ func (c *Core) Cancel(pw []byte, tradeID string) error {
 	var result = new(msgjson.OrderResult)
 	err = tracker.dc.signAndRequest(msgOrder, route, result)
 	if err != nil {
+		details := fmt.Sprintf("cancel: unable to signAndRequest: %v", err)
+		c.notify(newOrderNote("signAndRequest failure", details, db.ErrorLevel, nil))
```
Comment (buck54321) [inline client/core/core.go:1486]: Here too, prefer to display this error on the form that the user is interacting with rather than the notification tray.

**Comment by JoeGruffins** [comment]
If an exchange went offline it shows the disconnected glyph, but if you reloaded that page, the glyph would be removed because the user.Exchanges is still Connected.

There is probably a reason for user specific Exchanges data, but I am not sure what it is. This may not be the correct solution to the problem. Please advise.

**Comment by buck54321** [comment]
> If an exchange went offline it shows the disconnected glyph, but if you reloaded that page, the glyph would be removed because the user.Exchanges is still Connected.

If I'm understanding correctly, you can call `(*Core).refreshUser` at the end of `handleConnectEvent` to resolve this.

File: client/core/core.go [hunk 6]
```diff
@@ -2043,7 +2043,7 @@ func (c *Core) handleReconnect(uri string) {
 // NOTE: This handler is only used to post notifications to the user.
 func (c *Core) handleConnectEvent(uri string, connected bool) {
 	c.connMtx.Lock()
-	if dc, found := c.conns[uri]; found {
+	if dc, found := c.conns["https://"+uri]; found {
```
Comment (JoeGruffins) [inline client/core/core.go:2046]: Did something change here? could be something other that https?

Comment (chappjc) [reply client/core/core.go:2046]: It's eventually not going to have a scheme at all, but for the map lookup, definitely should not prepend with this.

File: client/core/core.go [hunk 7]
```diff
@@ -2013,7 +2024,41 @@ func (c *Core) setEpoch(epochIdx uint64) {
 // handleReconnect is called when a WsConn indicates that a lost connection has
 // been re-established.
 func (c *Core) handleReconnect(uri string) {
-	log.Infof("DEX at %s has reconnected", uri)
+	c.connMtx.RLock()
+	dc, found := c.conns["https://"+uri]
```
Comment (chappjc) [inline client/core/core.go:2028]: or here.  When did these predends sneak in?

File: client/comms/wsconn.go [hunk 8]
```diff
@@ -61,6 +61,11 @@ type WsCfg struct {
 	// ReconnectSync runs the needed reconnection synchronization after
 	// a disconnect.
 	ReconnectSync func()
+	// ConnectEventFunc runs whenever connection status changes.
+	//
+	// NOTE: These notifications are for aesthetic purposes only. They
+	// should not be relied upon for operation.
```
Comment (chappjc) [inline client/comms/wsconn.go:67]: I find the wording "relied upon for operation" too vague.  This says to me don't do anything with the event data except display it.  But I that is not the only thing you can do with it.  The receiver getting a connected=false event can certainly make use of that, stopping new orders from being submitted or otherwise changing the errors.  While connected=true does NOT mean that we guarantee the link is up until a connect=false event (submitting an order on a broken connection could trigger the disconnected state), it does mean we think it's connected and it's OK to try submitting orders.

File: client/core/core.go [hunk 9]
```diff
@@ -60,6 +60,12 @@ type dexConnection struct {
 
 	tradeMtx sync.RWMutex
 	trades   map[order.OrderID]*trackedTrade
+
+	// connected implies that the dex is connected.
+	//
+	// NOTE: This field is only used for notifications to the user, and
+	// should not be trusted in operations.
```
Comment (chappjc) [inline client/core/core.go:67]: Can we say why?  `wsConn.connected` is set when `dexConnection.connected` is set, although async (in a goroutine).  `connected=true` just means we think it is connected or rather we can treat it as connected until a send to the server could fail and the link will flip to `connected=false`, whereas `connected=false` means the link is definitely not connected and on reconnect it will be changed back to true.

I see no problem with modifying the client's behavior based on the best available information.

File: client/comms/wsconn.go (hunk 8 above)
Comment (chappjc) [reply client/comms/wsconn.go:67]: To recap the discussion with rpcclient and dcrd notifications, the objection to a disconnect notification was that the consumer might believe that it was connected up until the instant of the notification OR believe that the absence of the notification means the connection was never lost.  That could be especially problematic with rpcclient's auto-reconnect that could hide the state changes from the consumer.  I don't think any of this applies to DEX client.  We are managing the connection, with all reconnect attempts triggering this event (when wsConn first discovers it is broken and then when keepAlive>connect restores it).

File: client/core/core.go [hunk 10]
```diff
@@ -2028,9 +2039,29 @@ func (c *Core) handleReconnect(uri string) {
...
 	}
-	details := fmt.Sprintf("DEX at %s has reconnected", uri)
-	c.notify(newSystemNote("DEX reconnect", details, db.Success))
-	log.Infof(details)
+}
+
+// handleConnectEvent is called when a WsConn indicates that a connection was
+// lost or established.
+//
+// NOTE: This handler is only used to post notifications to the user.
```
Comment (chappjc) [inline client/core/core.go:2043]: "only use to post notifications"   But it also set sets each `dexConnection.connected` flag.  And I think that is good because dexConnection can do things differently if it believes to be disconnected.

**Comment by chappjc** [comment]
I think you can just undo the client/cmd/dexc/go.sum changes since it's not updated in master when building or go mod tidy.

**Comment by JoeGruffins** [comment]
Squashing before rebase.

**Comment by JoeGruffins** [comment]
depends on #386

**Comment by chappjc** [comment]
There seem to be a number of frontend errors now, and it's not showing the icon:

image

**Comment by chappjc** [comment]
Uh oh, the markets.js error is on master now. Must have snuck in with PR #386 .

`TypeError: can't access property "markets", U.user.exchanges[t.dex.url] is undefined markets.js:385:15`

**Comment by chappjc** [comment]
JS errors resolved in https://github.com/decred/dcrdex/pull/399, but please do review that.

**Comment by chappjc** [comment]
When squashed and rebased on PR #399 it works as expected:

image

Although the logs have an error.  Is this expected in this sequence?

```
[ERR] COMMS: read error (websocket: close 1006 (abnormal closure): unexpected EOF), attempting reconnection
[INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
[ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
[INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 5 seconds.
[WRN] CORE: notify: |WARNING| (conn) DEX disconnected - DEX at 127.0.0.1:7232 has disconnected
[INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
[ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
[INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 10 seconds.
[INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
[ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
[INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 15 seconds.
[INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
[INF] COMMS: Successfully reconnected.
[ERR] CORE: unable to authorize DEX at 127.0.0.1:7232: signing error: account locked
[INF] CORE: notify: |SUCCESS| (conn) DEX connected - DEX at 127.0.0.1:7232 has connected
[TRC] WEB: message of type 1 received for route loadmarket
```

**Comment by JoeGruffins** [comment]
@chappjc this one?
`[ERR] CORE: unable to authorize DEX at 127.0.0.1:7232: signing error: account locked`

**Comment by chappjc** [comment]
Yup.  Maybe that's nothing though.  I didn't debug it.

**Comment by chappjc** [comment]
Looks like we both revised the `// Form 4: ` comment. Sorry about that.  I don't really care too much about this particular comment, so resolve however you see fit.

**Comment by JoeGruffins** [comment]
Acutally, I had just rebased over your pr, now rebased on master.

**Comment by JoeGruffins** [comment]
I think you hit that because you had not gone through `login` yet, so it is correct that the account is locked and keys are not in memory so we can't sign the connect msg.

**Comment by chappjc** [comment]
I had just setup and unlocked wallets, so it must have been logged in, right?

Some more context:

```
2020-05-21 10:39:52.512 [INF] CORE: Connected to DEX server at 127.0.0.1:7232 and listening for messages.
2020-05-21 10:39:52.512 [DBG] CORE: connectDEX for 127.0.0.1:7232 completed, checking account...
2020-05-21 10:39:52.512 [DBG] CORE: dex connection to 127.0.0.1:7232 ready
2020-05-21 10:39:52.512 [INF] CORE: Successfully connected to 1 out of 1 DEX servers
2020-05-21 10:39:52.513 [INF] CORE: notify: |SUCCESS| (conn) DEX connected - DEX at 127.0.0.1:7232 has connected
2020-05-21 10:39:58.325 [DBG] WEB: New websocket client 127.0.0.1
2020-05-21 10:40:06.252 [TRC] WEB: Disconnected websocket client 127.0.0.1
2020-05-21 10:40:06.691 [DBG] WEB: New websocket client 127.0.0.1
2020-05-21 10:40:34.190 [DBG] CORE: authenticated connection to 127.0.0.1:7232
2020-05-21 10:40:34.295 [TRC] WEB: message of type 1 received for route loadmarket
2020-05-21 10:40:36.001 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012606
2020-05-21 10:40:42.001 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012607
2020-05-21 10:40:46.512 [TRC] COMMS: got pinged, and ponged the server
2020-05-21 10:40:47.411 [TRC] WEB: Disconnected websocket client 127.0.0.1
2020-05-21 10:40:47.952 [DBG] WEB: New websocket client 127.0.0.1
2020-05-21 10:40:47.991 [TRC] WEB: message of type 1 received for route loadmarket
2020-05-21 10:40:48.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012608
2020-05-21 10:40:50.149 [TRC] WEB: message of type 1 received for route loadmarket
2020-05-21 10:40:54.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012609
2020-05-21 10:40:54.738 [TRC] WEB: message of type 1 received for route acknotes
2020-05-21 10:40:59.844 [TRC] WEB: message of type 1 received for route unmarket
2020-05-21 10:41:00.001 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012610
2020-05-21 10:41:01.822 [TRC] WEB: Disconnected websocket client 127.0.0.1
2020-05-21 10:41:02.230 [DBG] WEB: New websocket client 127.0.0.1
2020-05-21 10:41:05.566 [TRC] WEB: message of type 1 received for route loadmarket
2020-05-21 10:41:06.001 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012611
2020-05-21 10:41:10.806 [TRC] WEB: message of type 1 received for route unmarket
2020-05-21 10:41:12.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012612
2020-05-21 10:41:14.298 [INF] CORE: connecting wallet for btc
2020-05-21 10:41:14.410 [INF] CORE: Connected to and unlocked btc wallet. Account "gamma" balance available = 8399943200 / locked = 0, Deposit address = mgesXt3vQUohiuHGKkTRaNDeJM7B2fScih
2020-05-21 10:41:17.205 [INF] CORE: connecting wallet for dcr
2020-05-21 10:41:17.298 [INF] CORE: Connected to and unlocked dcr wallet. Account "default" balance available = 9633874674221 / locked = 0, Deposit address = SsfWraUBDUtU2dKAhBAYcb8HVTEupAnj9ta
2020-05-21 10:41:18.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012613
2020-05-21 10:41:18.457 [TRC] WEB: message of type 1 received for route loadmarket
2020-05-21 10:41:20.302 [TRC] CORE: processing tip change for btc
2020-05-21 10:41:24.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012614
2020-05-21 10:41:28.230 [TRC] CORE: processing tip change for dcr
2020-05-21 10:41:30.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012615
2020-05-21 10:41:36.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012616
2020-05-21 10:41:40.512 [TRC] COMMS: got pinged, and ponged the server
2020-05-21 10:41:42.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012617
2020-05-21 10:41:45.302 [TRC] CORE: processing tip change for btc
2020-05-21 10:41:48.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 265012618
2020-05-21 10:41:52.119 [ERR] COMMS: read error (websocket: close 1006 (abnormal closure): unexpected EOF), attempting reconnection
2020-05-21 10:41:52.119 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-05-21 10:41:52.119 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-05-21 10:41:52.119 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 5 seconds.
2020-05-21 10:41:52.120 [WRN] CORE: notify: |WARNING| (conn) DEX disconnected - DEX at 127.0.0.1:7232 has disconnected
2020-05-21 10:41:53.229 [TRC] CORE: processing tip change for dcr
2020-05-21 10:41:57.119 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-05-21 10:41:57.120 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-05-21 10:41:57.120 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 10 seconds.
2020-05-21 10:42:07.120 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-05-21 10:42:07.120 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-05-21 10:42:07.120 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 15 seconds.
2020-05-21 10:42:10.302 [TRC] CORE: processing tip change for btc
2020-05-21 10:42:19.230 [TRC] CORE: processing tip change for dcr
2020-05-21 10:42:22.120 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-05-21 10:42:22.142 [INF] COMMS: Successfully reconnected.
2020-05-21 10:42:22.142 [ERR] CORE: unable to authorize DEX at 127.0.0.1:7232: signing error: account locked
2020-05-21 10:42:22.142 [INF] CORE: notify: |SUCCESS| (conn) DEX connected - DEX at 127.0.0.1:7232 has connected
```
