### PR TITLE
webserver/site: fix handling of NoAuth wallets

### LINKED ISSUE #2328: zec: create wallet form looks like native-RPC hybrid
image

same after F5 on the wallets page

### PR DESCRIPTION
**Pull request by ukane-philemon**
Closes #2328.

Zec wallet does not require a password and uses the `NoAuth` boolean field in its wallet def. But we seem to add that as criteria to display the single `Create` btn that is used only by seeded/token wallets that do not have required config opts.

The `walletDef.noauth` field is already properly handled by the last else statement in the block of code near code change.

### CODE REVIEW

File: client/webserver/site/src/js/forms.ts [hunk 1]
```diff
@@ -326,7 +326,7 @@ export class NewWalletForm {
         break
       }
     }
-    const noWalletPWNeeded = walletDef.noauth || walletDef.seeded || Boolean(this.current.asset.token)
+    const noWalletPWNeeded = walletDef.seeded || Boolean(this.current.asset.token)
```
Comment (chappjc) [inline client/webserver/site/src/js/forms.ts:329]: I think the reason this was done wrong is because the variable `noWalletPWNeeded` was named incorrectly at conception.  It should really be `isCreated` afaict.

The other thing is that `page.auth` is badly named too.  It is a `div` that includes both the `newWalletPassBox` **and** the `submitAdd` button.

image

image

Almost every time I come to this code, I have to go figure out what `page.auth` is and why that should be shown when `noWalletPWNeeded` (because it actually still includes the Add/Create!) button.

So `page.auth` -> `page.walletPassAndSubmitBttn`?

Both suggested changes are code churn, but this code is hard to reason about presently.

**Review by chappjc — COMMENTED** [review]
Looks better. :+1: 

image

I just have a couple thoughts in the review about issues that led to this error.

File: client/webserver/site/src/js/forms.ts (hunk 1 above)
Comment (ukane-philemon) [reply client/webserver/site/src/js/forms.ts]: I renamed `noWalletPWNeeded` to `displayCreateBtn` cuz that's what it does basically. IMO `isCreated` raises more questions(what is created?).

**Review by chappjc — APPROVED** [review]
