### PR TITLE
eth: Wait for tx in tests.

### LINKED ISSUE #1687: eth/testing: TestContract tests fail on testnet.
Like the title says.

Three test logs for example:
[out2.txt](https://github.com/decred/dcrdex/files/8997864/out2.txt)
[out3.txt](https://github.com/decred/dcrdex/files/8997865/out3.txt)
[out4.txt](https://github.com/decred/dcrdex/files/8997867/out4.txt)

Some transactions are not mined at all. Others are mined but just not found. These do not fail on simnet.

### PR DESCRIPTION
**Pull request by JoeGruffins**
When running the simnet tests on testnet, we wait for all tx to be mined
    before proceeding. Sometimes, on testnet, this coincides with us looking
    at a to be orphaned block. When we try to find the transaction that was
    just mined, it may not be mined in our block. As a solution, wait a few
    blocks to find tx in tests. If we wait until we are back on the main
    chain, we will find it.

    While we are here, update the internal geth nodes to use geth v1.10.19.

closes #1687

### CODE REVIEW

**Comment by JoeGruffins** [comment]
I had originally thought that maybe there was a problem with light nodes being unable to find txn, but it seems as though that was a false alarm.

There is sort of a second part to that issue, but I have no idea what was wrong. My tx were just not being sent to the network it seems. Nothing was wrong with them. After deleting the node folders, it just started working as expected. Hoping it was a fluke... I have one theory that the node was blacklisted somewhere. But then it was still able to connect and get blocks? And one node was fine while the other wasn't, so I don't know if that makes sense.

**Comment by JoeGruffins** [comment]
I was so sure I did go mod tidy...

**Review by martonp — APPROVED** [review]
LGTM

File: client/asset/eth/nodeclient_harness_test.go [hunk 1]
```diff
@@ -143,6 +139,33 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
+	timesUp := time.After(time.Duration(5*secPerBlock) * time.Second)
+	for {
+		select {
+		case <-ctx.Done():
+			return nil, ctx.Err()
+		case <-time.After(time.Second):
+			receipt, err := nc.transactionReceipt(ctx, hash)
+			if err != nil {
+				if errors.Is(err, asset.CoinNotFoundError) {
+					fmt.Println("got um error", err.Error())
```
Comment (LasTshaMAN) [inline client/asset/eth/nodeclient_harness_test.go:156]: just wondering, what's `um error` ?

File: client/asset/eth/nodeclient_harness_test.go [hunk 2]
```diff
@@ -143,6 +139,33 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
 	}
 }
 
+// waitForReceipt waits for a tx. This is useful on testnet when a tx may be "missing"
+// due to reorg. Wait for a few blocks to find the main chain and hopefully our tx.
+func waitForReceipt(t *testing.T, nc *nodeClient, hash common.Hash) (*types.Receipt, error) {
+	t.Helper()
+	// Waiting as much as five blocks.
+	timesUp := time.After(time.Duration(5*secPerBlock) * time.Second)
```
Comment (LasTshaMAN) [inline client/asset/eth/nodeclient_harness_test.go:147]: looks like there is no need for type-casting here: I think `time.After(5*secPerBlock * time.Second)` should work just fine,

also, maybe converting `secPerBlock` type to `time.Duration` where variable is defined (making `secPerBlock = time.Second`) would be result into its usage being cleaner, otherwise multiple places require this `* time.Second` part:

image

File: client/asset/eth/nodeclient_harness_test.go [hunk 3]
```diff
@@ -143,6 +139,33 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
+				if errors.Is(err, asset.CoinNotFoundError) {
+					fmt.Println("got um error", err.Error())
+					continue
+				}
+				return nil, err
+			}
+			spew.Dump(receipt)
+			return receipt, nil
+		case <-timesUp:
+			return nil, errors.New("wait for receipt timed out")
```
Comment (LasTshaMAN) [inline client/asset/eth/nodeclient_harness_test.go:164]: Like you've mentioned [here](https://github.com/decred/dcrdex/issues/1687#issuecomment-1169693575), low gas price could indeed be the reason for txn not getting mined (or maybe even outright not accepted by other nodes),

maybe mention this in error message to remind checking that hypothesis (print out gas price value used, and suggest checking it against current rough value for gas price in blockchain explorer) when test fails ? also, might extend error message with something like `txn might be missing due to reorg`

File: client/asset/eth/nodeclient_harness_test.go (hunk 1 above)
Comment (JoeGruffins) [reply client/asset/eth/nodeclient_harness_test.go:156]: Lol. This wasn't meant to make it to the code. Will remove.

**Comment by JoeGruffins** [comment]
Just rebased.

File: client/asset/eth/nodeclient_harness_test.go (hunk 2 above)
Comment (JoeGruffins) [reply client/asset/eth/nodeclient_harness_test.go:147]: It seems I do need to cast: `./nodeclient_harness_test.go:147:24: invalid operation: 5 * secPerBlock * time.Second (mismatched types int and time.Duration)`

Maying `secPerBlock` a `time.Duration` is good tho.

File: client/asset/eth/nodeclient_harness_test.go [hunk 4]
```diff
@@ -143,69 +139,77 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
+				if len(txsa)+len(txsb) == 0 {
+					break out
+				}
 			}
 		}
+		if waitTimeLimit {
+			<-timesUp
+		}
+		// Sleeping just in case the node balance needs to catch up.
+		time.Sleep(time.Second)
```
Comment (JoeGruffins) [inline client/asset/eth/nodeclient_harness_test.go:210]: Had a failure for the balance on testInitiate which makes me a little nervous. That was before this sleep. Not sure if there's another reason. Leaving the logs here.

Failed balance check:
[out.txt](https://github.com/decred/dcrdex/files/9038460/out.txt)

**Comment by JoeGruffins** [comment]
Removed some silly complexity https://github.com/decred/dcrdex/compare/d7414af334ce0e009e22bcd64144734586eb6c32..d0f8952114d3dafa3918dd3b014b18d3b56c357d

**Comment by JoeGruffins** [comment]
Actually, still seeing the balance issue. Looking into it. Maybe I just failed changing the sleep durations.

**Comment by JoeGruffins** [comment]
Just needed to make sure both clients are checked when mining to flush the pending transactions.

**Comment by JoeGruffins** [comment]
Had a new failure as well. Don't think it's related to these changes.
```
INFO [07-05|12:57:00.003] Imported new block headers               count=1   elapsed="302.748µs" number=7,171,701 hash=30f9ee..d47d71
INFO [07-05|12:57:12.182] Imported new block headers               count=2   elapsed="589.726µs" number=7,171,702 hash=2073e1..115585 ignored=1
INFO [07-05|12:57:12.396] Imported new block headers               count=1   elapsed="387.777µs" number=7,171,702 hash=52145c..7358f9
INFO [07-05|12:57:27.061] Imported new block headers               count=1   elapsed="440.306µs" number=7,171,703 hash=29b139..fe3715 ignored=2
WARN [07-05|12:57:27.276] Invalid header encountered               number=7,171,703 hash=29b139..fe3715 parent=2073e1..115585 err="unknown ancestor"
WARN [07-05|12:57:27.276] Synchronisation failed, dropping peer    peer=888da46ca44980cf672a444e2deff7c5e9a97af28f4edded586b58176d6bb4da err="retrieved hash chain is invalid: unknown ancestor"
    nodeclient_harness_test.go:1065: 1 swap with existing hash: post-initiate mining error: timed out
=== RUN   TestContract/testRedeem
WARN [07-05|12:58:05.811] Served eth_call                          reqid=19 duration=18.004139511s err="getDeleteStateObject (54cc38fc37d12558554d669e508aaab1ab25375c) error: no suitable peers available"
    nodeclient_harness_test.go:1365: unable to get swap state
=== RUN   TestContract/testRefund
INFO [07-05|12:58:09.171] Imported new block headers               count=4   elapsed="938.73µs"  number=7,171,705 hash=d4b851..50e16e
INFO [07-05|12:58:10.258] Imported new block headers               count=1   elapsed="144.992µs" number=7,171,706 hash=48b78c..b747b9
WARN [07-05|12:58:23.815] Served eth_call                          reqid=20 duration=18.004669644s err="getDeleteStateObject (54cc38fc37d12558554d669e508aaab1ab25375c) error: no suitable peers available"
    nodeclient_harness_test.go:1671: ok: unable to get swap state pre-init
--- FAIL: TestContract (247.30s)
    --- PASS: TestContract/testAddressesHaveFunds (0.58s)
    --- PASS: TestContract/testSwap (1.42s)
    --- FAIL: TestContract/testInitiate (209.29s)
    --- FAIL: TestContract/testRedeem (18.00s)
    --- FAIL: TestContract/testRefund (18.00s)
FAIL
```

File: client/asset/eth/nodeclient_harness_test.go [hunk 5]
```diff
@@ -143,65 +137,69 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
+				if errors.Is(err, asset.CoinNotFoundError) {
+					continue
+				}
+				return nil, err
 			}
+			spew.Dump(receipt)
+			return receipt, nil
+		case <-timesUp:
+			return nil, errors.New("wait for receipt timed out, txn might be missing due to reorg, check the following tx for a bad nonce or low gas cap")
+			spew.Dump(tx)
```
Comment (chappjc) [inline client/asset/eth/nodeclient_harness_test.go:163]: Unreachable.  Leftover debugging or you wanted this before the `return`?

File: client/asset/eth/nodeclient_harness_test.go [hunk 6]
```diff
@@ -143,65 +137,69 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
-				break out
+				if errors.Is(err, asset.CoinNotFoundError) {
+					continue
+				}
+				return nil, err
 			}
+			spew.Dump(receipt)
+			return receipt, nil
+		case <-timesUp:
+			return nil, errors.New("wait for receipt timed out, txn might be missing due to reorg, check the following tx for a bad nonce or low gas cap")
```
Comment (chappjc) [inline client/asset/eth/nodeclient_harness_test.go:162]: 155 columns is a bit much.  Maybe wrap after the second comma to keep most of the text uninterrupted.

File: go.mod [hunk 7]
```diff
@@ -38,7 +38,7 @@ require (
 	github.com/decred/dcrd/wire v1.5.0
 	github.com/decred/go-socks v1.1.0
 	github.com/decred/slog v1.2.0
-	github.com/ethereum/go-ethereum v1.10.17
+	github.com/ethereum/go-ethereum v1.10.19
```
Comment (chappjc) [inline go.mod:41]: Might as well get on https://github.com/ethereum/go-ethereum/releases/tag/v1.10.20 now

**Review by chappjc — APPROVED** [review]
LGTM, just a few minor things.

**Comment by JoeGruffins** [comment]
Just rebased.

File: client/asset/eth/nodeclient_harness_test.go [hunk 8]
```diff
@@ -143,65 +137,69 @@ func newRedeem(secret, secretHash [32]byte) *asset.Redemption {
...
 	}
-	if waitTimeLimit {
-		<-timesUp
-	}
-	return nil
 }
 
-// waitForMinedTestnet will multiply the time limit by testnetSecPerBlock.
-func waitForMinedTestnet(t *testing.T, nc *nodeClient, timeLimit time.Duration, waitTimeLimit bool) error {
+// waitForMinedFn will multiply the time limit by testnetSecPerBlock for
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/eth/nodeclient_harness_test.go:168]: Removed the `Fn`

File: client/asset/eth/nodeclient_harness_test.go (hunk 5 above)
Comment (JoeGruffins) [reply client/asset/eth/nodeclient_harness_test.go:163]: Doh. Yes. Moved.

File: client/asset/eth/nodeclient_harness_test.go (hunk 6 above)
Comment (JoeGruffins) [reply client/asset/eth/nodeclient_harness_test.go:162]: Wrapped after the second comma.

File: go.mod (hunk 7 above)
Comment (JoeGruffins) [reply go.mod]: Updated.

**Comment by JoeGruffins** [comment]
@chappjc review changes https://github.com/decred/dcrdex/compare/e1eca0132d1eadd2b447e9ea83ef3809d6807656..ea8f1f802b95ab3263deb492237277cc99f93f4a
