### PR TITLE
Show exchange disconnected if connection fails

### LINKED ISSUE #943: ui: down DEX server leads to register dialog sequence
If you have dexc configured with a registered DEX account at some server, that is the only configured DEX account, and then startup cannot connect for any reason, the UI enters into the add-a-dex path.

image

image

But really it's because the already-configured dex couldn't connect. e.g.:

```
[ERR] CORE: error connecting to DEX 127.0.0.1:17273: dial tcp 127.0.0.1:17273: connect: connection refused
[INF] CORE: Successfully connected to 0 out of 1 DEX servers
```

Preferably the UI should say there was a connection failure and not prompt you to re-register (which wouldn't work even if you wanted to pay again because the DEX is actually unreachable in this situation).

### PR DESCRIPTION
**Pull request by vctt94**
closes #943

Right now I am appending the exchange host on `Core.conns[host]` in case of connection failure, instead of only appending it on succcess. This way it is possible to give a feedback in the client that the exchange is not connected.

~~Right now it stills a work in progress, because there is a loader which I am not being able to remove.~~

This is how it looks if a dex server connection fails:

image

### CODE REVIEW

File: client/core/core.go [hunk 1]
```diff
@@ -120,6 +120,9 @@ func (dc *dexConnection) marketConfig(mktID string) *msgjson.Market {
 // marketMap creates a map of this DEX's *Market keyed by name/ID,
 // [base]_[quote].
 func (dc *dexConnection) marketMap() map[string]*Market {
+	if !dc.connected {
```
Comment (chappjc) [inline client/core/core.go:123]: On master `connected` is a uint32 atomic, so you'll have to do similarly to other places like `atomic.LoadUint32(&dc.connected) == 1`

Comment (vctt94) [reply client/core/core.go]: Thanks for the review. Now the CI passes!

File: client/core/core.go [hunk 2]
```diff
@@ -121,6 +121,9 @@ func (dc *dexConnection) marketConfig(mktID string) *msgjson.Market {
 // marketMap creates a map of this DEX's *Market keyed by name/ID,
 // [base]_[quote].
 func (dc *dexConnection) marketMap() map[string]*Market {
+	if atomic.LoadUint32(&dc.connected) == 0 {
+		return nil
```
Comment (chappjc) [inline client/core/core.go:125]: What's the motivation for this change?  Was there an existing bug?  It's not clear to me this is going to be a benign change in all cases.

Comment (vctt94) [reply client/core/core.go:125]: Right now when calling the `User` method on core, it calls the method  `exchangeMap`, which calls the method `marketMap` from the connection. 

As I am returning the connection now, when it fails to connect, I need this check, otherwise, `dc.cfg` will be nil, and break things.

Comment (JoeGruffins) [reply client/core/core.go:125]: If what you are really after is `dc.cfg` being nil or not, I would prefer checking that.

File: client/core/core.go [hunk 3]
```diff
@@ -1069,9 +1072,12 @@ func (c *Core) dexConnections() []*dexConnection {
...
 	for _, dc := range c.dexConnections() {
-		dc.cfgMtx.RLock()
-		requiredConfs := uint32(dc.cfg.RegFeeConfirms)
-		dc.cfgMtx.RUnlock()
+		var requiredConfs uint32
+		if atomic.LoadUint32(&dc.connected) == 1 {
+			dc.cfgMtx.RLock()
+			requiredConfs = uint32(dc.cfg.RegFeeConfirms)
+			dc.cfgMtx.RUnlock()
+		}
```
Comment (JoeGruffins) [inline client/core/core.go:1080]: Here too could check that "dc.cfg" is not nil.

**Review by JoeGruffins — COMMENTED** [review]
This looks to solve the issue to me. Maybe a little more info for the user would be useful? What should they do? I guess that host is now fubar for the life of this dexc? They should close the app and try again later?

**Comment by vctt94** [comment]
Thanks for the review @JoeGruffins . I agree with you, and I think it is a good idea to have more information. The problem is this is a server problem, so there is not how to be sure how long will it take.

Maybe add a message for retry later? What do you guys think

File: client/core/core.go [hunk 4]
```diff
@@ -121,6 +121,9 @@ func (dc *dexConnection) marketConfig(mktID string) *msgjson.Market {
 // marketMap creates a map of this DEX's *Market keyed by name/ID,
 // [base]_[quote].
 func (dc *dexConnection) marketMap() map[string]*Market {
+	if dc.cfg == nil {
+		return nil
+	}
 	dc.cfgMtx.RLock()
 	mktConfigs := dc.cfg.Markets
 	dc.cfgMtx.RUnlock()
```
Comment (buck54321) [inline client/core/core.go:129]: The `cfgMtx` protects the `dc.cfg` field. What you want here is something like

```
dc.cfgMtx.RLock()
cfg := dc.cfg
dc.cfgMtx.RUnlock()
if cfg = nil { ... }
mktConfigs := cfg.Markets
```

Comment (buck54321) [inline client/core/core.go:129]: The `cfgMtx` protects the `dc.cfg` field. What you want here is something like

```
dc.cfgMtx.RLock()
cfg := dc.cfg
dc.cfgMtx.RUnlock()
if cfg = nil { ... }
mktConfigs := cfg.Markets
```

File: client/core/core.go [hunk 5]
```diff
@@ -1069,9 +1072,12 @@ func (c *Core) dexConnections() []*dexConnection {
...
 	for _, dc := range c.dexConnections() {
-		dc.cfgMtx.RLock()
-		requiredConfs := uint32(dc.cfg.RegFeeConfirms)
-		dc.cfgMtx.RUnlock()
+		var requiredConfs uint32
+		if dc.cfg != nil {
+			dc.cfgMtx.RLock()
+			requiredConfs = uint32(dc.cfg.RegFeeConfirms)
+			dc.cfgMtx.RUnlock()
+		}
```
Comment (buck54321) [inline client/core/core.go:1080]: Here again, can't check `if dc.cfg != nil` without the `cfgMtx` locked. The `cfgMtx` doesn't protect the fields of the stored `*msgjson.ConfigResult`, it protects the `dexConnection.cfg` field itself.

File: client/core/core.go [hunk 6]
```diff
@@ -3405,6 +3411,11 @@ func (c *Core) verifyAccount(acct *db.AccountInfo) bool {
 	dc, err := c.connectDEX(acct)
 	if err != nil {
 		c.log.Errorf("error connecting to DEX %s: %v", acct.Host, err)
+		// update failed connection, so we can give feedback.
+		c.connMtx.Lock()
+		c.conns[host] = dc
+		c.connMtx.Unlock()
+		c.log.Debugf("dex connection to %s ready", acct.Host)
```
Comment (buck54321) [inline client/core/core.go:3418]: message seems misleading

File: client/core/core.go [hunk 7]
```diff
@@ -3405,6 +3411,11 @@ func (c *Core) verifyAccount(acct *db.AccountInfo) bool {
 	dc, err := c.connectDEX(acct)
 	if err != nil {
 		c.log.Errorf("error connecting to DEX %s: %v", acct.Host, err)
+		// update failed connection, so we can give feedback.
+		c.connMtx.Lock()
+		c.conns[host] = dc
+		c.connMtx.Unlock()
```
Comment (buck54321) [inline client/core/core.go:3417]: In the case of an error, `dc` will be `nil`. Might as well just `c.conns[host] = nil` here so there's no question. Though if we're going to use a nil-valued entry like this, the intention needs to be very clearly documented somewhere.

File: client/core/core.go [hunk 8]
```diff
@@ -4058,8 +4069,18 @@ func (c *Core) connectDEX(acctInfo *db.AccountInfo) (*dexConnection, error) {
...
+		dc := &dexConnection{
+			WsConn:     conn,
+			log:        c.log,
+			connMaster: connMaster,
+			books:      make(map[string]*bookie),
+			acct:       newDEXAccount(acctInfo),
+			trades:     make(map[order.OrderID]*trackedTrade),
+			notify:     c.notify,
+			connected:  0,
+		}
```
Comment (buck54321) [inline client/core/core.go:4081]: Rather than repeat this, might as well do this once up above, and just assign to the other fields directly in the non-error case.

File: client/webserver/site/src/html/markets.tmpl [hunk 9]
```diff
@@ -42,6 +42,7 @@
     {{- /* CHART */ -}}
 
     <div id="marketChart" class="w-100">
+      <div id="errMsg" class="fs15 pt-3 text-center d-hide errcolor"></div>
```
Comment (buck54321) [inline client/webserver/site/src/html/markets.tmpl:45]:
```suggestion
      <div id="chartErrMsg" class="fs15 pt-3 text-center d-hide errcolor"></div>
```

File: client/webserver/site/src/js/app.js [hunk 10]
```diff
@@ -498,8 +498,8 @@ export default class Application {
       case 'walletstate':
       case 'walletconfig': {
         const wallet = note.wallet
-        this.assets[wallet.assetID].wallet = wallet
-        this.walletMap[wallet.assetID] = wallet
+        if (this.assets !== undefined) this.assets[wallet.assetID].wallet = wallet
+        if (this.walletMap !== undefined) this.walletMap[wallet.assetID] = wallet
```
Comment (buck54321) [inline client/webserver/site/src/js/app.js:502]: Not sure about this. What are you fixing?

File: client/webserver/site/src/js/markets.js [hunk 11]
```diff
@@ -476,6 +478,12 @@ export default class MarketsPage extends BasePage {
     const { confs, confsrequired } = dex
     const feePending = this.hasFeePending()
 
+    // if dex is not connected to server, is not possible to know fee
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:481]:
```suggestion
    // If dex is not connected to server, is not possible to know fee
```

Comment (buck54321) [inline client/webserver/site/src/js/markets.js:481]:
```suggestion
    // If dex is not connected to server, is not possible to know fee
```

File: client/webserver/site/src/js/markets.js [hunk 12]
```diff
@@ -476,6 +478,12 @@ export default class MarketsPage extends BasePage {
...
+    // registration status.
+    if (!dex.connected) {
+      return
+    }
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:485]:
```suggestion
    if (!dex.connected) return
```

File: client/webserver/site/src/js/markets.js [hunk 13]
```diff
@@ -504,6 +512,19 @@ export default class MarketsPage extends BasePage {
   /* setMarket sets the currently displayed market. */
   async setMarket (host, base, quote) {
     const dex = app.user.exchanges[host]
+    if (!dex.connected) {
+      this.market = {
+        dex: dex
+      }
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:518]:
```suggestion
      this.market = { dex: dex }
```

File: client/webserver/site/src/js/markets.js [hunk 14]
```diff
@@ -1612,6 +1633,10 @@ class MarketList {
   first () {
     const firstXC = this.sortedSections()[0]
     const firstMkt = firstXC.first()
+    // can not find markets if server connection failed.
+    if (!firstMkt) {
+      return makeMarket(firstXC.host)
+    }
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:1639]:
```suggestion
    if (!firstMkt)  return makeMarket(firstXC.host)
```

File: client/webserver/site/src/js/markets.js [hunk 15]
```diff
@@ -1612,6 +1633,10 @@ class MarketList {
   first () {
     const firstXC = this.sortedSections()[0]
     const firstMkt = firstXC.first()
+    // can not find markets if server connection failed.
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:1636]:
```suggestion
    // Cannot find markets if server connection failed.
```

File: client/webserver/site/src/js/markets.js [hunk 16]
```diff
@@ -1657,12 +1682,14 @@ class ExchangeSection {
     this.rows = Doc.tmplElement(box, 'mkts')
     const rowTmpl = Doc.tmplElement(this.rows, 'mktrow')
     this.rows.removeChild(rowTmpl)
-    for (const mkt of Object.values(dex.markets)) {
-      this.marketRows.push(new MarketRow(rowTmpl, mkt))
-    }
-
-    for (const market of this.sortedMarkets()) {
-      this.rows.appendChild(market.row)
+    // if disconnected is not possible to get the markets from the server.
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:1685]:
```suggestion
    // If disconnected is not possible to get the markets from the server.
```

File: client/webserver/site/src/js/markets.js [hunk 17]
```diff
@@ -1657,12 +1682,14 @@ class ExchangeSection {
...
+    if (dex.markets) {
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:1686]: Prefer less indentation, so

```suggestion
    if (!dex.markets) return
```

**Review by buck54321 — CHANGES_REQUESTED** [review]

File: client/core/core.go (hunk 7 above)
Comment (vctt94) [reply client/core/core.go:3417]: dc will not be nil in this case, because now I am returning dc's value if it is disconnect, as well: https://github.com/decred/dcrdex/pull/989/files#diff-13a4a6b12c1ae844ef90151638f194427cfdc545fceb58d52c0f6f33b81d859bR4072

Comment (buck54321) [reply client/core/core.go:3417]: My bad. I meant to delete this comment before submitting my review.

Comment (buck54321) [reply client/core/core.go:3417]: My bad. I meant to delete this comment before submitting my review.

**Comment by vctt94** [comment]
Thanks for your reveiw buck. Updated your comments

File: client/webserver/site/src/js/app.js (hunk 10 above)
Comment (vctt94) [reply client/webserver/site/src/js/app.js]: You are right. Removed it

**Review by JoeGruffins — COMMENTED** [review]
It will show the message `Connection to dex server failed. You can close dexc and try again later.` even if this was a previously established connection that will reconnect automatically at some time.

imo it would be best if the connection were started in the reconnect mode, although still lacking a lot of initiation, that could be done whenever the connection does come up. There may be something making that more difficult than it sounds though, I am not sure.

I would think you could add a field to the dexConnection, a bool like `initiated` and pull out the last part of `connectDEX` into a separate function. If connect gets to the end successfully, `initiated` is true, if not keep trying to reconnect. reconnect has a switch for if `initiated` and if not go through the init procedure, which is the bottom half of `connectDEX`. However, if the init part fails still need to make this host fubar and stop trying to connect.

**Comment by vctt94** [comment]
I am not sure how to reproduce this @JoeGruffins, can you say the steps?

If connected, and stopping the server, for example, it just shows as disconnected

**Comment by chappjc** [comment]
@vctt94 I'm building on your branch presently w.r.t. the start in reconnect mode and some other tasks.  https://github.com/decred/dcrdex/commit/bec320c4
I'll have a number of other suggested changes for your branch shortly.

**Comment by chappjc** [comment]
2 commits building on your branch: https://github.com/chappjc/dcrdex/commits/wsconn-reconnect-loop-start-err
In addition to the `client/comms` change, there were some other gotchas like the `(*Core).listen(*dexConnection)` goroutine needing to be running for which such a connection eventually does connect.  It's a bunch of tangential work though so I suggest we merge your PR and I follow up with these changes.

But about your changes, the browser console is very fussy about `markets` being `null` and `assets` being `{}`.  I know without a connection we just don't have this info, but perhaps some if checks in the js to prevent all the errors.

File: client/core/core.go [hunk 18]
```diff
@@ -59,16 +56,17 @@ var (
 	// When waiting for a wallet to sync, a SyncStatus check will be performed
 	// ever syncTickerPeriod. var instead of const for testing purposes.
 	syncTickerPeriod = 10 * time.Second
+	// tickInterval is how often to check trades.
+	tickInterval = 60 * time.Second
```
Comment (chappjc) [inline client/core/core.go:61]: @buck54321 @itswisdomagain Reason for this is because tickInterval had an arbitrary formula based on the connected market's broadcast timeout.  Needing to have the `listen` goroutine, which also does the ticks, running from the start and thus before broadcast timeout is known made a problem.  The whole `tickCheckDivisions` thing was a bit questionable anyway.  I don't think I ever had a solid justification for a variable tick interval for markets with longer broadcast timeouts.

File: client/core/core.go [hunk 19]
```diff
@@ -4208,22 +4206,18 @@ func (c *Core) handleReconnect(host string) {
...
-	c.connMtx.Lock()
-	if dc, found := c.conns[host]; found {
-		var v uint32
-		if connected {
-			v = 1
-		}
-		atomic.StoreUint32(&dc.connected, v)
+func (dc *dexConnection) handleConnectEvent(connected bool) {
+	var v uint32
+	if connected {
```
Comment (chappjc) [inline client/core/core.go:4212]: Just realized the two `if` statements can be merged.

**Comment by chappjc** [comment]
Do you see any way to make this cleaner or hidden when in the disconnected state:

image

That is, when the depth chart is showing "Connection to dex server failed. You can close dexc and try again later."

Other comment is that that message now could be amended to say "You can close dexc and try again later **or wait for it to reconnect.**"  Although the `NoteTypeConnEvent` that comes when it does reconnect does not reload the page since usually a page reload isn't needed.  Not sure how frontend can change to deal with that.

File: client/webserver/site/src/js/app.js [hunk 20]
```diff
@@ -462,6 +462,7 @@ export default class Application {
   notify (note) {
     // Handle type-specific updates.
     this.log('notes', 'notify', note)
+    console.log(note)
```
Comment (chappjc) [inline client/webserver/site/src/js/app.js:465]: leftovers

File: client/webserver/site/src/js/markets.js [hunk 21]
```diff
@@ -1243,11 +1246,20 @@ export default class MarketsPage extends BasePage {
     }
   }
 
+  setBalanceVisibility () {
+    if (this.market.dex.connected) {
+      Doc.show(this.page.marketBalance)
+    } else {
+      Doc.hide(this.page.marketBalance)
+    }
+  }
```
Comment (chappjc) [inline client/webserver/site/src/js/markets.js:1255]: This seems alright to me but in other places we show/hide the whole order form that includes the balance table (`Doc.{show,hide}(page.orderForm)`), such as when the account is not yet paid.  That actually happens in `setRegistrationStatusVisibility`, which is called right above the `setRegistrationStatusVisibility` call you added. @fernandoabolafio or buck could advise of that's more appropriate or not.

Comment (vctt94) [reply client/webserver/site/src/js/markets.js]: I am also hiding the form now. 

I will wait to see if it is ok to check if to handleBalanceNote or setting connection status.

I am fine either way

**Review by JoeGruffins — APPROVED** [review]
Works great.

File: client/core/core.go [hunk 22]
```diff
@@ -3395,33 +3410,40 @@ func (c *Core) initialize() {
...
-		return false
+		c.log.Errorf("skipping loading of %s due to address parse error: %v", host, err)
+		return
 	}
-	dc, err := c.connectDEX(acct)
-	if err != nil {
-		c.log.Errorf("error connecting to DEX %s: %v", acct.Host, err)
-		return false
+	dc, err = c.connectDEX(acct)
+	if dc == nil {
```
Comment (chappjc) [inline client/core/core.go:3432]: @buck54321 had a good point in another thread about using dc.acct.host instead of doing the superfluous `addrHost` call a few lines up since `connectDEX` does it too.

**Review by chappjc — CHANGES_REQUESTED** [review]
One more minor request from me, and please follow up on any outstanding requests from Joe and myself.  I see two small ones.

File: client/core/core.go (hunk 18 above)
Comment (buck54321) [reply client/core/core.go:61]: It wasn't arbitrary. The broadcast timeout is an upper limit on what our tick interval should be. Basing the tick interval on the broadcast timeout is a reasonable approach. But using a 60s constant **is** arbitrary. What if the broadcast timeout is 30s and we never even get a second `tick`? Clearly, the operator that set the timeout is an ass, but that's not really the point.

File: client/core/core.go (hunk 22 above)
Comment (vctt94) [reply client/core/core.go:3432]: aparently the rebase changed it

File: client/core/core.go (hunk 18 above)
Comment (chappjc) [reply client/core/core.go:61]: I mean the number of ticks per timeout was arbitrary, and the fact that tick rate was variable was awkward imo.
A broadcast timeout on the order of seconds is crazy as you've pointed out.
Alternatives to this?  I don't have a solution.

Comment (chappjc) [reply client/core/core.go:61]: Ya know, the `(*Ticker).Reset(time.Duration)` method that was added in 1.15 is now fair game for us.... let me see about that.  There are still likely some challenges though as the ticker's going to have to be in a `dexConnection` field to be able to reset it from the reconnect handler.

File: client/webserver/site/src/js/app.js [hunk 23]
```diff
@@ -496,6 +496,8 @@ export default class Application {
         break
       case 'walletstate':
       case 'walletconfig': {
+        // assets can be null if failed to connect to dex server.
+        if (!this.assets) return
```
Comment (buck54321) [inline client/webserver/site/src/js/app.js:500]: The `Assets` field of the `User` object should be populated regardless of any particular dex connection status. Are you sure this comment is true?

File: client/webserver/site/src/js/app.js [hunk 24]
```diff
@@ -508,6 +510,9 @@ export default class Application {
         if (ord) updateMatch(ord, note.match)
         break
       }
+      case 'conn': {
+        this.reconnected()
+      }
```
Comment (buck54321) [inline client/webserver/site/src/js/app.js:515]: No need for braces is you're not creating variables. 

```
case 'conn':
  this.reconnected()
```

File: client/webserver/site/src/js/markets.js [hunk 25]
```diff
@@ -66,7 +68,9 @@ export default class MarketsPage extends BasePage {
       // Max order section
       'maxOrd', 'maxLbl', 'maxFromLots', 'maxFromAmt', 'maxFromTicker',
       'maxToAmt', 'maxToTicker', 'maxAboveZero', 'maxLotBox', 'maxFromLotsLbl',
-      'maxBox'
+      'maxBox',
+      // errors
+      'chartErrMsg'
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:73]: Please put this in the `// Chart and legend` section.

File: client/webserver/site/src/js/markets.js [hunk 26]
```diff
@@ -47,6 +47,8 @@ export default class MarketsPage extends BasePage {
       'baseWalletIcons', 'quoteWalletIcons', 'lotSize', 'rateStep', 'lotField',
       'tifNow', 'mktBuyBox', 'mktBuyLots', 'mktBuyField', 'minMktBuy', 'qtyBox',
       'loaderMsg', 'balanceTable', 'orderPreview',
+      // Balance
+      'marketBalance',
```
Comment (buck54321) [inline client/webserver/site/src/js/markets.js:51]: No new section here. It's the same section as the `balanceTable`, which is the section labeled `// Order form`.

**Review by buck54321 — APPROVED** [review]
Just couple nits.

File: client/core/core.go (hunk 18 above)
Comment (buck54321) [reply client/core/core.go:61]: Oh, nice. I didn't even know about `(*Ticker).Reset`.

File: client/webserver/site/src/js/app.js (hunk 23 above)
Comment (vctt94) [reply client/webserver/site/src/js/app.js:500]: If the server is off, it is not possible to know which assets they have, or is it?

Comment (buck54321) [reply client/webserver/site/src/js/app.js:500]: `this.assets` is just `this.user.assets`, which comes from the Go `core.User` type. The `Assets` field is a `map[uint32]*SupportedAsset`, which are assets that the client supports, not `dex.Asset`, which would be associated with a DEX. The big clue is that it is a field of `User`, not of `Exchange`. Look at `(*Core).assetMap` to see how the `User.Assets` map is made.

**Comment by chappjc** [comment]
Generally working quite well.  The one thing left for a follow-up PR that I'm preparing already is to allow a logged in dexc to start working immediately and without restart.  Right now it can't load orders into trackedTrades in the following case: dexc user has active orders, dcrdex server is down, dexc shuts down, dexc starts back up, dexc user does login (unlocking wallet and account keys), dcrdex server comes back online.  In this case it does reconnect as expected, but the trackedTrades are not loaded fully and because information from the server was required to load them, so dexc logs unknown orders reported by the server on auth.  A dexc restart resolves it, but this is next work for me.

Note that the solution to the above is tantamount to solving https://github.com/decred/dcrdex/issues/952.  I'm getting pretty close but it's not terribly pretty yet.
