### PR TITLE
app: Fix bond waiting UI

### LINKED ISSUE #2978: ui: waiting for bonds displays not updating correctly
After the bond is created and we start waiting for confirmations, the "Creating Bonds..." section should be hidden.
image

### PR DESCRIPTION
**Pull request by martonp**
Only show one section at a time in the bond waiting UI on the markets page.

Closes #2978

### CODE REVIEW

File: client/webserver/site/src/js/markets.ts [hunk 1]
```diff
@@ -955,9 +955,16 @@ export default class MarketsPage extends BasePage {
...
+      const elements = [page.registrationStatus, page.bondRequired, page.bondCreationPending, page.notRegistered]
+      for (const el of elements) {
+        Doc.setVis(el === section, el)
+      }
+    }
+
     if (market.dex.auth.effectiveTier >= 1) {
       const toggle = async () => {
-        Doc.hide(page.registrationStatus, page.bondRequired, page.bondCreationPending)
+        showSection(undefined)
```
Comment (ukane-philemon) [inline client/webserver/site/src/js/markets.ts:967]: I finished bond posting and the order form has been displayed but "Fidelity bond accepted!" remained on the order form until I refreshed,

**Review by ukane-philemon — CHANGES_REQUESTED** [review]

**Review by JoeGruffins — APPROVED** [review]

File: client/webserver/site/src/js/markets.ts (hunk 1 above)
Comment (martonp) [reply client/webserver/site/src/js/markets.ts:967]: That's what this line is supposed to do.. and the "Fidelity bond accepted" disappears for me. Maybe you didn't build the latest UI?
