### PR TITLE
asset: create btcwallet+neutrino log dir and file without initialization

### LINKED ISSUE #1944: wallets/internal: Cannot view logs after recover.
If you click `wallet logs` after doing `recover` you are given an internal server error:

image

To reproduce, go on simnet and change btc to SPV. Recover then click wallet logs.

### PR DESCRIPTION
**Pull request by ukane-philemon**
This fixes an issue where wallet recovery deletes the existing neutrino log file but logging initialization is a one-time operation. Closes #1944.

### CODE REVIEW

File: client/asset/dcr/spv.go [hunk 1]
```diff
@@ -138,9 +138,10 @@ var _ tipNotifier = (*spvWallet)(nil)
 
 func createSPVWallet(pw, seed []byte, dataDir string, extIdx, intIdx uint32, chainParams *chaincfg.Params) error {
 	dir := filepath.Join(dataDir, chainParams.Name, "spv")
-
-	if err := initLogging(dir); err != nil {
-		return fmt.Errorf("error initializing dcrwallet logging: %w", err)
+	// Create log path and file.
+	_, err := logRotator(dir)
```
[the remark this answers is not in the document]
Comment (ukane-philemon) [reply client/asset/dcr/spv.go:142]: > It also creates a log rotator but doesn't use it.

Yeah, I'm letting the log rotator create the log file with its file permission...

[the remark this answers is not in the document]
Comment (chappjc) [reply client/asset/dcr/spv.go:142]: We can't just do `rotator.New` and throw away the `*rotator.Rotator`.  It opens the file for writing, and there's an active file descriptor.

[the remark this answers is not in the document]
Comment (ukane-philemon) [reply client/asset/dcr/spv.go:142]: oops, missed closing the rotator.

[the remark this answers is not in the document]
Comment (ukane-philemon) [reply client/asset/dcr/spv.go:142]: oops, missed closing the rotator.

File: client/asset/bch/spv.go [hunk 2]
```diff
@@ -477,6 +476,8 @@ func (w *bchSPVWallet) Stop() {
 	}
 
 	w.log.Info("SPV wallet closed")
+	// Allow the logger to be re-initiated when the wallet reconnects.
+	atomic.CompareAndSwapUint32(&loggingInited, 1, 0)
```
Comment (JoeGruffins) [inline client/asset/bch/spv.go:480]: nit: Can just do [StoreUint32(addr *uint32, val uint32)](https://pkg.go.dev/sync/atomic#StoreUint32) since you are not using the return.

**Review by JoeGruffins — APPROVED** [review]
Looks fixed to me.

File: client/asset/bch/spv.go (hunk 2 above)
Comment (chappjc) [reply client/asset/bch/spv.go:480]: Same thought.  Not using the return has the smell of a bug

**Comment by buck54321** [comment]
Looks like the `spvWallet.dir` is
```Go
dir: filepath.Join(cfg.WalletCFG.DataDir, cfg.ChainParams.Name, "spv"),
```
and the log file is created in a subdirectory of that directory. 

If we instead created the log files in, say, 
```Go
filepath.Join(cfg.WalletCFG.DataDir, cfg.ChainParams.Name, "spvlogs")
```
this wouldn't be an issue.

**Comment by ukane-philemon** [comment]
> If we instead created the log files in, say,
filepath.Join(cfg.WalletCFG.DataDir, cfg.ChainParams.Name, "spvlogs")
this wouldn't be an issue.

I think the issue is that only the log dir is created while the `neutrino.log` file is not, causing an error when trying to retrieve the log file. This PR allows `rotator.New(...)` to create the  `neutrino.log`  file when the wallet is created so that calls to download wallet logs will find the `neutrino.log` file.

**Comment by buck54321** [comment]
My read might be wrong, but it seems to me that the problem is that `(*spvWallet).moveWalletData` is moving log files in the first place.

**Comment by ukane-philemon** [comment]
> My read might be wrong, but it seems to me that the problem is that `(*spvWallet).moveWalletData` is moving log files in the first place.

What is the expected behaviour for new wallets(the create wallet method does not know it's a recovery)? And does it mean the wallet log should be untouched in any scenario?

**Comment by buck54321** [comment]
I don't see a reason to start new log files when we perform recovery. We'll want the record to be continuous, no?

**Comment by ukane-philemon** [comment]
> I don't see a reason to start new log files when we perform recovery. We'll want the record to be continuous, no?

Hmm, maybe not, because we ought to keep all details regarding the old wallet including the logs on the `assetdb-backup` directory. So the new wallet will have to start clean?

**Comment by chappjc** [comment]
I think Buck is saying we should just not delete the logs.  We can still copy them.

Also with the current PR, dcrwallet loggers keep using the old log rotator.  I don't see how it's working.

**Comment by ukane-philemon** [comment]
> I think Buck is saying we should just not delete the logs. We can still copy them.

Okay, I had assumed the expected behaviour for recovery is to remove everything related to the previous wallet(including logs) from the main wallet dir. However, @buck54321 suggestion will keep changes minimal, I think.

**Comment by ukane-philemon** [comment]
@buck54321, RE: https://github.com/decred/dcrdex/pull/1946#issuecomment-1309975817, I had to move some things around in https://github.com/decred/dcrdex/commit/1e56f6dbde69ab75b08234fe9db2d84e14f36aea

File: client/asset/btc/spv_wrapper.go [hunk 3]
```diff
@@ -191,15 +191,44 @@ var (
...
+		if !exist {
+			if err := os.MkdirAll(logDir, 0744); err != nil {
+				return nil, fmt.Errorf("error creating log directory: %w", err)
+			}
+		} else {
+			// Move old logs to new log path.
+			if err := os.Rename(oldDir, logDir); err != nil {
+				return nil, err
+			}
+		}
```
Comment (buck54321) [inline client/asset/btc/spv_wrapper.go:214]: I personally think it'd be fine to skip this "upgrade" step.

File: client/asset/bch/spv.go [hunk 4]
```diff
@@ -942,20 +942,49 @@ func (w logWriter) Write(p []byte) (n int, err error) {
...
+	exist, err := fileExists(logDir)
+	if err != nil {
+		return nil, err
+	}
+	if !exist {
+		oldDir := filepath.Join(netDir, "logs")
+		exist, err := fileExists(oldDir)
+		if err != nil {
+			return nil, err
+		}
```
Comment (buck54321) [inline client/asset/bch/spv.go:955]: As mentioned in other comment, I'm not certain we need this upgrade check, but if we do, we probably wouldn't bail on an error here. 

We also have `dex.FileExists`, which returns just a bool.

Comment (ukane-philemon) [reply client/asset/bch/spv.go:955]: Okay. I didn't want to use the dex pkg in the assets pkg to reduce dependency. But maybe it's okay?

Comment (buck54321) [reply client/asset/bch/spv.go:955]: We're already importing it.

File: client/asset/btc/spv_wrapper.go (hunk 3 above)
Comment (chappjc) [reply client/asset/btc/spv_wrapper.go:214]: Was thinking the same, especially since it's a perpetual upgrade.  I'd want to remove this stuff eventually, but when?  Let's just leave things

Comment (ukane-philemon) [reply client/asset/btc/spv_wrapper.go:214]: >  Let's just leave the old log alone

Alright.

File: client/asset/dcr/spv.go [hunk 5]
```diff
@@ -939,7 +938,7 @@ var (
 // logRotator initializes a rotating file logger.
 func logRotator(netDir string) (*rotator.Rotator, error) {
 	const maxLogRolls = 8
-	logDir := filepath.Join(netDir, logDirName)
+	logDir := filepath.Join(filepath.Dir(netDir), logDirName)
```
Comment (chappjc) [inline client/asset/dcr/spv.go:941]: Should be just telling `logRotator` the right parent dir to use, not have `logRotator` strip a path.  Here's the right place:

https://github.com/decred/dcrdex/blob/441eeb3df87ada71afe0565d624a581793403a76/client/asset/dcr/spv.go#L141-L142

Don't pass that `dir` and expect `logRotator` to strip off `"spv"`.  Instead have an intermediate `netDir := filepath.Join(dataDir, chainParams.Name)` That you give to `logRotator`

File: client/asset/btc/spv.go [hunk 6]
```diff
@@ -58,18 +58,20 @@ var _ BTCWallet = (*btcSPVWallet)(nil)
...
+	netDir := filepath.Join(dataDir, net.Name)
+	walletDir := filepath.Join(netDir, "spv")
+
+	if err := logNeutrino(netDir); err != nil {
 		return fmt.Errorf("error initializing btcwallet+neutrino logging: %w", err)
 	}
 
-	logDir := filepath.Join(dir, logDirName)
+	logDir := filepath.Join(netDir, logDirName)
 	err := os.MkdirAll(logDir, 0744)
```
Comment (chappjc) [inline client/asset/btc/spv.go:69]: Not something with this PR per se, but what are these two `Join`/`MkdirAll` lines doing here after `logNeutrino` anyway?

Comment (ukane-philemon) [reply client/asset/btc/spv.go:69]: Ah, yeah. I think I wanted to remove this. Because `logNrutrino` will create the directory.

File: client/asset/btc/spv_wrapper.go [hunk 7]
```diff
@@ -1158,7 +1158,25 @@ func (w *spvWallet) moveWalletData(backupDir string) error {
...
+
+func (w *spvWallet) copyWalletLogFile(dstDir string) error {
+	if err := os.MkdirAll(dstDir, 0744); err != nil {
+		return err
+	}
+	logBytes, err := os.ReadFile(w.logFilePath())
+	if err != nil {
+		return err
+	}
+	return os.WriteFile(filepath.Join(dstDir, logFileName), logBytes, 0744)
```
Comment (buck54321) [inline client/asset/btc/spv_wrapper.go:1179]: Is this sufficient? We have a log rotator that gzips logs periodically and performs some amount of truncation (starts from scratch?). For example, here is what my current mainnet **assetdb/btc/mainnet/logs** looks like.
image

Comment (chappjc) [reply client/asset/btc/spv_wrapper.go:1179]: Aren't we also going to have a collision between network at **assetdb/btc/spvlogs**?  That's the new log path right?

Comment (ukane-philemon) [reply client/asset/btc/spv_wrapper.go:1179]: > Is this sufficient?

Ah, maybe not. We would need to copy the whole directory content.

File: client/asset/btc/spv_wrapper.go [hunk 8]
```diff
@@ -1157,8 +1158,54 @@ func (w *spvWallet) moveWalletData(backupDir string) error {
...
+// destination directory without preserving the original file permissions.
+func copyDir(srcDir, dstDir string) error {
+	dirFiles, err := os.ReadDir(srcDir)
+	if err != nil {
+		return err
+	}
+
+	if err := os.MkdirAll(dstDir, 0744); err != nil {
+		return err
+	}
```
Comment (chappjc) [inline client/asset/btc/spv_wrapper.go:1188]: The docs for `copyDir` should also say `The destination folder must not exist.` if that's gonna be the restriction.

File: client/asset/btc/spv_wrapper.go [hunk 9]
```diff
@@ -1157,8 +1158,54 @@ func (w *spvWallet) moveWalletData(backupDir string) error {
...
+
+	for _, file := range dirFiles {
+		srcFile := filepath.Join(srcDir, file.Name())
+		dstFile := filepath.Join(dstDir, file.Name())
+		if file.IsDir() {
+			if err := copyDir(srcFile, dstFile); err != nil {
+				return err
+			}
+		} else if file.Type().IsRegular() {
+			logBytes, err := os.ReadFile(srcFile)
```
Comment (chappjc) [inline client/asset/btc/spv_wrapper.go:1198]: We should never do `os.ReadFile` to copy files.  Please see the design here: https://github.com/decred/dcrdata/blob/master/stakedb/ticketpool.go#L174-L220

In addition to using a streaming buffered implementation of `copyFile`, it also `Stat`s the dest dir and only makes it if needed.  We can keep your current restriction that it must not exist, but note that please.

What your code has that the linked code does not seems to be recursion, which is fine to keep, but we should change how we copy the files.

**Review by chappjc — CHANGES_REQUESTED** [review]
Works so that the wallet file is accessible (and continuous) after recover.

Just need to rework the file copy code so it is buffered, not loading a whole file into memory.

File: client/asset/btc/spv_wrapper.go (hunk 9 above)
Comment (ukane-philemon) [reply client/asset/btc/spv_wrapper.go:1198]: Alright, will look into the referenced code.

File: client/asset/btc/spv_wrapper.go (hunk 8 above)
Comment (ukane-philemon) [reply client/asset/btc/spv_wrapper.go:1188]: I think it should be a restriction.

**Review by chappjc — APPROVED** [review]
