### PR TITLE
client/dcr: Unlock wallet if acct not encrypted.

### LINKED ISSUE #1576: core/simnet_tests: account is not encrypted with a unique passphrase
As of commit 95c9a38b it seems the client core simnet tests fail with `error starting clients: dcr wallet authentication error: -4: encryption/decryption error: account is not encrypted with a unique passphrase`

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #1576

### CODE REVIEW

File: client/asset/dcr/rpcwallet.go [hunk 1]
```diff
@@ -688,10 +688,19 @@ func (w *rpcWallet) LockAccount(ctx context.Context, acctName string) error {
...
+// encrypted. Part of the Wallet interface.
 func (w *rpcWallet) UnlockAccount(ctx context.Context, pw []byte, acctName string) error {
-	return translateRPCCancelErr(w.rpcClient.UnlockAccount(ctx, acctName, string(pw)))
+	var res *walletjson.AccountUnlockedResult
+	res, err := w.rpcClient.AccountUnlocked(ctx, acctName)
+	if err != nil {
+		return err
+	}
+	if res.Encrypted {
+		return translateRPCCancelErr(w.rpcClient.UnlockAccount(ctx, acctName, string(pw)))
```
Comment (chappjc) [inline client/asset/dcr/rpcwallet.go:700]: Thank you for restoring this logic.  I suppose it makes sense to restore it down here in the `rpcWallet` code instead of up at the `ExchangeWallet` level where it was.

Also, I can confirm that `(*rpcWallet).LockAccount` does have this `accountunlocked` check.

File: client/core/core.go [hunk 2]
```diff
@@ -1700,6 +1700,7 @@ func (c *Core) CreateWallet(appPW, walletPW []byte, form *WalletForm) error {
 	if err != nil {
 		return err
 	}
+	defer crypter.Close()
```
Comment (chappjc) [inline client/core/core.go:1703]: Hmm, we don't do this *anywhere*, and there seem to be numerous places we should.  Can we split this out and address them all in another PR?

Comment (JoeGruffins) [reply client/core/core.go:1703]: ok.

Comment (JoeGruffins) [reply client/core/core.go]: diff https://github.com/decred/dcrdex/pull/1582/commits/0fdbd4e6688a9ac47b0812c22ede529f297575bc

**Review by chappjc — APPROVED** [review]
