### PR TITLE
server/eth: Monitor RPC provider health

### LINKED ISSUE #2122: server/eth: server needs to support startup with failing providers in the list
The server supports multiple providers, but at startup they all have to be working (connect as well as not old best header).
This means that if a provider gets their issue resolved later, you have to restart the server to start using it again.
With multiple providers in the eth.conf, it would make more sense to allow failed providers as long as there is at least one "working".  The failing providers can be rechecked periodically, or when rotating through providers.  Perhaps as long as the provider can connect at startup we can allow it with an old best header, just disregard that providers results until it is up-to-date?

### PR DESCRIPTION
**Pull request by martonp**
Previously, the ETH backend would not start if any of the providers could not connect or was outdated. Now, if at least one of the providers is able to connect and the header is recent, the backend will start. After connecting, a goroutine will start that will periodically check the health of the RPC providers, sort the list putting the non-outdated ones first, outdated ones after, and the ones that fail to respond last. Requests will then attempt to use the rpc providers in this order.

Closes #2122

### CODE REVIEW

**Review by norwnd — COMMENTED** [review]
If you don't mind me reviewing this.

**Review by norwnd — APPROVED** [review]

File: server/asset/eth/rpcclient.go [hunk 1]
```diff
@@ -110,11 +187,12 @@ func (c *rpcclient) connect(ctx context.Context) (err error) {
...
-	c.clients = make([]*ethConn, len(c.endpoints))
-	for i, endpoint := range c.endpoints {
+	c.clients = make([]*ethConn, 0, len(c.endpoints))
+	for _, endpoint := range c.endpoints {
 		client, err := rpc.DialContext(ctx, endpoint)
 		if err != nil {
-			return fmt.Errorf("unable to dial rpc to %q: %v", endpoint, err)
+			c.log.Errorf("Ethereum RPC client failed to connect to %q: %v", endpoint, err)
+			continue
 		}
```
Comment (JoeGruffins) [inline server/asset/eth/rpcclient.go:196]: I get this is the point of the pr, but I think it should still keep this failed node around and check periodically. Say an owner has a geth node that just isn't synced yet, and for whatever reason just doesn't respond here, or the server starts up with the node offline, they might not notice it was not added if they had a fallback and it did connect. You wouldn't want to keep your server down waiting for the eth node to act right. I don't think they can add again after starting? Which may be a use for the admin api endpoint at some point. But for now I think it should keep checking those.

The health checking loop does keep them around.

**Review by JoeGruffins — COMMENTED** [review]
Small thing that is loosely related, the simet harness continually appends to the file at $ETH_CONFIG_PATH in the dcrdex harness. If it could just write a new file every time that would be good.

`<<` to `>` I believe.
https://github.com/decred/dcrdex/blob/ea8cb4d7b468c83b3e842c13c252df739b07a889/dex/testing/dcrdex/harness.sh#L223-L228

File: server/asset/eth/rpcclient.go (hunk 1 above)
Comment (JoeGruffins) [reply server/asset/eth/rpcclient.go:196]: Actually, would market suspend -> resume attempt to connect all the nodes again?

**Comment by JoeGruffins** [comment]
Maybe could check that enpoints are not the same on initial start up? The harness copies the same address over and over, so I noticed 9 connections to the same node.
```
2023-02-13 12:33:39.888 [DBG] ASSET[eth]: Parsed 9 endpoints from the ETH config file
2023-02-13 12:33:39.888 [DBG] ASSET[eth][RPC]: API endpoints supported by /home/joe/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.892 [DBG] ASSET[eth][RPC]: API endpoints supported by ws://localhost:38557: admin:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.894 [DBG] ASSET[eth][RPC]: API endpoints supported by /home/joe/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.896 [DBG] ASSET[eth][RPC]: API endpoints supported by ws://localhost:38557: admin:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.897 [DBG] ASSET[eth][RPC]: API endpoints supported by /home/joe/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.899 [DBG] ASSET[eth][RPC]: API endpoints supported by ws://localhost:38557: admin:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.899 [DBG] ASSET[eth][RPC]: API endpoints supported by /home/joe/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.901 [DBG] ASSET[eth][RPC]: API endpoints supported by ws://localhost:38557: admin:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.902 [DBG] ASSET[eth][RPC]: API endpoints supported by /home/joe/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-02-13 12:33:39.903 [INF] ASSET[eth][RPC]: number of connected ETH providers: 9
```

File: server/asset/eth/rpcclient.go (hunk 1 above)
Comment (JoeGruffins) [reply server/asset/eth/rpcclient.go:196]: It appears not to.

Comment (martonp) [reply server/asset/eth/rpcclient.go:196]: > I get this is the point of the pr, but I think it should still keep this failed node around and check periodically.

Yeah I agree, it wouldn't hurt to attempt to connect once every few minutes.

**Review by JoeGruffins — APPROVED** [review]
Working well.

File: server/asset/eth/rpcclient.go [hunk 2]
```diff
@@ -84,52 +93,144 @@ func (c *rpcclient) clientsCopy() []*ethConn {
...
+	outdated
+	connected
+)
+
+func (c *rpcclient) checkConnectionStatus(ctx context.Context, conn *ethConn) connectionStatus {
 	hdr, err := conn.HeaderByNumber(ctx, nil)
 	if err != nil {
-		return false, fmt.Errorf("Failed to get header from %q: %v", conn.endpoint, err)
+		return failed
 	}
```
[the remark this answers is not in the document]
Comment (martonp) [reply server/asset/eth/rpcclient.go:158]: I added some logs.

File: server/asset/eth/rpcclient.go [hunk 3]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
+	if err != nil {
+		c.log.Errorf("Failed to get header from %q: %v", conn.endpoint, err)
+		return failed
+	}
+
+	if c.headerIsOutdated(hdr) {
+		c.log.Warnf("header fetched from %q appears to be outdated (time %s). If you continue to see this message, you might need to check your system clock",
+			conn.endpoint, time.Unix(int64(hdr.Time), 0))
+		return outdated
+	}
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:165]: Minor tweak to show age could be nice:

```go
	if c.headerIsOutdated(hdr) {
		hdrTime := time.Unix(int64(hdr.Time), 0)
		c.log.Warnf("header fetched from %q appears to be outdated (time %s is %v old). "+
			"If you continue to see this message, you might need to check your system clock",
			conn.endpoint, hdrTime, time.Since(hdrTime))
		return outdated
	}
```

File: server/asset/eth/rpcclient.go [hunk 4]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
 
 func (c *rpcclient) withClient(f func(ec *ethConn) error, haltOnNotFound ...bool) (err error) {
-	for range c.endpoints {
-		c.idxMtx.RLock()
-		idx := c.endpointIdx
-		ec := c.clients[idx]
-		c.idxMtx.RUnlock()
+	clients := c.clientsCopy()
 
+	for _, ec := range clients {
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:265]: nbd but `for _, ec := range c.clientsCopy() {` would be fine

File: server/asset/eth/rpcclient.go [hunk 5]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
+
+	c.clientsMtx.Lock()
+	defer c.clientsMtx.Unlock()
+	c.clients = clientsUpdatedOrder
+	c.healthCheckCounter = (c.healthCheckCounter + 1) % failingEndpointsCheckFreq
+
+	return len(healthyConnections) > 0
+}
+
+// monitorConnectionsHealth starts a goroutine that checks the health of all connections
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:246]: Can re-wrap.

**Review by buck54321 — CHANGES_REQUESTED** [review]

File: server/asset/eth/rpcclient.go [hunk 6]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
+		return fmt.Errorf("failed to connect to an up-to-date ethereum node")
+	}
 
-		es, err := swapv0.NewETHSwap(contractAddr, ec.Client)
-		if err != nil {
-			return fmt.Errorf("unable to initialize eth contract for %q: %v", endpoint, err)
-		}
-		ec.swapContract = &swapSourceV0{es}
-		ec.caller = client
+	go c.monitorConnectionsHealth(ctx)
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:319]: I think it's fine to have this unsupervised based on the caller's pattern of `connect`'s context cancellation followed by calling the `shutdown()` method, but it's a little confusing.  Seem like anything could go wrong?

Fundamentally I don't quite get why there's a there's both a context for connect, but also a shutdown method.  It's like the context on connect was sort of intended to just apply to the initial connection action (e.g. timeout), but this use of it makes it apply to longer running processes, which is compatible with how `(*ETHBackend).Connect` works...

Does this all seem fine or are things a bit mixed up?

**Review by chappjc — CHANGES_REQUESTED** [review]

File: server/asset/eth/rpcclient.go [hunk 7]
```diff
@@ -52,111 +56,258 @@ type ethConn struct {
...
-		// Try the next client.
-		c.idxMtx.Lock()
-		// Only advance it if another thread hasn't.
-		if c.endpointIdx == idx && len(c.endpoints) > 0 {
-			c.endpointIdx = (c.endpointIdx + 1) % len(c.endpoints)
-			c.log.Infof("Switching RPC endpoint to %q", c.endpoints[c.endpointIdx])
-		}
-		c.idxMtx.Unlock()
+
+		c.log.Errorf("Unpropagated error from %q: %v", ec.endpoint, err)
```
[the remark this answers is not in the document]
Comment (martonp) [reply server/asset/eth/rpcclient.go:274]: True, I'll move provider to the end if there's an error.

File: server/asset/eth/rpcclient.go [hunk 8]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
+
+// sortConnectionsByHealth checks the health of the connections and sorts them
+// based on their health. It does a best header call to each connection and
+// connections with non outdated headers are placed first, ones with outdated
+// headers are placed in the middle, and ones that error are placed last.
+// Every failingEndpointsCheckFreq health checks, the endpoints that have
+// never been successfully connection will be checked. True is returned if
+// there is at least one healthy connection.
+func (c *rpcclient) sortConnectionsByHealth(ctx context.Context) bool {
+	c.log.Tracef("sorting connections by health counter = %d", c.healthCheckCounter)
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:178]: Let's remove this trace now that we're getting closer to a final iteration.

File: server/asset/eth/rpcclient.go [hunk 9]
```diff
@@ -52,111 +56,268 @@ type ethConn struct {
...
+			failingConnections = append(failingConnections, conn)
+		}
+	}
+
+	for _, ec := range clients {
+		categorizeConnection(ec)
+	}
+
+	if c.healthCheckCounter == 0 && len(c.neverConnectedEndpoints) > 0 {
+		c.log.Tracef("number of never connected endpoints: %d", len(c.neverConnectedEndpoints))
```
Comment (chappjc) [inline server/asset/eth/rpcclient.go:203]: This can be an Infof or even a Warnf

File: server/asset/eth/rpcclient.go (hunk 6 above)
Comment (martonp) [reply server/asset/eth/rpcclient.go:351]: I got rid of the shutdown method. I guess the reason was to make sure that the ETH backend was shutdown before closing the client connections, but that can be handled with a new context as well.

**Review by buck54321 — APPROVED** [review]
