### PR TITLE
server: fail fast if txindex is not enabled for btc clones

### LINKED ISSUE #1778: server/zec: The getindexinfo rpc endpoint does not exist.
zec requires that the `-txindex` flag be set when starting as seen in #1767. Our current way of checking this is the `getindexinfo` rpc endpoint. However, it does not appear that zec has this. If there is a way to check we should as it is fatal for zec markets if this is not enabled. Maybe we can use `getrawtransaction` for a known transaction hash on test/mainnet, or could be an easier way. Also, maybe this should be an error and stop server start up?

### PR DESCRIPTION
**Pull request by ukane-philemon**
This ensures `txindex` is enabled by fetching information for a `coinbase` transaction of a given block which is essential for dex activities as it could be fatal for `btc` clone markets if this is not enabled. Closes #1778 

Litecoin Core version v0.21.2.1 has `getindexinfo` rpc command. Tested with bitcoin cash, dogecoin, litecoin and should work for zcash(my zec refuses to sync).
PS: @JoeGruffins, I'd be glad if you can find time to test this with zcash.

### CODE REVIEW

**Review by JoeGruffins — APPROVED** [review]
Working for zcash.

**Comment by JoeGruffins** [comment]
Unrelated to these changes, but if you send an rpc request to zcash while it is still doing the initial scan, the request hangs forever.

File: server/asset/btc/rpcclient.go [hunk 1]
```diff
@@ -107,12 +108,46 @@ type txIndexResult struct {
...
-	if err != nil {
-		return false, err
+	if err == nil {
+		// Return early if there is no error. bitcoind returns an empty json
+		// object if txindex is not enabled. It is safe to conclude txindex is
+		// enabled if res.Txindex is not nil.
+		return res.TxIndex != nil, nil
+	}
+
+	if isMethodNotFoundErr(err) {
```
Comment (chappjc) [inline server/asset/btc/rpcclient.go:118]: Let's negate the condition, unindent the new code, and `return false, err` in the branch instead.

File: server/asset/btc/rpcclient.go [hunk 2]
```diff
@@ -249,6 +284,22 @@ func (rc *RPCClient) GetBlockVerbose(blockHash *chainhash.Hash) (*GetBlockVerbos
...
+	if err != nil {
+		return nil, err
+	}
+
+	blockHash, err := chainhash.NewHashFromStr(blockHashStr)
+	if err != nil {
+		return nil, err
+	}
+
+	return blockHash, nil
```
Comment (chappjc) [inline server/asset/btc/rpcclient.go:300]: The boiler plate isn't really needed here. `return chainhash.NewHashFromStr(blockHashStr)`.

Actually, this whole function could be `return rc.callHashGetter(methodGetBlockHash, anylist{index})`, but I can't stand that `callHashGetter` helper TBH.  :laughing:

File: server/asset/btc/rpcclient.go [hunk 3]
```diff
@@ -249,6 +284,22 @@ func (rc *RPCClient) GetBlockVerbose(blockHash *chainhash.Hash) (*GetBlockVerbos
 	return res, rc.call(methodGetBlock, anylist{blockHash.String(), arg}, res)
 }
 
+// GetBlockHash fetches the block hash for the block at the given index.
+func (rc *RPCClient) GetBlockHash(index int64) (*chainhash.Hash, error) {
+	var blockHashStr string
+	err := rc.Call(methodGetBlockHash, []interface{}{index}, &blockHashStr)
```
Comment (chappjc) [inline server/asset/btc/rpcclient.go:290]: Pattern is to use `rc.call`, the non-exported version.
Also `anylist{index}`, but it's the same.

**Review by chappjc — CHANGES_REQUESTED** [review]
Looks pretty reasonable to me.  A few little nits.

File: server/asset/btc/rpcclient.go (hunk 3 above)
Comment (ukane-philemon) [reply server/asset/btc/rpcclient.go:290]: > Pattern is to use rc.call, the non-exported version.

Yeah, thanks for the review.

File: server/asset/btc/rpcclient.go (hunk 2 above)
Comment (ukane-philemon) [reply server/asset/btc/rpcclient.go]: I could leave it all in `checkTxIndex` but I'd like to keep it cleaner.

**Comment by ukane-philemon** [comment]
> Unrelated to these changes, but if you send an rpc request to zcash while it is still doing the initial scan, the request hangs forever.

Hmm, other btc clones return an error almost immediately. I think using a new `ctx`  with timeout when making requests with an `rpcClient` should cover such a scenario.

**Review by chappjc — APPROVED** [review]
