### PR TITLE
asset: display asset symbol in failed connect message

### LINKED ISSUE #2066: Messaging for missing RPC wallets isn't great
When a wallet can't be found on startup, the error message doesn't even inform the user of which wallet it was.

image

### PR DESCRIPTION
**Pull request by ukane-philemon**
Resolves #2066.

Wallet connection warning

### CODE REVIEW

File: client/core/wallet.go [hunk 1]
```diff
@@ -340,15 +340,15 @@ func (w *xcWallet) Connect() error {
 	// ConnectOnce so that the ConnectionMaster's On method will report false.
 	err := w.connector.ConnectOnce(context.Background())
 	if err != nil {
-		return err
+		return fmt.Errorf("%s: %w", unbip(w.AssetID), err)
```
Comment (chappjc) [inline client/core/wallet.go:343]: Would be `w.Symbol` for these.
However, the caller knows what wallet it's using, so instead of decorating every error returned from this method with a symbol, it would be better to have the caller do it.  AFAICT, that's only `(*Core).connectWalletResumeTrades`, so change `codedError` there to `newError` and it's done.  That's the pattern in the other methods that surround it.

**Review by chappjc — CHANGES_REQUESTED** [review]

File: client/core/wallet.go (hunk 1 above)
Comment (ukane-philemon) [reply client/core/wallet.go]: I see we currently do `unbip(w.AssetID)` even when we have access to `w.Symbol`, would you want me to change those too to use `w.Symbol`?

Comment (chappjc) [reply client/core/wallet.go]: Just here is fine.  That field happens to be new is all.

**Review by chappjc — APPROVED** [review]
