### PR TITLE
app: fix markets view layout issues

### LINKED ISSUE #550: web: market sell has rate/price form
image

This seems to be a regression.  Market sell should just have a number of lots form.

### PR DESCRIPTION
**Pull request by buck54321**
Fixes issues where overflow and div sizing were acting weird on resize. 

Creates and uses a stylish scrollbar class. Enables manual chart div click-drag resizing and remembers the user's preference across sessions. 

Also corrects a recent regression where certain order form elements were not being hidden for market orders.

Most of the loc are just html indentation changes. Best tested with the [test app server](https://github.com/decred/dcrdex/wiki/Test-App-Server).

resolves #550, #514, #296, #539

### CODE REVIEW

File: client/webserver/site/src/js/charts.js [hunk 1]
```diff
@@ -74,12 +74,10 @@ export class DepthChart {
...
-    this.wheel = this.wheel_.bind(this)
-    bind(this.canvas, 'wheel', this.wheel)
-    this.resize = this.resize_.bind(this)
-    bind(window, 'resize', this.resize)
-    this.click = this.click_.bind(this)
-    bind(this.canvas, 'click', this.click)
+
+    bind(this.canvas, 'wheel', e => { this.wheel(e) })
+    bind(window, 'resize', e => { this.resize(e) })
+    bind(this.canvas, 'click', e => { this.click(e) })
```
Comment (chappjc) [inline client/webserver/site/src/js/charts.js:80]: Is this effectively the same as doing `bind(this.canvas, 'click', click.bind(this))` to get `this` to be the `DepthChart` inside of `click`?

Comment (buck54321) [reply client/webserver/site/src/js/charts.js:80]: That's right. I'm not sure why I had it the old way.

**Comment by buck54321** [comment]
739d61e contains fixes for https://github.com/decred/dcrdex/issues/516 and https://github.com/decred/dcrdex/issues/532. Sorry if anybody was mid-review.

File: client/webserver/site/src/js/markets.js [hunk 2]
```diff
@@ -198,6 +199,35 @@ export default class MarketsPage extends BasePage {
...
+    bind(page.chartResizer, 'mousedown', e => {
+      if (e.button !== 0) return
+      e.preventDefault()
+      const trackMouse = ee => {
+        ee.preventDefault()
+        const box = page.rightSide.getBoundingClientRect()
+        const h = box.bottom - box.top
+        var chartRatio = (ee.pageY - box.top) / h
+        setChartRatio(chartRatio)
+        State.store(chartRatioKey, chartRatio)
```
Comment (chappjc) [inline client/webserver/site/src/js/markets.js:223]: Seems like it should store the key on `mouseup` rather than on each mouse movement.  Practically maybe it doesn't matter?  Oh, I guess the `mousemove` event fires when the mouse **stops** after movement -- that works then if that is correct.

File: client/webserver/site/src/html/markets.tmpl [hunk 3]
```diff
@@ -36,280 +36,287 @@
...
+            <table class="ordertable bg0">
+              {{block "thead" .}}
+              <thead>
+                <tr>
+                  <th class="text-left pl-2">Quantity</th>
+                  <th class="text-right pr-2">Rate</th>
+                  <th class="text-right pr-2">Epoch</th>
+                </tr>
+              </thead>
+              {{end}}
```
Comment (chappjc) [inline client/webserver/site/src/html/markets.tmpl:69]: I'm no template guru, but I can't understand what this block does.

Comment (buck54321) [reply client/webserver/site/src/html/markets.tmpl:69]: The block is defined here for reuse on the sells table. Look for `{{template "thead"}}` below.

Comment (chappjc) [reply client/webserver/site/src/html/markets.tmpl:69]: Ahhhh, I didn't think about a block being reusable.  For reason I though it was a one-time define and execute kind of thing.

**Comment by buck54321** [comment]
@chappjc, I was unable to reproduce the `formatCoinValue` error. I've added a console error message that should give some insight if you can still reproduce.

**Comment by chappjc** [comment]
I'm not seeing it any more either, at least not with a fresh harness.  The one I had with over 1 million DCR was pretty unusual.

**Comment by chappjc** [comment]
Here's the repro with 1218684.00822222:

```javascript
function str(x){
  return x.toLocaleString('en-us', fullPrecisionSpecs);
}

const fullPrecisionSpecs = {
  minimumSignificantDigits: 4,
  maximumSignificantDigits: 8,
  minimumFractionDigits: 8,
  maximumFractionDigits: 8
}
let v = 1218684.00822222
var vStr = str(v)
console.log(vStr)
var [whole, frac] = vStr.split('.')
console.log(whole, frac);
```

https://jsfiddle.net/nsp49o7y/

**Comment by buck54321** [comment]
Fixed `formatCoinValue` in 741523f. We could use unit tests for functions like this, so I actually tested a couple of js unit testing frameworks, but ran into some unfortunate issues with both. I'll keep looking for a suitable framework.
