### PR TITLE
client: Let core handle redeem and refund locking.

### LINKED ISSUE #1539: client/eth: 12600000 > 0 redemption funds reserved error.
I apologize if this is already an issue. I feel like we have had several issues/pr about this, but when trading on simnet or testnet, I still see `[ERR] CORE: retiring order 0d52237b5b799d416c78d35543ce3ef05c4a7fa118be701f2cd4600d8c23cc4d with 12600000 > 0 redemption funds reserved` If this is expected, we should not log as error. If not expected should fix.

To reproduce make a 1lot trade for dcr/eth and watch it to the end.

### PR DESCRIPTION
**Pull request by JoeGruffins**
For account based coins, let core use the Reserve and Unlock methods to
    handle redemption and refund reserves for assets that use them. This
    solves a minor bug where redemption funds are not unlocked for a tracked
    trade that is redeemed normally.

closes #1539

### CODE REVIEW

**Review by martonp — APPROVED** [review]
Looks good, but why was it not working properly previously?

**Comment by JoeGruffins** [comment]
> Looks good, but why was it not working properly previously?

Awesome!

The refunds should have spit out more errors, I just don't think we test them enough.

I think the accounting for the eth package was fine, just unlocking the same funds multiple times in some circumstances, because core is also tracking this for the trade. I don't guess the core locker serves a purpose besides logging? This does not solve #1544 which I guess I'll look into next...

**Comment by chappjc** [comment]
> I think the accounting for the eth package was fine, just unlocking the same funds multiple times in some circumstances, because core is also tracking this for the trade. I don't guess the core locker serves a purpose besides logging?

Can you expand on this?  So both core and internally eth were unlocking stuff?  Are we following a consistent approach to the responsibility of coin locking / unlocking?

File: client/core/core.go [hunk 1]
```diff
@@ -5948,10 +5948,14 @@ func (c *Core) listen(dc *dexConnection) {
 			for _, trade := range doneTrades {
 				// Log an error if redemption funds are still reserved.
 				trade.mtx.RLock()
-				reserved := trade.redemptionLocked
+				redeemLocked := trade.redemptionLocked
+				refundLocked := trade.refundLocked
```
Comment (chappjc) [inline client/core/core.go:5952]: Moving the refund unlocking does look more consistent, given we were doing it here for redeems...

This change set does feel better.

**Comment by JoeGruffins** [comment]
> So both core and internally eth were unlocking stuff?

Yes.

Here when we redeem in core, we unlock the refund reserves in core and the eth package:
https://github.com/decred/dcrdex/blob/fb76b59006d744e149a48ecc2218eaead4920819/client/core/trade.go#L2038-L2042
but we unlock the redeem reserves in the eth package only, hence there being reserves left in the trade reserves at the end for a normal redeem:
https://github.com/decred/dcrdex/blob/fb76b59006d744e149a48ecc2218eaead4920819/client/asset/eth/eth.go#L878

If we want to lock/unlock the coins for both, the eth package cannot touch core, so it only makes sense to let core handle it imo. Core is already handling all the locking and most of the unlocking.

> Are we following a consistent approach to the responsibility of coin locking / unlocking?

No but this should change that as all use of the account locker methods inside the eth package is removed in this pr. That is `ReserveNRedemptions`, `UnlockRedemptionReserves`, `ReReserveRedemption`, `ReserveNRefunds`, `UnlockRedemptionReserves`, and `ReReserveRefund` are only used in core.

File: client/core/trade.go [hunk 2]
```diff
@@ -2043,6 +2030,11 @@ func (c *Core) redeemMatchGroup(t *trackedTrade, matches []*matchTracker, errs *
 			match.Status = order.MakerRedeemed
 			proof.MakerRedeem = coinID
 		}
+		if t.isMarketBuy() {
+			t.unlockRedemptionFraction(1, uint64(len(t.matches)))
+		} else {
+			t.unlockRedemptionFraction(match.Quantity, t.Trade().Quantity)
+		}
```
Comment (buck54321) [inline client/core/trade.go:2037]: How about just sum the `match.Quantity` while you loop so you can call your unlock functions just once at the end?

**Comment by chappjc** [comment]
Hmm, last change [didn't work out](https://github.com/decred/dcrdex/runs/5882544593?check_suite_focus=true):

```
 2022-04-08 09:09:59.421 [ERR] TCORE: attempting to unlock more than is reserved for order a5aafd01d81f56054d7021ae9aa643adf30c5fad3f415275792169cd0e4de453. unlocking reserved amount instead: 0 reserved, unlocking 40
2022-04-08 09:09:59.422 [INF] TCORE: loaded 1 incomplete orders
--- FAIL: TestResolveActiveTrades (0.00s)
    core_test.go:5269: initial: side = Taker, order status = booked, match status = MakerSwapCast: redemption funds not reserved, 10 != 50
```

**Comment by chappjc** [comment]
A few mostly trivial conflicts created by https://github.com/decred/dcrdex/pull/1523

**Comment by JoeGruffins** [comment]
Yes, srry. I should run tests first. I'm looking into it.

Oh conflicts good. Srry I didn't re-review #1523, was getting around to it...

File: client/core/core.go [hunk 3]
```diff
@@ -5349,8 +5354,12 @@ func (c *Core) resumeTrades(dc *dexConnection, trackers []*trackedTrade) assetMa
 		tracker.recalcFilled()
 
 		if isActive {
-			tracker.lockRedemptionFraction(trade.Remaining(), trade.Quantity)
-			tracker.lockRefundFraction(trade.Remaining(), trade.Quantity)
```
Comment (JoeGruffins) [inline client/core/core.go:5353]: This was incorrect right? We were locking per match and here at the end. We should just do the targeted locks...

File: client/core/core_test.go [hunk 4]
```diff
@@ -5240,10 +5241,12 @@ func TestResolveActiveTrades(t *testing.T) {
...
 		}
 
+		isActive := dbOrder.MetaData.Status == order.OrderStatusBooked || dbOrder.MetaData.Status == order.OrderStatusEpoch
+
 		if lo.T.Sell && ((match.Side == order.Taker && match.Status < order.MatchComplete) ||
 			(match.Side == order.Taker && match.Status < order.MakerRedeemed)) {
-			var reReserveQty uint64 = redemptionReserves
-			if dbOrder.MetaData.Status > order.OrderStatusBooked {
+			var reReserveQty uint64
+			if isActive {
```
Comment (JoeGruffins) [inline client/core/core_test.go:5249]: Not sure what was going on with this test. We only want locked if the matches are active correct?

File: client/core/core.go (hunk 3 above)
Comment (JoeGruffins) [reply client/core/core.go:5353]: Oh wait, this is locking unmatched funds.

File: client/core/core_test.go (hunk 4 above)
Comment (JoeGruffins) [reply client/core/core_test.go]: Ok, I got it now. We want them all locked unless the match is no longer active then just the matched. Took a while to seep in.

File: client/core/trade.go [hunk 5]
```diff
@@ -214,9 +214,9 @@ func (t *trackedTrade) accountRefunder() (asset.AccountLocker, bool) {
 	return ar, is
 }
 
-// lockRedemptionFraction locks the specified fraction of the available
+// lockRefundFraction locks the specified fraction of the available
 // refund reserves. Subsequent calls are additive. If a call to
-// lockRedemptionFraction would put the locked reserves > available reserves,
+// lockRefundFraction would put the locked reserves > available reserves,
```
Comment (chappjc) [inline client/core/trade.go:219]: Not related to your changes, but I'm having a very hard time understanding why we're going to so much trouble of working with a rational number's numerator and denominator if we just end up doing this:

```
func applyFraction(num, denom, target uint64) uint64 {
	return uint64(math.Round(float64(num) / float64(denom) * float64(target)))
}
```

We're _are_ going to see precision loss and likely the occasional wrong result, but we still have to jump through all these hoops.  What am I missing?

I'm looking at `math/big.Rat` if we want to be rigorous w.r.t. precision.  Thoughts or clarification?

Comment (chappjc) [reply client/core/trade.go:219]:
```go
func applyFraction(num, denom, target uint64) uint64 {
	frac := big.NewRat(int64(num), int64(denom))
	res, exact := new(big.Rat).Mul(frac, big.NewRat(int64(target), 1)).Float64()
	fmt.Println("**************** frac:", frac)
	fmt.Println("**************** val:", target)
	fmt.Printf("**************** scaled: %v (f) => %d (i) (exact = %v)\n", res, uint64(math.Round(res)), exact)
	simple := uint64(math.Round(float64(num) / float64(denom) * float64(target)))
	fmt.Println("**************** simple:", simple)
	return simple
}
```

Exposes some issues with `TestRedemptionReserves` and `TestRefundReserves`.  In particular trying to divide an order size by a value that the order cannot be split evenly.

Test issues aside, I'm still thinking that we an change the `trackedTrade` fields to a new system whereby for say, redeem reserves, one field is the multiple size and the other field is the number of reserved multiples.  Then the unlock methods just need to specify an integer multiple to unlock, which just decrements the locked integer.

Comment (chappjc) [reply client/core/trade.go:219]: Nothing to change with this PR, @JoeGruffins .  Just clarifying

Comment (JoeGruffins) [reply client/core/trade.go:219]: I agree. The current locker does deal with "dust" if a remainder slipped through, but there's probably a more strait forward answer. I'll make an issue?

Comment (buck54321) [reply client/core/trade.go:219]: > I'll make an issue?

For what?

Comment (chappjc) [reply client/core/trade.go:219]: The fraction system is turning out to be brittle, complex, and prone to precision loss and rounding error.  If we continue to have trouble with reserves locking, I'll propose some changes as I described in the last paragraph here: https://github.com/decred/dcrdex/pull/1556#discussion_r846523350
No need to divert effort yet.

Comment (buck54321) [reply client/core/trade.go:219]: But as @JoeGruffin's pointed out, your comment 

> Exposes some issues with TestRedemptionReserves and TestRefundReserves. In particular trying to divide an order size by a value that the order cannot be split evenly.

is incorrect, since we deal with rounding errors in `reservesToUnlock`.

There've clearly been some hiccups in implementing refunds, but that doesn't mean the system is brittle or complex.

Not trying to stop you from trying your plan though.

Comment (chappjc) [reply client/core/trade.go:219]: I don't mean to harshly criticize the design here; I just believe that it does not handle rounding well and it its use is error prone.

In `applyFraction`, the `math.Round` deals with floating point _precision_ errors, not errors in the input arguments that create an expression where the number cannot be divided evenly even on paper, never mind floating point precision.  The main issue is not when precision results in something like 3999.9999997, and that rounds to 4000 just fine; it's when num and denom result in something like 13333.4 or 666.6666666.  The result will just be wrong because the caller gave unsatisfiable inputs.

I _sort of_ understand the dust handling in `reservesToUnlock`, but why should there be dust.  Also what if the rounding in applyFraction goes the other way an is unlocking one extra gwei instead?  Is that all handled?  I cannot tell.

In the tests, run with the modified code I posted above.  First thing I noticed is this:

```
**************** frac: 2/3
**************** val: 100000
**************** scaled: 66666.66666666667 (f) => 66667 (i) (exact = false)
**************** simple: 66667
```

because of 
```
const reserves = 100_000
qty := lotSize * 10
matchQty := qty * 2 / 3
matchReserves := applyFraction(2, 3, reserves)
```

The math.Round isn't correcting for floating point precision with this; it's just not a whole number _on paper_.  Is this really expected?  I don't get it if so.

Even if this is all somehow "right", there's still little point in keeping num and denom separate because of `math.Round(float64(num) / float64(denom) * float64(target))`, which divides num/denom into a float first anyway.

Comment (chappjc) [reply client/core/trade.go:219]: I'm sure a big part of this is just me being slow, but I am confused by how to use the functions and what the arguments mean, and I'm surprised at the acrobatics needed to deal with the reserves.

Comment (buck54321) [reply client/core/trade.go:219]: I hear ya. I'll add some notes to explain some of the choices and hopefully save you some time in implementation.

- **Assuming that the redemption and refund reserves are evenly divisible by the number `n` passed to `ReserveNRedemptions`**, then for all orders but market buy orders, everything will work out evenly without rounding.
- The generalization of returns as fractional is to deal with market buy orders, where we can't know at order-time how many matches there will be. We **could** store the `n` value estimate we used to reserve and use that to eliminate rounding for market buy orders.
- I do think that the integer system that you're planning will be mathematically identical to this, just with more data persistence. Consider this. I could, instead of 
 
```Go
returnQty := applyFraction(matchQuantity, orderQuantity, reserves)
```
do
```Go
matchLots := matchQuantity / mktInfo.LotSize
orderLots := orderQuantity / mktInfo.LotSize
returnQty := applyFraction(matchLots, orderLots, reserves)
```

One problem is we're not saving the market info, but let's overlook that for a second.

If we were instead to save **a reserve quantity per lot** (in the spirit of your suggestion, I think), then we might have something like this

```Go
matchLots := matchQuantity / mktInfo.LotSize
returnQty := tracker.reserveQtyPerLot * matchLots
```

Which looks clean, but would require the persistence of more data.

Going back now, internally in `applyFraction`, I do roughly

```Go
return matchQuantity / orderQuantity * reserves
```
or equivalently
```Go
return matchLots / orderLots * reserves
```
Multiplying numerator and denominator by `1 / orderLots`
```Go
return matchLots * (reserves / orderLots)
```

which is exactly where we got with the alternative approach. Same result, more data persistence required. 

> Even if this is all somehow "right", there's still little point in keeping num and denom separate because of `math.Round(float64(num) / float64(denom) * float64(target))`, which divides num/denom into a float first anyway.

I'm not sure I understand. How else could I handle `num` and `denom`?

Comment (chappjc) [reply client/core/trade.go:219]: Thanks for describing that all in detail.  I appreciate it.

> I'm not sure I understand. How else could I handle `num` and `denom`?

Because `num` and `denom` only ever get used in `applyFraction` (afaict), it could be: 

```go
// frac is on [0,1], target is an amount in atomic units.
func applyFraction(frac float64, target uint64) uint64 {
	return uint64(math.Round(frac * float64(target)))
}
```

Given the above, unless we got fancy with integer math or big.Rat, I'm not seeing a reason to make the caller worry about espressing the frac as a rational number.

Comment (buck54321) [reply client/core/trade.go:219]: I was just trying to avoid math and conversions at the call sites.

**Review by chappjc — APPROVED** [review]
OK.  I'm still a bit perturbed that we have to compute a least common multiple via greatest common divisor via Euclidean algorithm just reservere/unreserve some funds...
