### PR TITLE
app: auto-refund swaps when trade fails

### LINKED ISSUE #302: core: send refund transaction when taker goes dark
If 1) the client is the maker on a match, 2) the match status is `MakerSwapCast`, and 3) it's been 48 hours since the swap was broadcast, the maker should `Refund` the swap tx.

### PR DESCRIPTION
**Pull request by itswisdomagain**
Resolves #302.

In addition to checking for matches that require a swap or redemption broadcast, also check for failed matches where the client has a pending/unspent swap output and perform auto-refund where possible.

The following match disruption scenarios, necessitating a refund, are considered:
- The client is the (Maker) and has broadcast their init swap but up till the locktime expiry on the client's/Maker's swap, the other party (the Taker) has not sent "notification" of their counterswap (or sent a counterswap that failed audit checks).
- The client is the Taker and has broadcast their counterswap but up till the locktime expiry on the client's/Taker's counterswap, the other party (the Maker) has not sent "notification" of their redeeming the counterswap (or sends an invalid notification).

### CODE REVIEW

File: client/core/trade.go [hunk 1]
```diff
@@ -503,7 +584,7 @@ func (t *trackedTrade) tick() (int, error) {
 		// notifications before swapMatches.
 		corder, _ := t.coreOrderInternal()
 		if err != nil {
-			errs.add("swapMatches: %v", err)
+			errs.addErr(err)
```
Comment (itswisdomagain) [inline client/core/trade.go:587]: The `err` returned from `swapMatches()` already contain the `"swapMatches - ..."` prefix.

File: client/asset/dcr/dcr.go [hunk 2]
```diff
@@ -987,9 +999,12 @@ func (dcr *ExchangeWallet) FindRedemption(ctx context.Context, coinID dex.Bytes)
...
 // Refund refunds a contract. This can only be used after the time lock has
 // expired.
-func (dcr *ExchangeWallet) Refund(receipt asset.Receipt, nfo *dex.Asset) error {
-	op := receipt.Coin()
-	txHash, vout, err := decodeCoinID(op.ID())
+// NOTE: The contract cannot be retreived from the unspent coin info as the
+// wallet does not store it, even though it was known when the init transaction
+// was created. The DEX should store this information for persistence across
+// sessions.
+func (dcr *ExchangeWallet) Refund(coinID, contract dex.Bytes, nfo *dex.Asset) error {
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:1006]: This is a good move. Since the exchange wallets are arbitrating refundability via `LockTimeExpired` now, we can probably drop the `asset.Receipt` interface altogether and just use `asset.Coin`s.

File: client/core/trade.go [hunk 3]
```diff
@@ -533,7 +580,21 @@ func (t *trackedTrade) tick() (int, error) {
...
+		corder, _ := t.coreOrderInternal()
+		details := fmt.Sprintf("Refunded %.8f %s on order %s",
+			float64(refunded)/conversionFactor, unbip(t.wallets.fromAsset.ID), t.token())
+		if err != nil {
+			errs.addErr(err)
+			t.notify(newOrderNote("Match failure", details+", with some errors", db.ErrorLevel, corder))
+		} else {
+			t.notify(newOrderNote("Match failure", details, db.WarningLevel, corder))
+		}
+	}
```
Comment (JoeGruffins) [inline client/core/trade.go:595]: I think this would be better as two notifications. One for the match failure, and possibly another if there is a refund error.

File: client/core/trade.go [hunk 4]
```diff
@@ -533,7 +580,21 @@ func (t *trackedTrade) tick() (int, error) {
 			t.notify(newOrderNote("Match complete", details, db.Poke, corder))
 		}
 	}
-	return len(swaps) + len(redeems), errs.ifany()
+
+	if len(refunds) > 0 {
+		refunded, err := t.refundMatches(refunds)
+		corder, _ := t.coreOrderInternal()
+		details := fmt.Sprintf("Refunded %.8f %s on order %s",
```
Comment (JoeGruffins) [inline client/core/trade.go:587]: trying this out on a dcr_btc market, both refunds will say I was refunded dcr, but really one was btc, so this should use the terminology `worth` as above I think.

File: client/core/core.go [hunk 5]
```diff
@@ -2219,6 +2219,12 @@ func handleRevokeMatchMsg(_ *Core, dc *dexConnection, msg *msgjson.Message) erro
...
 	}
 
+	// todo: consider checking if any refunds/forced redemption are necessary
+	// before setting this match's status to Revoked.
+	// Alternatively, set status to Revoked but "remember" to attempt Refund/
+	// FindRedemption if necessary. Currently, `trackedTrade.isRefundable` will
+	// return false for this match because of the status change.
+
 	md := tracker.metaData
 	md.Status = order.OrderStatusRevoked
```
Comment (buck54321) [inline client/core/core.go:2229]: Hmm. I now see that there are some issues here with revocation handling. Revocations can apply to individual matches and not entire order. The server side handling has some of the logic conflated as well, it seems, where the revocation is applied to the order instead of the match. If I'm reading this right, it's going to take some work to get it corrected. For now, I think we should handle it by tracking the revocation as part of the `MatchProof`. 

Though it's tempting, we don't want to add a new `order.MatchStatus` e.g. `MatchRevoked`, because we may still want to know what the order status was when it was revoked.

File: client/core/trade.go [hunk 6]
```diff
@@ -472,26 +472,73 @@ func (t *trackedTrade) isRedeemable(match *matchTracker) bool {
...
+	}
+
+	dbMatch, metaData, proof, _ := match.parts()
+	var side string
+	switch {
+	case dbMatch.Side == order.Maker && metaData.Status == order.MakerSwapCast:
+		side = "Maker"
+	case dbMatch.Side == order.Taker && metaData.Status == order.TakerSwapCast:
+		side = "Taker"
+	default:
```
[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/trade.go:498]: We'll need a way to check if the match has been revoked here. Even though the issue is pre-existing, could you add a field to the `db.MatchProof` so we can tell if the match has been revoked and set the field in `handleRevokeMatchMsg`?

File: client/db/types.go [hunk 7]
```diff
@@ -271,28 +273,29 @@ func DecodeMatchProof(b []byte) (*MatchProof, error) {
...
+			InitStamp:       intCoder.Uint64(pushes[11]),
+			AuditSig:        pushes[12],
+			AuditStamp:      intCoder.Uint64(pushes[13]),
+			RedeemSig:       pushes[14],
+			RedeemStamp:     intCoder.Uint64(pushes[15]),
+			RedemptionSig:   pushes[16],
+			RedemptionStamp: intCoder.Uint64(pushes[17]),
 		},
 	}, nil
 }
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/db/types.go:301]: Yeah, this has been discussed before and the current thinking is keep stuff as v0 until initial release, so we'll likely continue to see these kinds of breaking changes during this active development period.

File: client/asset/interface.go [hunk 8]
```diff
@@ -103,8 +111,13 @@ type Wallet interface {
 	// regardless of whether the server sends the 'redemption' message or not.
 	FindRedemption(ctx context.Context, coinID dex.Bytes) (dex.Bytes, error)
 	// Refund refunds a contract. This can only be used after the time lock has
-	// expired.
-	Refund(Receipt, *dex.Asset) error
+	// expired AND if the contract has not been redeemed/refunded.
+	// CoinNotFoundError
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/asset/interface.go:115]: Oops

File: client/core/trade.go (hunk 4 above)
Comment (itswisdomagain) [reply client/core/trade.go:587]: Looking at the code again, this really shouldn't happen because refunds are always made to the `from` wallet, as that's the source of all client swaps. Can you recheck this?

File: client/core/trade.go [hunk 9]
```diff
@@ -533,7 +580,21 @@ func (t *trackedTrade) tick() (int, error) {
...
+		refunded, err := t.refundMatches(refunds)
+		corder, _ := t.coreOrderInternal()
+		details := fmt.Sprintf("Refunded %.8f %s on order %s",
+			float64(refunded)/conversionFactor, unbip(t.wallets.fromAsset.ID), t.token())
+		if err != nil {
+			errs.addErr(err)
+			t.notify(newOrderNote("Match failure", details+", with some errors", db.ErrorLevel, corder))
+		} else {
+			t.notify(newOrderNote("Match failure", details, db.WarningLevel, corder))
+		}
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go:594]: Thinking about this... I think it's possible that a match being refunded now may have been earlier identified as failed/disrupted, and "then" would be a better time to send the match failure message. Will wait to get specifics on **when** a match is actually considered failed before implementing this.

File: client/core/trade.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go:498]: Does it matter if the match has been revoked when checking refundability? I suspect whether revoked or not, we'd want to auto refund when the locktime expires.

File: client/core/trade.go [hunk 10]
```diff
@@ -735,6 +797,63 @@ func (t *trackedTrade) redeemMatches(matches []*matchTracker) error {
...
+			match.failErr = err
+			continue
+		}
+		if t.Trade().Sell {
+			refundedQty += match.Match.Quantity
+		} else {
+			refundedQty += calc.BaseToQuote(match.Match.Rate, match.Match.Quantity)
+		}
+		// todo: order.MatchFailed? Status needs to change so that refund is
+		// not re-attempted on trackedTrade.tick().
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go:846]: Not seeing it yet... is there an advantage to keeping the `{Actor}SwapCast` status after successful refund? Historical reasons perhaps?

[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/trade.go:846]: Is there any case in which a taker could go to a refund from any status other than `TakerSwapCast`, or a maker from an status other than `MakerSwapCast`? Now that I think about it, I don't think that there is. But we do want to save the refund coin for historical purposes.

[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/trade.go:846]: I see we're not returning the coin ID from `Refund` yet.

File: client/core/trade.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/trade.go:498]: That sounds right. Carry on.

File: client/core/trade.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go]: I've added that.

File: client/core/trade.go [hunk 11]
```diff
@@ -739,6 +799,61 @@ func (t *trackedTrade) redeemMatches(matches []*matchTracker) error {
...
+		var matchFailureReason string
+		switch {
+		case dbMatch.Side == order.Maker && metaData.Status == order.MakerSwapCast:
+			swapCoinID = proof.MakerSwap
+			matchFailureReason = "no valid counterswap received from Taker"
+		case dbMatch.Side == order.Taker && metaData.Status == order.TakerSwapCast:
+			swapCoinID = proof.TakerSwap
+			matchFailureReason = "no valid redemption received from Maker"
+		default:
+			log.Errorf("attempted to execute invalid refund for match %s", match.id)
```
Comment (buck54321) [inline client/core/trade.go:822]: Should print the side and status as part of the error message.

File: client/core/trade.go [hunk 12]
```diff
@@ -473,30 +473,75 @@ func (t *trackedTrade) isRedeemable(match *matchTracker) bool {
...
+			refunds = append(refunds, match)
 		}
 	}
-	if len(swaps) > 0 {
-		fromID := t.wallets.fromAsset.ID
+
+	fromID := t.wallets.fromAsset.ID
+	nSwapsAndRefunds := len(swaps) + len(refunds)
+	if nSwapsAndRefunds > 0 {
 		counts[fromID] = len(swaps)
```
Comment (buck54321) [inline client/core/trade.go:541]: ~~`len(swaps)`~~ 🡆`nSwapsAndRefunds` ?

File: client/core/trade.go [hunk 13]
```diff
@@ -537,6 +582,20 @@ func (t *trackedTrade) tick() (assetCounter, error) {
...
+	if len(refunds) > 0 {
+		refunded, err := t.refundMatches(refunds)
+		corder, _ := t.coreOrderInternal()
+		details := fmt.Sprintf("Refunded %.8f %s on order %s",
+			float64(refunded)/conversionFactor, unbip(fromID), t.token())
+		if err != nil {
+			errs.addErr(err)
+			t.notify(newOrderNote("Match failure", details+", with some errors", db.ErrorLevel, corder))
+		} else {
+			t.notify(newOrderNote("Match failure", details, db.WarningLevel, corder))
```
Comment (buck54321) [inline client/core/trade.go:595]: How about subjects `Refund Failure`, and `Matches Refunded`?

File: client/core/core.go [hunk 14]
```diff
@@ -2337,14 +2337,24 @@ func handleRevokeMatchMsg(_ *Core, dc *dexConnection, msg *msgjson.Message) erro
...
+			break
+		}
+	}
+	tracker.matchMtx.RUnlock()
+	if revokedMatch == nil {
+		return fmt.Errorf("no match found with id %s for order %s", matchID, oid.String())
 	}
 
-	return tracker.db.UpdateOrder(metaOrder)
+	revokedMatch.MetaMatch.MetaData.Proof.IsRevoked = true
```
Comment (buck54321) [inline client/core/core.go:2356]: Nice. Thanks for taking care of this.

File: client/core/trade.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/trade.go]: I think you have it working as is now, but I do think we should do something. I wouldn't want to use `MatchComplete` though, as I would consider that an indicator of success. I think it's okay in this case to add a new `MatchStatus` (since unlike a revocation, the status progression is unambiguous) if that works for everyone else.

File: client/core/trade.go (hunk 12 above)
Comment (itswisdomagain) [reply client/core/trade.go:541]: arghh

File: client/core/trade.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go]: Yeah, saving the refund coin prevents re-attempting to refund; while keeping the status may help in later review of where the trade went south. Maybe no need to change the status?

> Is there any case in which a taker could go to a refund from any status other than `TakerSwapCast`, or a maker from an status other than `MakerSwapCast`?

Missed this earlier. Maker could also refund if status is `TakerSwapCast` but maker was unable to redeem the Taker's swap for some reason. I see this isn't yet considered in this PR.

File: client/core/trade.go [hunk 15]
```diff
@@ -739,6 +812,67 @@ func (t *trackedTrade) redeemMatches(matches []*matchTracker) error {
...
+		if proof.RefundCoin != nil {
+			log.Errorf("attempted to execute duplicate refund for match %s, side %s, status %s",
+				match.id, dbMatch.Side, dbMatch.Status)
+			continue
+		}
+		contractToRefund := proof.Script
+		var swapCoinID order.CoinID
+		var matchFailureReason string
+		switch {
+		case dbMatch.Side == order.Maker && dbMatch.Status == order.MakerSwapCast:
```
Comment (chappjc) [inline client/core/trade.go:833]: `isRefundable` says this is OK for maker if `dbMatch.Status == order.MakerSwapCast || (dbMatch.Status == order.TakerSwapCast && proof.MakerRedeem == nil)`
https://github.com/decred/dcrdex/pull/401/files#diff-ca928c370ec8b724badec3db0dbd7bc4R506-R507
although the reason in the second part of that `||` would be "not redeeming taker swap".  Do we not want to support that here?

File: client/core/core.go (hunk 5 above)
Comment (chappjc) [reply client/core/core.go]: I think we resolved the server side concerns in matrix (order revocation was a side effect of failing a match, but the individual match was being revoked via `SetMatchInactive`), but please confirm if we need to address something on that end.

Comment (chappjc) [reply client/core/core.go]: Oh, I agree we should add a new `order.MatchStatus` value for failed/revoked.  On the server DB implementation, there are `active BOOLEAN` and `status INT2` columns where a revoked/failed match is identifiable by `NOT active AND status != {MatchComplete flag}`.

And the reason for revoking an order belonging to the party at fault in a failing swap is that if the user is having trouble completing swaps we do not want the order to stay on the books.

Comment (chappjc) [reply client/core/core.go]: grr, I mean't should **not** add a new status value.

File: client/core/trade.go [hunk 16]
```diff
@@ -473,30 +473,88 @@ func (t *trackedTrade) isRedeemable(match *matchTracker) bool {
...
+	dbMatch, _, proof, _ := match.parts()
+	side, status := dbMatch.Side, dbMatch.Status
+
+	// hasRedeemableSwap is true if
+	// - the client is the taker on the match and the status is TakerSwapCast
+	// - the client is the maker on the match, the status is MakerSwapCast OR
+	//   status is TakerSwapCast but Taker's swap has not been redeemed. The
+	//   second case does not prevent Maker from (re-)attempting to redeem
+	//   Taker's swap; it just ensures that Maker's swap is refunded if Taker's
+	//   swap still can't be refunded **after** Maker's locktime expires.
```
Comment (itswisdomagain) [inline client/core/trade.go:501]:
```suggestion
	//   swap still can't be redeemed **after** Maker's locktime expires.
```

File: client/core/trade.go (hunk 15 above)
Comment (itswisdomagain) [reply client/core/trade.go:833]: > Do we not want to support that here?

I'm guessing you mean **Do we ~not~ want to support that here?**

That's something to (re)think about.
I added a reason for doing this here in a comment a little above the referenced LOC:
```
//   The second case does not prevent Maker from (re-)attempting to redeem
//   Taker's swap; it just ensures that Maker's swap is refunded if Taker's
//   swap still can't be redeemed **after** Maker's locktime expires.
```

The idea is, if Maker is unable to redeem Taker's swap for some reason, we should allow Maker sufficient time to re-attempt the redemption. After all, Maker cannot refund their own swap until the locktime expires.
Another thing too is, by the time Maker's swap locktime expires, Taker's swap locktime would have since expired, so I think it would be a fine time to issue a refund to Maker _since_ Maker has been so far unable to redeem Taker's swap. Taker would likely have refunded their swap as well, when their own locktime expired.

File: client/core/core.go (hunk 5 above)
Comment (itswisdomagain) [reply client/core/core.go]: > I think we resolved the server side concerns in matrix (order revocation was a side effect of failing a match, but the individual match was being revoked via `SetMatchInactive` and removed from the `Swapper.matches` map after requesting `'revoke'` acks from both users), but please confirm if we need to address something on that end.

Yeah, server side checks out as discussed in chat. Don't think there's any issue there.

File: client/core/trade.go (hunk 16 above)
Comment (chappjc) [reply client/core/trade.go:501]: Sounds good, although I would remove "still" from that too.

File: client/core/trade.go (hunk 15 above)
Comment (chappjc) [reply client/core/trade.go:833]: Yeah, "Do we not want to support that here?" is a (apparently colloquial) way of saying "This is not supported here, but should it be?".

Anyway, I think I understand the case, but what I'm pointing out is that this function will not allow the maker to refund in that `TakerSwapCast` case where their own maker contract is expired.  What code allows the maker to refund their swap when it is expired regardless of whether the taker's swap is broadcasted?

Comment (itswisdomagain) [reply client/core/trade.go:833]: Oh... I was mixing that up. It should be OK to exec the refund here as well, will fix.
