### PR TITLE
loadbot/zec: Avoid using the same outputs.

### LINKED ISSUE #1683: loadbot/zec: Transactions rejected.
Running with loadbot on master `7d3069112ad3b3aa0f10491657594573c8b38166` 4m/2m locktimes on the zec_btc market.

The compound suite never gets far with the error:
```
2022-06-24 13:11:15.191 [ERR] LOADBOT: exec error (zec) "./alpha": exit status 4: error code: -4
error message:
Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of the wallet and coins were spent in the copy but not marked as spent here.
```

I guess sending funds from alpha to the new wallets.

Some more comments here: https://github.com/decred/dcrdex/pull/1656#issuecomment-1156679602

Full logs:
[zecbtc.txt](https://github.com/decred/dcrdex/files/8973256/zecbtc.txt)

### PR DESCRIPTION
**Pull request by JoeGruffins**
zec will complain about double spends if sendtoaddress is used too soon
    after mining a block. Use a mutex to make sure we always wait a second
    after mining to send.

closes  #1683

### CODE REVIEW

File: dex/testing/dcrdex/harness.sh [hunk 1]
```diff
@@ -149,7 +149,7 @@ if [ $ZEC_ON -eq 0 ]; then
         {
             "base": "ZEC_simnet",
             "quote": "BTC_simnet",
-            "lotSize": 100000000,
+            "lotSize": 1000000,
```
Comment (JoeGruffins) [inline dex/testing/dcrdex/harness.sh:152]: Brought down just to conserve funds.

**Comment by JoeGruffins** [comment]
Just rebased.

**Comment by JoeGruffins** [comment]
Thanks to input from @buck54321 I was able to make this more correct. We just need wait a second after mining a block. 

Related: https://github.com/zcash/zcash/issues/6045

Changes: https://github.com/decred/dcrdex/compare/1137d3212506244d8e67601dc663ecf37ef20005..7633edfa1eea95a3cc09a50ccd6d84942d5b2f4f

**Comment by JoeGruffins** [comment]
I had not noticed before, but eth is adding quotes to addrs it seems, which prevents sending back excess https://github.com/decred/dcrdex/compare/7633edfa1eea95a3cc09a50ccd6d84942d5b2f4f..b524479bc7e5a22d1e016828a3998b09630cc51b

File: dex/testing/loadbot/loadbot.go [hunk 2]
```diff
@@ -101,6 +101,8 @@ var (
 
 	processesMtx = sync.Mutex{}
 	processes    = []*process{}
+
+	zecSendMtx = sync.Mutex{}
```
Comment (chappjc) [inline dex/testing/loadbot/loadbot.go:105]: Since `zecSendMtx` is not guarding a field, it could use a comment like `// prevents sending funds too soon after mining a block...` or something.

**Review by chappjc — APPROVED** [review]
LGTM.  Maybe a comment on the new mutex that doesn't clearly guard a field, but hopefully that goes away soon anyway.

**Comment by JoeGruffins** [comment]
Just rebased.

**Comment by JoeGruffins** [comment]
Hmm, first time to see this `2022-07-07 13:31:34.113 [CRT] MANTLE:CMPD:STACKER:0: Trade error (limit order, sell = true, qty = 5000000, rate = 762000): new order request with DEX server 127.0.0.1:17273 market zec_btc failed: rpc error: error code 36: fee rate for {txid = be0c9bacf6d1d5f1857f0bb088ca5d9ecb080932a26caf0c6ada866ad4d89d03, vout = 1} is too low. 1 < 9
`

**Comment by JoeGruffins** [comment]
Also see `2022-07-07 13:24:04.085 [CRT] MANTLE:CMPD:STACKER:0: Trade error (limit order, sell = true, qty = 3000000, rate = 675000): FundOrder error for zec, funding quantity 3000000 (3 lots): insufficient funds. 0.03 requested, 0.0248358 available` which may be related to sending with a delay now...

File: dex/testing/loadbot/loadbot.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply dex/testing/loadbot/loadbot.go]: Corrected.

Comment (JoeGruffins) [reply dex/testing/loadbot/loadbot.go]: Added a comment.

**Comment by JoeGruffins** [comment]
@chappjc suggestions https://github.com/decred/dcrdex/compare/5c4ee9e40f9c58070cc3cf08b903ea76e81ccda8..925e2bb253aca2cd7fba00f8939156ea8b7c668c

**Comment by chappjc** [comment]
OK, hopefully this is fixed upstream soon.
