### PR TITLE
client/core: fix synchronization issues

### LINKED ISSUE #158: deadlock in client/core TestRegister with -race
in `client/core`, `TestRegister` seems to deadlock with:

    go test -v -race -count 1

### PR DESCRIPTION
**Pull request by buck54321**
Resolves #158

### CODE REVIEW

File: client/core/core.go [hunk 1]
```diff
@@ -854,18 +862,21 @@ func (c *Core) tipChange(assetID uint32, nodeErr error) {
...
 	defer c.waiterMtx.Unlock()
-	for _, w := range c.waiters {
+	for d, w := range c.waiters {
 		waiter := w
 		if waiter.asset.ID != assetID {
 			continue
 		}
+		dex := d
 		go func() {
 			confs, err := waiter.coin.Confirmations()
```
Comment (chappjc) [inline client/core/core.go]: Seems like you could put `defer c.removeWaiter(dex)` as the first line in this goroutine func.

Comment (buck54321) [reply client/core/core.go]: In the case of no error, but too few confirmations, the waiter should remain in the map.

Comment (chappjc) [reply client/core/core.go]: Ah, gotcha.
