### PR TITLE
fix inconsistent wallet sync status

### LINKED ISSUE #1514: btc wallet sync: inconsistent sync status
Steps to reproduce: 
  1. start dexc with a new BTC SPV wallet.
  2. Assuming dcr wallet is all set and reg fee paid. Go markets page and attempt to sell dcr for btc, you get a `btc still syncing. progress=0.XX%` error e.g `0.72%`
  3. While on the wallets page, hover on sync status icon, you get `XX.x%` e.g `72.3%`.
  
  Hard to tell which is the correct sync status
btcsyncing
.

### PR DESCRIPTION
**Pull request by ukane-philemon**
This diff properly formats wallet sync status.
dexsync
Closes #1514

### CODE REVIEW

File: client/core/core.go [hunk 1]
```diff
@@ -4089,7 +4089,7 @@ func (c *Core) prepareTrackedTrade(dc *dexConnection, form *TradeForm, crypter e
 		}
 		if !w.synced {
 			return fmt.Errorf("%s still syncing. progress = %.2f", unbip(w.AssetID),
```
Comment (chappjc) [inline client/core/core.go:4091]: Could include a percent sign. `%.2f%%`

**Review by JoeGruffins — APPROVED** [review]
image

**Comment by JoeGruffins** [comment]
Commit message best practices: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Tense here is good, but usually we do something like `filename: Fix something.` and more info under that header if needed.

**Comment by ukane-philemon** [comment]
> Commit message best practices: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
> 
> Tense here is good, but usually we do something like `filename: Fix something.` and more info under that header if needed.

Thanks for this @JoeGruffins. Nice article.

**Review by buck54321 — APPROVED** [review]

**Review by chappjc — APPROVED** [review]
