### PR TITLE
app: Fix registration flow forms

### LINKED ISSUE #2749: app: Cannot select bond asset
On simnet I start a fresh `dexc` without `dcrdex` being online. I register, then I run `dcrdex`. When I go to select a bond asset, I get the following error: 

Screenshot 2024-04-26 at 7 09 23 PM
 
 It works fine if `dcrdex` is already running then I register.

### PR DESCRIPTION
**Pull request by martonp**
The registration flow didn't take into account the case where an exchange had not yet been added to user.Exchanges. It assumed the exchange would already be view only.

Closes #2749

### CODE REVIEW

File: client/webserver/site/src/js/forms.ts [hunk 1]
```diff
@@ -1092,7 +1090,7 @@ export class FeeAssetSelectionForm {
   }
 
   refresh () {
-    this.setExchange(app().exchanges[this.host])
+    this.setExchange(this.xc)
   }
```
Comment (ukane-philemon) [inline client/webserver/site/src/js/forms.ts:1094]: Information about this exchange might have changed in `app().exchanges` I think.

**Comment by ukane-philemon** [comment]
> The registration flow didn't take into account the case where an exchange had not yet been added to user.Exchanges

whatever call site where we open the affected form can add the exchange to `app().exchanges` until it's eventually updated later?

**Comment by buck54321** [comment]
I had rolled a fix into #2737 already, but I'll merge this first

**Comment by buck54321** [comment]
Oops. Made a conflict.

**Comment by buck54321** [comment]
> I had rolled a fix into #2737 already, but I'll merge this first

Fudge. I merged it.

**Review by buck54321 — APPROVED** [review]
