### PR TITLE
harness: Update eth to work with geth 1.14 and up.

### LINKED ISSUE #3122: harness: Update to work with geth v1.13.x +
Trying on `geth version 1.14.9-stable-c350d3ac` it seems many things are broken. The main problem is:
```
Fatal: Failed to register the Ethereum service: only PoS networks are supported, please transition old ones with Geth v1.13.x
```

This may be a large job. Maybe we cannot use the miner anymore. That messes up a lot of testing utilities we have, and tests.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #3122

Also no longer using the deprecated `personal` namespace

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Does polygon need all the same changes?

**Review by dev-warrior777 — APPROVED** [review]

File: dex/testing/btc/base-harness.sh [hunk 1]
```diff
@@ -114,7 +114,7 @@ tmux send-keys -t $SESSION:0 "${DAEMON} -rpcuser=user -rpcpassword=pass \
   -rpcport=${ALPHA_RPC_PORT} -datadir=${ALPHA_DIR} $(deprecateddbd $ALPHA_DESCRIPTOR_WALLET) \
   -debug=rpc -debug=net -debug=mempool -debug=walletdb -debug=addrman -debug=mempoolrej \
   -whitelist=127.0.0.0/8 -whitelist=::1 \
-  -txindex=1 -regtest=1 -port=${ALPHA_LISTEN_PORT} -fallbackfee=0.00001 \
```
Comment (JoeGruffins) [inline dex/testing/btc/base-harness.sh:117]: On Bitcoin core v28.0.0 for some reason this wasn't using the port anymore. Using bind seems to work...

**Comment by JoeGruffins** [comment]
I was going to update the internal eth nodes, but its adding a toolchain to the go.mod and we didn't want that for some reason. I guess we will have to add it to update though?

**Comment by JoeGruffins** [comment]
The harness just mines whenever there is a transaction, which is unfortunate, but the mining scrip needs to be updated to reflect this. Also some tests in /client/asset/eth are broken still.

**Comment by JoeGruffins** [comment]
Fixing the mining script https://github.com/decred/dcrdex/compare/726f473c18811544c6624b9239ddb78b555fe86f..b983ef294ec3571e685b9751863fc5de947ab172

I also tried setting `--dev.period 10` but for some reason no transactions are mined then. That may be useful for testing if we can figure it out.

File: dex/testing/btc/base-harness.sh (hunk 1 above)
Comment (dev-warrior777) [reply dex/testing/btc/base-harness.sh:117]: Just tried bitcoin core v22-1 and it accepts `-bind=12345` but does not make a listening tcpip port. 

```sh
2024-12-25T07:55:25Z Command-line arg: bind="12345"
2024-12-25T07:55:25Z Command-line arg: server="1"
```
netstat -tl - no new port

`-bind=12345` _does_ make port:

```sh
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:12345              [::]:*                  LISTEN     
```

**Comment by JoeGruffins** [comment]
Fixing tests and apparently gas for token swaps is less now https://github.com/decred/dcrdex/compare/b983ef294ec3571e685b9751863fc5de947ab172..4f832ebf1086d67112a0cae15b7c3a55c65032ae

Also, I had to update to 1.14.12 because `HeaderByNumber` was returning an incorrect header on simnet.

**Review by dev-warrior777 — APPROVED** [review]

**Comment by JoeGruffins** [comment]
It looks like the newest version 1.14.13 does not require the toolchain thing to go.mod

**Comment by JoeGruffins** [comment]
It looks like we must have go 1.22 though https://github.com/decred/dcrdex/compare/ef12c81a71930dd3b6bdf99fa997808390a0a738..758821247746b64667e366415276f05270ef6b9c

File: dex/testing/btc/base-harness.sh (hunk 1 above)
Comment (JoeGruffins) [reply dex/testing/btc/base-harness.sh:117]: So `-bind` does not work on earlier versions?

Comment (dev-warrior777) [reply dex/testing/btc/base-harness.sh:117]: Cannot say all earlier but I suspect so

Comment (dev-warrior777) [reply dex/testing/btc/base-harness.sh:117]: Just did a quiick search on [bitcoin](https://github.com/search?q=repo%3Abitcoin%2Fbitcoin%20-bind&type=code) and it looks a bit more complex ..

Comment (JoeGruffins) [reply dex/testing/btc/base-harness.sh:117]: I'll try just setting both...

**Review by martonp — COMMENTED** [review]
I tried `--dev.period` and it worked for me: b6ba4cd1eb4c182f64659e7de8c728b33514863d

I removed the mine-alpha script as well, since the mining is automatically handled by `geth`. The only issue I had was that it would only mine one transaction per block, and I'm not sure why. The gas ceiling is higher than all of the pending transactions.

File: client/asset/eth/eth_test.go [hunk 2]
```diff
@@ -4927,11 +4927,11 @@ func testMaxSwapRedeemLots(t *testing.T, assetID uint32) {
...
 	} else {
-		if info.MaxSwapsInTx != 20 {
-			t.Fatalf("expected 20 for max swaps but got %d", info.MaxSwapsInTx)
+		if info.MaxSwapsInTx != 24 {
+			t.Fatalf("expected 24 for max swaps but got %d", info.MaxSwapsInTx)
 		}
-		if info.MaxRedeemsInTx != 45 {
-			t.Fatalf("expected 45 for max redemptions but got %d", info.MaxRedeemsInTx)
+		if info.MaxRedeemsInTx != 55 {
+			t.Fatalf("expected 55 for max redemptions but got %d", info.MaxRedeemsInTx)
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply client/asset/eth/eth_test.go:4934]: The values are different on simnet with the changes.

**Comment by JoeGruffins** [comment]
> I tried `--dev.period` and it worked for me: [b6ba4cd](https://github.com/decred/dcrdex/commit/b6ba4cd1eb4c182f64659e7de8c728b33514863d)
> 
> I removed the mine-alpha script as well, since the mining is automatically handled by `geth`. The only issue I had was that it would only mine one transaction per block, and I'm not sure why. The gas ceiling is higher than all of the pending transactions.

Yeah there was some reason the dev.period didnt work out, I think that's why. We can't work with one tx per block can we?

File: dex/networks/eth/params.go [hunk 3]
```diff
@@ -32,8 +32,8 @@ const (
 // These are the chain IDs of the various Ethereum network supported.
 const (
 	MainnetChainID = 1
-	TestnetChainID = 5  // Görli
-	SimnetChainID  = 42 // see dex/testing/eth/harness.sh
+	TestnetChainID = 5    // Görli
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply dex/networks/eth/params.go:35]: changed

File: server/asset/eth/eth.go [hunk 4]
```diff
@@ -145,7 +145,7 @@ func (d *Driver) Setup(cfg *asset.BackendConfig) (asset.Backend, error) {
 	case dex.Testnet:
 		chainID = params.SepoliaChainConfig.ChainID.Uint64()
 	default:
-		chainID = 42
+		chainID = 1337
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply server/asset/eth/eth.go:148]: changed

File: dex/networks/erc20/contracts/TestToken.sol [hunk 5]
```diff
@@ -31,9 +31,15 @@ contract TestToken {
...
-        _balances[0xd12aB7cf72CCf1f3882eC99DDc53CD415635C3bE] = 11000000000000000000000; // delta
+    }
+
+    /**
+     * @dev Set the balance for the sender. Not part of a real erc20 token's
+     * api.
+     */
+    function setSenderBalance(uint256 amt) public virtual returns (bool) {
+        _balances[msg.sender] = amt;
+        return true;
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply dex/networks/erc20/contracts/TestToken.sol:42]: Oh shoot, missed that. Will use it instead.

[the remark this answers is not in the document]
Comment (JoeGruffins) [reply dex/networks/erc20/contracts/TestToken.sol:42]: reverted contract changes and using airdrop

File: dex/testing/eth/harness.sh [hunk 6]
```diff
@@ -242,58 +102,31 @@ tmux send-keys -t $SESSION:0 "cd ${NODES_ROOT}/harness-ctl" C-m
...
-	"$CHAIN_ADDRESS_JSON_FILE_NAME" "$BETA_ADDRESS_JSON" "$BETA_ADDRESS_JSON_FILE_NAME" \
-	"$BETA_NODE_KEY" "snap" "$BETA_AUTHRPC_PORT" "$BETA_HTTP_PORT" "$BETA_WS_PORT" \
-	"$BETA_WS_MODULES"
-
-# Miner
-tmux new-window -t $SESSION:5 -n "miner" $SHELL
-tmux send-keys -t $SESSION:5 "cd ${NODES_ROOT}/harness-ctl" C-m
-tmux send-keys -t $SESSION:5 "watch -n 15 ./mine-alpha 1" C-m
-
 sleep 1
```
[the remark this answers is not in the document]
Comment (JoeGruffins) [reply dex/testing/eth/harness.sh:109]: done

**Comment by JoeGruffins** [comment]
Reverted the test contract changes, fix most of martons review topics, also removing mining from the loadbot setup. The extra mining seems to be causing problems for geth and its not necessary in my opinion. https://github.com/decred/dcrdex/compare/a9b7a67d37daa752b7849579eb4c22e9aaf9ee22..6c261a4d1b727e0cfe0ba869a5814760eb600cdd

Still using the mining script in the eth harness because we can't do with one tx per block that dev.period seems to force.

**Comment by martonp** [comment]
> Yeah there was some reason the dev.period didnt work out, I think that's why. We can't work with one tx per block can we?

I think it's fine, generally we won't have more than 1 tx per block, and it's more realistic than immediately mining a block only when there is a transaction. I'm pretty sure we're doing something wrong though.. I don't think dev.period would have this restriction. I've messed with the gas ceiling and wasn't able to get it to work.

**Comment by JoeGruffins** [comment]
The loadbot will produce many txn per second, and I use that alot. We can always adjust the scripts manually to meet our needs I suppose. I will look into if I am implementing this wrong. I haven't found anything yet about it only being 1 tx per block googling around. Unsure yet if that's by design.

**Comment by JoeGruffins** [comment]
There`s some time dilation going on. The longer the dev node runs, the further the header's time drifts into the future. This means any contracts based off of local time will eventually be expired before created based on the chain's time. May be due to the fast blocks.

Prints from where we watch blocks:
```
block 92 header time 2025-02-07 18:36:28 +0900 JST my time 2025-02-07 18:35:27.463838776 +0900 JST
block 829 header time 2025-02-07 18:49:14 +0900 JST my time 2025-02-07 18:45:22.460241287 +0900 JST
```

File: dex/testing/loadbot/mantle.go [hunk 7]
```diff
@@ -71,6 +72,7 @@ func runTrader(t Trader, name string) {
 	}
 
 	maintain := true
+	time.Sleep(time.Second * 16) // at least a block for reg funds
```
Comment (JoeGruffins) [inline dex/testing/loadbot/mantle.go:75]: Need to also listen for ctx.Done here

**Comment by JoeGruffins** [comment]
@martonp its working now with dev.period! apparently you were right and I just needed to remove more args from the config file. https://github.com/decred/dcrdex/compare/7dfded390ae2f3efc40da0aee62851e5139d61e3..4be0e134a9a175b6fff069c320c36e3155199ec0

File: dex/testing/loadbot/mantle.go (hunk 7 above)
Comment (JoeGruffins) [reply dex/testing/loadbot/mantle.go]: done

**Review by martonp — APPROVED** [review]
LGTM
