### PR TITLE
comms: extend test wait times.

### LINKED ISSUE #450: server/comms/test: noresponse send error
Go CI 1.13 test failure.

log:
```
 ok  	decred.org/dcrdex/server/coinlock	1.788s
--- FAIL: TestOnline (0.92s)
    comms_test.go:708: noresponse send error: write tcp 127.0.0.1:44728->127.0.0.1:33797: write: connection reset by peer
FAIL
FAIL	decred.org/dcrdex/server/comms	1.203s
ok  	decred.org/dcrdex/server/db	1.746s
```

@chappjc comment:
> It looks like the pingPeriod might be too fast or the pongWait too short vs pingPeriod in comms_test.go for the CI machines. 90 ms is a terribly fast ping period so I wouldn't be surprised if these pathetic CI machines just freeze for longer than that for no apparent reason. Otherwise I don't know why the conn write would have gotten connection reset by peer there.

If memory serves correctly, all of these sleep/wait related issues happen in 1.13. No hard evidence that this is causal, just an observation.

### PR DESCRIPTION
**Pull request by dnldd**
This extends test wait times to prevent timeouts on slow machines.

Resolves  #450

### CODE REVIEW

File: server/comms/comms_test.go [hunk 1]
```diff
@@ -610,7 +610,7 @@ func TestOnline(t *testing.T) {
 
 	keyPath := filepath.Join(tempDir, "rpc.key")
 	certPath := filepath.Join(tempDir, "rpc.cert")
-	pongWait = 100 * time.Millisecond
```
Comment (chappjc) [inline server/comms/comms_test.go:613]: Only thing with this is that we have a three-ping sleep down here: https://github.com/decred/dcrdex/pull/493/files#diff-a19499504b77f7a1f4e6498dbb82929cR707-R708, so it's in our interest to reduce that to a couple pings (@buck54321 I was never really sure why waiting for more than one ping was needed, can you clarify?) or maybe settle on a 500ms pong wait instead.

Comment (buck54321) [reply server/comms/comms_test.go:613]: I was probably being sloppy around the edges. 2 pings at 500 ms seems better.
