### PR TITLE
client/dcr: Remove GetRawTransaction.

### LINKED ISSUE #2947: dcr: rpc wallet needs `--txindex` with v1.0.0
After updating a mainnet node that is using an rpc wallet connected to a dcrd node, I see this:

`2024-09-04 05:21:06.227 [ERR] CORE[dcr]: error identifying transaction: GetRawTransaction error: -32603: the transaction index must be enabled to query the blockchain (specify --txindex)`

This was not required before.

### PR DESCRIPTION
**Pull request by JoeGruffins**
GetRawTransaction will error if txindex is not specified on the node, and until now GetTransaction has been good enough for client.

Until 12a90a7fbd we were only using `GetRawTransaction` for mempool redemptions, which it will not error for https://github.com/decred/dcrd/blob/7735cbb4e11b61636e88ad07e9ad8c1a30dd4047/internal/rpcserver/rpcserver.go#L2899

closes #2947

### CODE REVIEW

**Comment by JoeGruffins** [comment]
I will fix tests if these changes look like the right direction. They may take a little work.

File: client/asset/dcr/dcr.go [hunk 1]
```diff
@@ -3787,12 +3779,12 @@ func (dcr *ExchangeWallet) findRedemptionsInMempool(contractOutpoints []outPoint
 	}
 
 	for _, txHash := range mempoolTxs {
-		tx, err := dcr.wallet.GetRawTransaction(dcr.ctx, txHash)
```
Comment (buck54321) [inline client/asset/dcr/dcr.go:3790]: Doesn't `getrawtransaction` work for mempool transaction even if `txindex` is not enabled?

Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:3790]: Yes, for mempool transactions.

Should we leave it in with a note that it can only be used for mempool?

My reasoning is that if `GetTransaction` is good enough for rpc clients with an spv node, then it's good enough for full nodes.

Comment (dev-warrior777) [reply client/asset/dcr/dcr.go:3790]: Just to note for testing: the dcr **simnet** test harness node alpha _has_ `--txindex`; node beta does _not_ have a tx index.

Comment (JoeGruffins) [reply client/asset/dcr/dcr.go:3790]: beta wallet is also an --spv wallet so I dont think we have a simnet wallet connecting to beta node

**Comment by JoeGruffins** [comment]
Ill work on fixing the tests.

File: client/asset/dcr/dcr_test.go [hunk 2]
```diff
@@ -4654,7 +4655,7 @@ func TestFindBond(t *testing.T) {
 	}, {
 		name:    "bad msgtx",
 		coinID:  bond.CoinID,
-		txRes:   txFn(nil, bond.SignedTx[1:]),
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr_test.go:4657]: I have not idea why I had to change this, maybe I should.

**Review by buck54321 — APPROVED** [review]
