### PR TITLE
server/asset: Check if txindex is enabled.

### LINKED ISSUE #1535: server/dcr: Preemptively check for --txindex.
Recently, I set up a testnet server and forgot to run dcrd with the `--txindex` flag. The server asset started up fine and there was no problem until a user tried to pay the registration fee. This caused the error: `[WRN] AUTH: Unexpected error checking fee coin confirmations: -32603: The transaction index must be enabled to query the blockchain (specify --txindex)`

If possible, it would be better to error at start-up when transaction indexing is not enabled to avoid problems after the server has already been started.

The `getinfo` rpc command does provide a way to check:
```
$ dcrctl getinfo
{
  "version": 1080000,
  "protocolversion": 8,
  "blocks": 889610,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 31.33877036,
  "testnet": true,
  "relayfee": 0.0001,
  "errors": "",
  "addrindex": false,
  "txindex": true
}
```

### PR DESCRIPTION
**Pull request by ukane-philemon**
This diff:
1. checks if  `-txindex` is enabled for bitcoind 
2. checks if  `--txindex` is enabled for dcrd.
Closes #1535

### CODE REVIEW

File: server/asset/btc/rpcclient.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ const (
 	methodGetTxOut          = "gettxout"
 	methodGetRawTransaction = "getrawtransaction"
 	methodGetBlock          = "getblock"
+	methodGetIndexInfo      = "getindexinfo"
```
Comment (chappjc) [inline server/asset/btc/rpcclient.go:25]: Since this method was [introduced in Bitcoin Core v0.21](https://bitcoincore.org/en/releases/0.21.0/#new-rpcs), that officially breaks support for v0.20, which people still use.  It also is a problem for other forks of Bitcoin Core (e.g. Litecoin 0.18) that don't have this either.

This could be resolved in different ways.  Simplest is to just log a warning, which may or may not be seen by the operator.  We could detect a "method not found" error and ignore the error.  More complete would be to check the version like we do on client side.

**Review by chappjc — CHANGES_REQUESTED** [review]

**Review by JoeGruffins — APPROVED** [review]

File: server/asset/btc/btc.go [hunk 2]
```diff
@@ -254,6 +254,25 @@ func (btc *Backend) Connect(ctx context.Context) (*sync.WaitGroup, error) {
...
+		}
+		// Ignore and log err if getindexinfo method is not found.
+		// getindexinfo method is not currently supported by
+		// pre 0.21 versions of bitcoind, and some forks of
+		// bitcoin core (litecoin).
+		txindex = true
+		btc.log.Warnf("The getindexinfo RPC is unavailable for %s. Please ensure txindex is enabled in the node config.", btc.name)
+	}
+
+	if !txindex {
```
Comment (chappjc) [inline server/asset/btc/btc.go:271]: Combine into an `else if` and remove the `txindex = true` in the `err != nil` branch above.

In fact, I would suggest limiting scope of the `txindex` variable like

```go
if txindex, err := btc.node.CheckTxIndex(); err != nil {
```

**Review by chappjc — CHANGES_REQUESTED** [review]
Looks good. One last logic clean up please

**Comment by ukane-philemon** [comment]
@chappjc thanks for the review, all changes applied.

File: server/asset/btc/rpcclient.go [hunk 3]
```diff
@@ -75,6 +76,25 @@ func (rc *RPCClient) GetBlockChainInfo() (*GetBlockchainInfoResult, error) {
 	return chainInfo, nil
 }
 
+// TxIndexResult models the data returned from the getindexinfo command
+// for txindex.
+// TxIndexResult.Txindex is nil if the returned data is an empty json object.
+type TxIndexResult struct {
```
Comment (buck54321) [inline server/asset/btc/rpcclient.go:82]: Doesn't need to be exported.

File: server/asset/btc/rpcclient.go [hunk 4]
```diff
@@ -75,6 +76,25 @@ func (rc *RPCClient) GetBlockChainInfo() (*GetBlockchainInfoResult, error) {
...
+	TxIndex *struct{} `json:"txindex"`
+}
+
+// CheckTxIndex checks if bitcoind transaction index is enabled.
+func (rc *RPCClient) CheckTxIndex() (bool, error) {
```
Comment (buck54321) [inline server/asset/btc/rpcclient.go:87]: Doesn't need to be exported.

**Review by buck54321 — APPROVED** [review]
