### PR TITLE
dcr: work around ticket purchase bug

### LINKED ISSUE #2496: staking,ui: fix ticket purchasing for n > 1
See [various notes in `(*spvWallet).PurchaseTickets`](https://github.com/decred/dcrdex/blob/1b79545ab5af6adacb1a3bb295169a8807328244/client/asset/dcr/spv.go#L904-L953). 

1. What is the reason that we can only send n < num_utxos? Is it related to privacy?
2. Why does looping result in a double spend? Outputs are apparently not being locked or the lock is being ignored. Is that a bug?
3. Absent a dcrwallet change, we may need to do asynchronous ticket purchasing. That might be absolutely necessary anyway, once mixing is implemented. #2492 helps with that.

### PR DESCRIPTION
**Pull request by buck54321**
Implement a ticket queue to work around a known bug where fewer tickets than requested are purchased without error.

Show number of queued tickets on front end.

Closes #2496

### CODE REVIEW

File: client/asset/dcr/dcr.go [hunk 1]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
+		return
+	}
+	sinfo, err := dcr.wallet.StakeInfo(dcr.ctx)
+	if err != nil {
+		dcr.log.Errorf("StakeInfo error: %v", err)
+		dcr.emit.Data(ticketDataRoute, &TicketPurchaseUpdate{Err: err.Error()})
+		return
 	}
+	if dcrutil.Amount(bal.Available) < sinfo.Sdiff*dcrutil.Amount(remain) {
+		dcr.log.Errorf("Insufficient balance %s to purches %d ticket at price %s: %v", dcrutil.Amount(bal.Available), remain, sinfo.Sdiff)
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr.go:5222]:
```
2023-11-17 05:05:30.709 [ERR] CORE[dcr]: Insufficient balance 0 DCR to purches 990 ticket at price 0.0002 DCR: %!v(MISSING)
```

The last %v doesn't have an error.

Also, this was waiting for confs so tried a second time. I think returning at line 5205 prevents this.
```
2023-11-17 05:05:30.709 [TRC] CORE[dcr]: Attempting to purchase 990 tickets
2023-11-17 05:05:30.709 [TRC] CORE: Processing tip change for dcr
2023-11-17 05:05:30.709 [ERR] CORE[dcr]: Insufficient balance 0 DCR to purches 990 ticket at price 0.0002 DCR: %!v(MISSING)
2023-11-17 05:05:34.041 [DBG] CORE[btc]: tip change: 454 (33cb50bc8c3379bd6443e4cbef3611b1a3c665d6506dbb6246632d147dac929c) => 455 (0b42f1dd56b0a8a5e76bb68e34bb9c984a44f9c6d15b4aebb716a05a7a3bb6f0)
2023-11-17 05:05:34.041 [TRC] CORE: Processing tip change for btc
2023-11-17 05:05:34.041 [TRC] CORE[btc][SPV]: Bals: spendable = 0 BTC (0 BTC trusted, 0 BTC untrusted, 0 BTC assumed locked), immature = 0 BTC
2023-11-17 05:05:46.281 [DBG] CORE[dcr]: tip change: 651 (31900f90988e23659ec301bcf5f39bc98eabfea389babff7dfe79b91412ce0ad) => 652 (b97d6ba3f36a6e589d33e84f4c09eb9f2254add1bbbbbfbc1be334bdfb5d0704)
2023-11-17 05:05:46.281 [TRC] CORE: Processing tip change for dcr
2023-11-17 05:05:46.281 [TRC] CORE[dcr]: Attempting to purchase 990 tickets
2023-11-17 05:05:46.281 [ERR] CORE[dcr]: Insufficient balance 0 DCR to purches 990 ticket at price 0.0002 DCR: %!v(MISSING)
```

File: client/asset/dcr/dcr.go [hunk 2]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
+		}
+		if tx.Confirmations > 0 {
+			delete(tb.unconfirmedTickets, txHash)
+		} else {
+			unconf++
+		}
+	}
+	if unconf > 0 {
+		ok = true
+		dcr.log.Tracef("Skipping ticket purchase attempt because there are still %d unconfirmed tickets", unconf)
```
Comment (JoeGruffins) [inline client/asset/dcr/dcr.go:5204]: Should return here to skip?

**Review by JoeGruffins — APPROVED** [review]
Working well.

File: client/asset/dcr/dcr.go [hunk 3]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
 	}
-	vInfo := v.(*vsp)
-	return dcr.wallet.PurchaseTickets(dcr.ctx, n, vInfo.URL, vInfo.PubKey)
+	purchased := int32(len(tickets))
+	remain = tb.remaining.Add(-purchased)
+	// sanity check
+	if remain < 0 {
+		remain = 0
+		tb.remaining.Store(remain)
+	}
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/asset/dcr/dcr.go:5250]: I think we can play safe by using a mtx on the ticketBuyer struct.

File: client/asset/dcr/dcr.go [hunk 4]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
+	if tb.unconfirmedTickets == nil {
+		tb.unconfirmedTickets = make(map[chainhash.Hash]struct{})
+	}
+
+	remain := tb.remaining.Load()
+	if remain < 1 {
+		return
+	}
+
+	var unconf int
```
Comment (itswisdomagain) [inline client/asset/dcr/dcr.go:5188]: Don't really need this variable. Can get unconfirmed count later via `len(tb.unconfirmedTickets)`.

File: client/asset/dcr/dcr.go [hunk 5]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
+		dcr.emit.Data(ticketDataRoute, &TicketPurchaseUpdate{Err: err.Error()})
+		return
+	}
+	sinfo, err := dcr.wallet.StakeInfo(dcr.ctx)
+	if err != nil {
+		dcr.log.Errorf("StakeInfo error: %v", err)
+		dcr.emit.Data(ticketDataRoute, &TicketPurchaseUpdate{Err: err.Error()})
+		return
 	}
+	if dcrutil.Amount(bal.Available) < sinfo.Sdiff*dcrutil.Amount(remain) {
```
Comment (itswisdomagain) [inline client/asset/dcr/dcr.go:5221]: If it can purchase less than `remain`, shouldn't we? I think we should purchase as many as we can before failing.

File: client/asset/dcr/dcr.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/asset/dcr/dcr.go:5250]: Another idea is to use `atomic.Uint32` instead of `atomic.Int32`. The former won't allow a negative value, right?

File: client/asset/dcr/dcr.go [hunk 6]
```diff
@@ -5119,28 +5126,142 @@ func (dcr *ExchangeWallet) SetVSP(url string) error {
...
+		return errors.New("not connected, login first")
 	}
 	// I think we need to set this, otherwise we probably end up with default
 	// of DefaultRelayFeePerKb = 1e4 => 10 atoms/byte.
 	feePerKB := dcrutil.Amount(dcr.feeRateWithFallback(feeSuggestion) * 1000)
 	if err := dcr.wallet.SetTxFee(dcr.ctx, feePerKB); err != nil {
-		return nil, fmt.Errorf("error setting wallet tx fee: %w", err)
+		return fmt.Errorf("error setting wallet tx fee: %w", err)
+	}
+
```
Comment (martonp) [inline client/asset/dcr/dcr.go:5142]: If you check check for insufficient balance over here and return an error the UI could show insufficient balance instead of a check mark first and then immediately fail after.

File: client/asset/dcr/dcr.go (hunk 1 above)
Comment (martonp) [inline client/asset/dcr/dcr.go:5222]:
```suggestion
		dcr.log.Errorf("Insufficient balance %s to purchase %d ticket at price %s: %v", dcrutil.Amount(bal.Available), remain, sinfo.Sdiff)
```

**Review by martonp — COMMENTED** [review]
Working nicely. I think the UI would be a bit nicer with immediate failure if the balance is too low though.

**Comment by JoeGruffins** [comment]
This closes #2496 ?

File: client/asset/dcr/dcr.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (buck54321) [reply client/asset/dcr/dcr.go:5250]: It's just a sanity check. I really don't think the mutex is worth it.

File: client/asset/dcr/dcr.go (hunk 6 above)
Comment (buck54321) [reply client/asset/dcr/dcr.go:5142]: We can't really calculate exact fees, but we can apply a simpler filter. On it.

**Review by martonp — APPROVED** [review]
