### PR TITLE
core: fix wallet creation sequence

### LINKED ISSUE #235: core: wrong password error is unrecoverable
If you enter the wrong password during wallet creation, you get an error message, but attempting to enter the correct password results in a "wallet already exists" error and there's no way to get things right. 

The wallet password should be checked before the wallet is stored.

### PR DESCRIPTION
**Pull request by buck54321**
Resolves #235

Moves `xcWallet` from *types.go* to *wallet.go*.

### CODE REVIEW

File: client/core/core.go [hunk 1]
```diff
@@ -577,10 +584,6 @@ func (c *Core) loadWallet(dbWallet *db.Wallet) (*xcWallet, error) {
 	}
 	wallet.Wallet = w
 	wallet.connector = dex.NewConnectionMaster(w)
-
-	c.walletMtx.Lock()
-	c.wallets[dbWallet.AssetID] = wallet
-	c.walletMtx.Unlock()
 	return wallet, nil
```
Comment (buck54321) [inline client/core/core.go:587]: Decision to store the wallet is up to the caller now.

File: client/core/wallet.go [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+	}
+	w.mtx.Lock()
+	w.lockTime = time.Now().Add(dur)
+	w.mtx.Unlock()
+	return nil
+}
+
+// lock the wallet, setting the lockTime to the time when the wallet will be
+// locked.
+func (w *xcWallet) Lock() error {
```
Comment (buck54321) [inline client/core/wallet.go:43]: I think the only thing changed about `xcWallet` is that I've exported the `Lock` method. It's a method of the embedded type, and having a `lock` method and a `Lock` method makes it possible to bypass the `lockTime` handling by mistake. This change is meant to prevent that, and to bring consistency with the `Unlock` method, which already did this.

File: client/webserver/api.go [hunk 3]
```diff
@@ -137,23 +137,6 @@ func (s *WebServer) apiNewWallet(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 	s.notifyWalletUpdate(form.AssetID)
-	type response struct {
-		OK     bool   `json:"ok"`
-		Locked bool   `json:"locked"`
-		Msg    string `json:"msg"`
-	}
-	err = s.core.OpenWallet(form.AssetID, form.AppPW)
-	if err != nil {
```
Comment (buck54321) [inline client/webserver/api.go:146]: This is handled in `CreateWallet` now.

File: client/core/wallet.go [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+		return err
+	}
+	w.mtx.Lock()
+	w.lockTime = time.Now().Add(dur)
+	w.mtx.Unlock()
+	return nil
+}
+
+// lock the wallet, setting the lockTime to the time when the wallet will be
+// locked.
```
Comment (chappjc) [inline client/core/wallet.go:42]: I know it hasn't changed, but the comment is a bit confusing since it's setting `lockTime` to the zero `time.Time` value for the purposes of having `time.(Time).After(now)` always return true in `unlocked` and `state`.  Seems like the current comment is describing what `Unlock` does.

`Lock` cap.

File: client/core/core.go [hunk 5]
```diff
@@ -531,15 +528,20 @@ func (c *Core) CreateWallet(appPW, walletPW string, form *WalletForm) error {
 		return fmt.Errorf(s, a...)
 	}
 
+	err = wallet.Unlock(walletPW, aYear)
+	if err != nil {
+		return initErr("%s wallet authentication error: %v", unbip(assetID), err)
```
Comment (chappjc) [inline client/core/core.go:533]: Again not a change in this PR, but should `xcWallet` have a `Disconnect` method (for `initErr` to call) so that `xcWallet.hookedUp` can get set to `false`?
