### PR TITLE
client: fix missing settings button for erc20 tokens

### LINKED ISSUE #2040: ui: wallet settings button (and disable button in that view) missing for ERC20 tokens

### PR DESCRIPTION
**Pull request by vctt94**
closes #2040.

I am always showing the settings button for tokens now, even though they don't have configopts defined. This way it is possible to enable or disable and export them.

### CODE REVIEW

**Comment by vctt94** [comment]
Thanks for the review Marton. Changed for your proposed solution and I believe it makes more sense.

**Review by JoeGruffins — APPROVED** [review]

File: client/webserver/site/src/js/wallets.ts [hunk 1]
```diff
@@ -636,8 +636,11 @@ export default class WalletsPage extends BasePage {
 
       const walletDef = app().walletDefinition(assetID, wallet.type)
       page.walletType.textContent = walletDef.tab
+      Doc.show(page.reconfigureBox)
       const configurable = assetIsConfigurable(assetID)
-      if (configurable) Doc.show(page.reconfigureBox)
+      // if it is not configurable, we do not show the password form.
+      if (configurable) Doc.show(page.passwordWrapper)
```
Comment (martonp) [inline client/webserver/site/src/js/wallets.ts:642]:
``` javascript
Doc.setVis(configurable, page.passwordWrapper)
```

File: client/webserver/site/src/js/wallets.ts [hunk 2]
```diff
@@ -636,8 +636,11 @@ export default class WalletsPage extends BasePage {
 
       const walletDef = app().walletDefinition(assetID, wallet.type)
       page.walletType.textContent = walletDef.tab
+      Doc.show(page.reconfigureBox)
```
Comment (martonp) [inline client/webserver/site/src/js/wallets.ts:639]: I don't think you need to explicitly show this. Just remove `page.reconfigureBox` from the `Doc.hide` above.

**Review by martonp — APPROVED** [review]

**Review by chappjc — APPROVED** [review]
utACK.  In the absence of a token wallet definition with any configopts (which is the case presently), hiding the Submit button is the right move so that `showReconfig` is accessible and shows the disable button among other things.

**Review by buck54321 — APPROVED** [review]
