### PR TITLE
multi: connect response includes active orders

### LINKED ISSUE #597: retire orders where the preimage request failed
If a client submits an order, but fails to provide the preimage when epoch processing takes place, the order never leaves "epoch" status.  For sure in client/Core, the order hangs around, not getting retired.  There may be changes needed on the server as well... needs investigation.

### PR DESCRIPTION
**Pull request by itswisdomagain**
**server/auth**: return list of active orders with `connect` response (will follow up with spec update)

**client/core**:
- Log error and issue notification for active orders reported by DEX that are
 unknown to the client.
- Update order statuses where server-reported statuses are different from statuses
 recorded by client.
- Retrieve correct status using the order_status route for orders considered active by
 the client but not returned by the DEX in the connect response.
- Delete stale cancel orders if their target orders are returned as active in the connect
 response.

Resolves #597.

### CODE REVIEW

**Comment by itswisdomagain** [comment]
Converting this to draft to allow #687 go in first, as the new order_status route will find good uses here.

File: client/core/trade_simnet_test.go [hunk 1]
```diff
@@ -330,6 +347,305 @@ func testMakerGhostingAfterTakerRedeem(t *testing.T) {
...
+// - Non-standing order, preimage revealed, "missed" nomatch or match request (if
+//   matched).
+// - Expect order status to stay at Epoch status before going AWOL and to become
+//   Executed after re-connecting the DEX, even if the order was matched and the
+//   matches got revoked due to client inaction.
+// Order 3:
+// - Standing order, partially matched, booked, revoked due to inaction on a
+//   match.
+// - Expect order status to be Booked before going AWOL and to become Revoked
+//   after re-connecting the DEX. Locked coins should be returned.
```
Comment (itswisdomagain) [inline client/core/trade_simnet_test.go:369]: These simulated and tested scenarios are 3 of the 4 scenarios documented in the table in https://github.com/decred/dcrdex/pull/648#issuecomment-688585289 where coins may remain needlessly locked.

**Comment by itswisdomagain** [comment]
The last 2 commits are to enable me test with the order_status feature (cherry-picked the commit from #687). Will likely get edited a little bit more and force-pushed before this will be ready for review. I expect #687 will go in and I'll rebase this branch over the updated master before this becomes ready for review.

**Comment by itswisdomagain** [comment]
I'm satisfied with the workings of this branch as is. I was able to simulate some of the problematic conditions described in https://github.com/decred/dcrdex/pull/648#issuecomment-688585289 using the webserver on master branch and get decent but incomplete resolution without the order_status route and complete resolution with the order_status route. Details below:

Master branch
--------
2 clients, each with 2 orders stuck at an incorrect status and had funds locked.
 - **Client 1, Problem Order 1**: Limit order, not matched and became booked. Client received nomatch request and set the status to Booked. Client went offline and the order got matched while client was away. Match got revoked due to client inaction (client was maker) and the order got revoked. revoke_order messages are not currently sent for revoked orders and even if they were, client would have missed the message. Order got stucked at status Booked with funds locked.
 - **Client 1, Problem Order 2**: Limit order, not matched and became booked. Client submitted cancel order, sent preimage for the cancel order but missed the cancel match message. Order was canceled on the server but client is unaware. Order got stucked at status Booked with funds locked.
 - **Client 2, Problem Order 1**: Market order, client went offline _before_ sending preimage. Order got revoked without client knowing. _{Clients are currently not informed of orders revoked due to reimage misses. If the client was unable or unwilling to send the preimage, no reason to expect the client to properly handle an order revoked message.}_ Order got stuck at status Epoch with funds locked.
 - **Client 2, Problem Order 2**: Market order, client went offline _after_ sending preimage. Order wasn't matched, became Executed but client missed the nomatch message. Order got stuck at status Epoch with funds locked.
master_1
master_2

Testing resolution with 87b781cb311c47c9de0643d341e335fed6d422fd (connect response includes active orders + order.PreimageRevealed)
--------
 - **Client 1, Problem Order 1**: Resolved against active orders in connect response, became Revoked ✅ 
 - **Client 1, Problem Order 2**: Resolved against active orders in connect response, became Canceled ☑️ (with guess work, assumed order was canceled because `t.cancel != nil`).
 - **Client 2, Problem Order 1**: Resolved against active orders in connect response, became Executed ❌ ( 87b781cb311c47c9de0643d341e335fed6d422fd assumes preimage was sent for all orders, so market order with preimage sent = Executed)
 - **Client 2, Problem Order 2**: Resolved against active orders in connect response, became Executed ✅ 
- All stuck orders retired, locked funds returned.
<details>
<summary>Reconcilation logs</summary>

```
Client 1 Logs:
2020-09-16 23:36:07.086 [INF] CORE: loaded 2 incomplete orders
2020-09-16 23:36:07.114 [DBG] CORE: Authenticated connection to 127.0.0.1:40, 0 active orders, 0 active matches
2020-09-16 23:36:07.114 [DBG] CORE: Order cd638decba73c0d3c8586abd1f31278a8263af2bef24cf9281b20d71b2e1a290 updated from recorded status epoch to inactive status canceled
2020-09-16 23:36:07.114 [DBG] CORE[dcr]: returning coins [8fe6dd46f34f85e03195851f7cca7616ca60f78f1d38c84efe71d3a37726f96b:0]
2020-09-16 23:36:07.115 [DBG] CORE: Authenticated connection to localhost:40, 0 active orders, 0 active matches
2020-09-16 23:36:07.115 [DBG] CORE: Order ec53001d3cc11a121dfbc003ace830d2c4b9cad5237da7a1b25d1d6626e2fdf7 updated from recorded status booked to inactive status revoked
2020-09-16 23:36:07.115 [DBG] CORE[btc]: returning coins [64260e5ab227f99d6cc1b7b02702099a9cf403c91f1392e9e43ffb8ad1acad17:1]
2020-09-16 23:36:07.119 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-16 23:36:07.120 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-16 23:36:12.052 [INF] CORE: Retiring inactive order cd638decba73c0d3c8586abd1f31278a8263af2bef24cf9281b20d71b2e1a290 in status canceled
2020-09-16 23:36:12.055 [TRC] CORE: notify: |DATA| (balance) balance updated
2020-09-16 23:36:12.056 [INF] CORE: Retiring inactive order ec53001d3cc11a121dfbc003ace830d2c4b9cad5237da7a1b25d1d6626e2fdf7 in status revoked
2020-09-16 23:36:12.060 [TRC] CORE: notify: |DATA| (balance) balance updated

Client 2 Logs:
2020-09-16 23:36:58.127 [INF] CORE: loaded 2 incomplete orders
2020-09-16 23:36:58.146 [DBG] CORE: Authenticated connection to 127.0.0.1:40, 0 active orders, 0 active matches
2020-09-16 23:36:58.146 [DBG] CORE: Authenticated connection to localhost:40, 0 active orders, 0 active matches
2020-09-16 23:36:58.146 [DBG] CORE: Order e0ef5cf0fd8ee598d0c13155ca405311aa4af74d421243eb8890d94f711098f2 updated from recorded status epoch to inactive status executed
2020-09-16 23:36:58.146 [DBG] CORE[btc]: returning coins [bc83c5fea01a9bea526a4716618f7b45331d7b710136e42d55f86f86ddbecca2:1]
2020-09-16 23:36:58.146 [DBG] CORE: Order 11c3390f2150cb87f87f1c02399d58d32f7a23482d6d306266743c4cf068af7d updated from recorded status epoch to inactive status executed
2020-09-16 23:36:58.146 [DBG] CORE[dcr]: returning coins [c6343b6837b1d8eab0fa6aee57ffd836f19a1f2a8693d5756e65a09b3c5bab51:1]
2020-09-16 23:36:58.149 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-16 23:36:58.150 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-16 23:37:00.249 [INF] CORE: Retiring inactive order e0ef5cf0fd8ee598d0c13155ca405311aa4af74d421243eb8890d94f711098f2 in status executed
2020-09-16 23:37:00.253 [TRC] CORE: notify: |DATA| (balance) balance updated
2020-09-16 23:37:00.257 [INF] CORE: Retiring inactive order 11c3390f2150cb87f87f1c02399d58d32f7a23482d6d306266743c4cf068af7d in status executed
2020-09-16 23:37:00.259 [TRC] CORE: notify: |DATA| (balance) balance updated
```

</details>
connect_orders_1
connect_orders_2

Testing resolution with a729612f106a254c777dc30fc93284a58eac2979 (connect response includes active orders - order.PreimageRevealed + order_status)
--------
- **Client 1, Problem Order 1**: Resolved against active orders in connect response, became Revoked ✅ 
- **Client 1, Problem Order 2**: Resolved against active orders in connect response, became Canceled ✅ 
- **Client 2, Problem Order 1**: Resolved against active orders in connect response, became Revoked ✅ 
- **Client 2, Problem Order 2**: Resolved against active orders in connect response, became Executed ✅ 
- All stuck orders retired, locked funds returned.
<details>
<summary>Reconcilation logs</summary>

```
Client 1 Logs:
2020-09-17 02:26:07.506 [INF] CORE: loaded 2 incomplete orders
2020-09-17 02:26:07.548 [DBG] CORE: Authenticated connection to 127.0.0.1:40, 0 active orders, 0 active matches
2020-09-17 02:26:07.549 [DBG] CORE: Authenticated connection to localhost:40, 0 active orders, 0 active matches
2020-09-17 02:26:07.549 [DBG] CORE: Requesting order status for 1 trades from DEX 127.0.0.1:40
2020-09-17 02:26:07.549 [DBG] CORE: Requesting order status for 1 trades from DEX localhost:40
2020-09-17 02:26:07.579 [DBG] CORE: Order cd638decba73c0d3c8586abd1f31278a8263af2bef24cf9281b20d71b2e1a290 updated from recorded status epoch to new status canceled reported by DEX 127.0.0.1:40
2020-09-17 02:26:07.579 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-17 02:26:07.581 [DBG] CORE: Order ec53001d3cc11a121dfbc003ace830d2c4b9cad5237da7a1b25d1d6626e2fdf7 updated from recorded status booked to new status revoked reported by DEX localhost:40
2020-09-17 02:26:07.581 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-17 02:26:21.179 [INF] CORE: Retiring inactive order cd638decba73c0d3c8586abd1f31278a8263af2bef24cf9281b20d71b2e1a290 in status canceled
2020-09-17 02:26:21.180 [INF] CORE: Retiring inactive order ec53001d3cc11a121dfbc003ace830d2c4b9cad5237da7a1b25d1d6626e2fdf7 in status revoked
2020-09-17 02:26:21.180 [DBG] CORE[btc]: returning coins [64260e5ab227f99d6cc1b7b02702099a9cf403c91f1392e9e43ffb8ad1acad17:1]
2020-09-17 02:26:21.180 [DBG] CORE[dcr]: returning coins [8fe6dd46f34f85e03195851f7cca7616ca60f78f1d38c84efe71d3a37726f96b:0]
2020-09-17 02:26:21.186 [TRC] CORE: notify: |DATA| (balance) balance updated
2020-09-17 02:26:21.187 [TRC] CORE: notify: |DATA| (balance) balance updated

Client 2 Logs:
2020-09-17 02:28:33.108 [INF] CORE: loaded 2 incomplete orders
2020-09-17 02:28:33.131 [DBG] CORE: Authenticated connection to 127.0.0.1:40, 0 active orders, 0 active matches
2020-09-17 02:28:33.131 [DBG] CORE: Authenticated connection to localhost:40, 0 active orders, 0 active matches
2020-09-17 02:28:33.131 [DBG] CORE: Requesting order status for 1 trades from DEX 127.0.0.1:40
2020-09-17 02:28:33.131 [DBG] CORE: Requesting order status for 1 trades from DEX localhost:40
2020-09-17 02:28:33.140 [DBG] CORE: Order 11c3390f2150cb87f87f1c02399d58d32f7a23482d6d306266743c4cf068af7d updated from recorded status epoch to new status executed reported by DEX 127.0.0.1:40
2020-09-17 02:28:33.140 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-17 02:28:33.142 [DBG] CORE: Order e0ef5cf0fd8ee598d0c13155ca405311aa4af74d421243eb8890d94f711098f2 updated from recorded status epoch to new status revoked reported by DEX localhost:40
2020-09-17 02:28:33.142 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2020-09-17 02:28:44.340 [INF] CORE: Retiring inactive order 11c3390f2150cb87f87f1c02399d58d32f7a23482d6d306266743c4cf068af7d in status executed
2020-09-17 02:28:44.341 [DBG] CORE[dcr]: returning coins [c6343b6837b1d8eab0fa6aee57ffd836f19a1f2a8693d5756e65a09b3c5bab51:1]
2020-09-17 02:28:44.340 [INF] CORE: Retiring inactive order e0ef5cf0fd8ee598d0c13155ca405311aa4af74d421243eb8890d94f711098f2 in status revoked
2020-09-17 02:28:44.341 [DBG] CORE[btc]: returning coins [bc83c5fea01a9bea526a4716618f7b45331d7b710136e42d55f86f86ddbecca2:1]
2020-09-17 02:28:44.346 [TRC] CORE: notify: |DATA| (balance) balance updated
2020-09-17 02:28:44.347 [TRC] CORE: notify: |DATA| (balance) balance updated
```

</details>
connect_orders+order_status_1
connect_orders+order_status_2

**Comment by itswisdomagain** [comment]
I'm gonna leave this as is for now until #687 goes in, then I'll clean it up and mark ready for review.

**Comment by chappjc** [comment]
Excellent analysis and summary of resolutions in that table.  Certainly seems like the proper resolution is w/o the PreimageRevealed flag (although the v1 OrderProof "soft upgrade" was a clever approach) - no db scheme changes, and correct status updates.

I'm pretty happy happy with PR #687 , and looking at this a bit it looks like querying for status of *cancel* orders may not be needed.  Thoughts about that?  We do still need to deal with cancel orders in epoch status, even if indirectly (checking the status of the targeted order instead).

**Comment by itswisdomagain** [comment]
Iirc, the only reason a cancel order will not get matched to the target order is if the cancel order's preimage was not sent or if the target order gets completely matched before the cancel order is processed.

If that's correct, we can infer the final status of the cancel order without querying for it:
- REVOKED: If the target order is returned with the connect response, implying the target order is NEITHER executed nor canceled. If the target order is still booked, the cancel order's preimage was not sent.
- EXECUTED: If the target order is NOT returned with the connect response, implying the target order is EITHER executed or canceled. We already query the status for such orders using the order_status route, so we'll know if the target order is executed or canceled. That will help determine if the cancel order was matched or unmatched.

Make sense?

**Comment by chappjc** [comment]
Client can also disappear after providing the cancel order's preimage, but before getting a match/nomatch back.  Has happened several times.  But even in this case it sounds like we can make the same inferences.

**Comment by itswisdomagain** [comment]
Right. We won't need to rely on the match/nomatch to determine the status of the cancel order. We just need to know the current status of the target order, if the target order is canceled, we know we missed a match request on the cancel order. If the target order is executed, we missed the preimage request _or_ the nomatch request for the cancel order.

Reading that again, looks like we can't completely infer. If the target order is executed, it could be that the cancel order's preimage was not received and the target order went on to match completely; or it was received but the target order got executed before the cancel order was processed.

**Comment by itswisdomagain** [comment]
We can safely retire stale cancel orders anyway, but we would need the order_status route to account for cancel orders if we want to know the final status of the cancel order.

Basically, we retire the cancel order if the target order
- is no longer booked (now executed, revoked or canceled)
- is booked but the cancel order's epoch ended a while ago.

The second case allows the client to submit another cancel order if they wish. The second case also means the cancel order was revoked.

**Comment by chappjc** [comment]
I want to say that we don't care what the cancel order status is as long as we know what happened with the trade, but I have a feeling that's going to haunt us.  That said, I'm ok with moving forward with https://github.com/decred/dcrdex/pull/687 without the ability to query cancel order statuses directly.  We can modify that behavior as needed.

**Comment by itswisdomagain** [comment]
Marking this as ready for review. Feature complete now, just want to push another commit that refactors the db methods and types used in preparing the active orders for the connect response and the order_status response.

File: server/auth/auth.go [hunk 2]
```diff
@@ -892,17 +911,20 @@ func (auth *AuthManager) handleConnect(conn comms.Link, msg *msgjson.Message) *m
...
+		log.Errorf("handleConnect prepare response error: %v", err)
 		return &msgjson.Error{
 			Code:    msgjson.RPCInternalError,
 			Message: "internal error",
 		}
 	}
 	err = conn.Send(respMsg)
 	if err != nil {
+		log.Errorf("handleConnect send response error: %v", err)
 		log.Error("error sending connect response: " + err.Error())
```
Comment (itswisdomagain) [inline server/auth/auth.go:928]: hmm, was probably debugging with this.

File: client/core/core_test.go [hunk 3]
```diff
@@ -2714,6 +2728,243 @@ func TestTradeTracking(t *testing.T) {
...
+			dc.trades[tracker.ID()] = tracker
+			if tracker.cancel != nil {
+				pendingCancel = tracker
+			}
+		}
+		dc.tradeMtx.Unlock()
+
+		if pendingCancel != nil {
+			// Canceling the order again should fail.
+			rig.queueCancel(nil)
```
Comment (itswisdomagain) [inline client/core/core_test.go:2883]: The cancel route should not get hit, so this is at best unnecessary, at worst, potentially problematic.

File: client/core/core_test.go [hunk 4]
```diff
@@ -2714,6 +2728,243 @@ func TestTradeTracking(t *testing.T) {
...
+		if pendingCancel != nil {
+			pendingCancel.mtx.RLock()
+			status, stillHasCancelOrder := pendingCancel.metaData.Status, pendingCancel.cancel != nil
+			pendingCancel.mtx.RUnlock()
+			if status == order.OrderStatusBooked {
+				if stillHasCancelOrder {
+					t.Fatalf("%s: expected stale cancel order to be deleted for now-booked order", tt.name)
+				}
+				// Cancel order deleted. Canceling the order again should succeed.
+				rig.queueCancel(nil)
```
Comment (itswisdomagain) [inline client/core/core_test.go:2933]: This should be unnecessary, given the previously queued cancel response. If that previously queued response was used, this would return a `no response queued` error which will expose the fact that the previous cancel attempt visited the cancel route.

File: client/core/trade.go [hunk 5]
```diff
@@ -527,6 +527,48 @@ func (t *trackedTrade) counterPartyConfirms(match *matchTracker) (have, needed u
...
+// if their preimages was not sent. We cannot currently tell whether the cancel
+// order's preimage was revealed, so assume that the cancel order is Executed
+// but unmatched. Consider adding a order.PreimageRevealed field to ensure that
+// the correct final status is set for the cancel order.
+//
+// This method MUST be called with the trackedTrade mutex lock held for writes.
+func (t *trackedTrade) deleteStaleCancelOrder() {
+	if t.cancel == nil {
+		return
+	}
```
Comment (itswisdomagain) [inline client/core/trade.go:547]: Should also check that this trade's status is still Epoch / Booked. Cancel orders are currently not deleted from Executed / Revoked or Canceled orders; and they don't need to be deleted.

File: client/core/core_test.go (hunk 3 above)
Comment (itswisdomagain) [reply client/core/core_test.go:2883]: Allowing this queued response to ensure that the error returned here is the expected error and not a `response not queued for route` error. The queued response should actually only be served later in this tests and will error then if it was already served here.

File: server/db/driver/pg/orders.go [hunk 6]
```diff
@@ -1285,30 +1217,50 @@ func loadTradeFromTable(dbe *sql.DB, fullTable string, oid order.OrderID) (order
...
+	orders, err := userOrdersFromTable(ctx, a.db, fullTable, aid, oids)
 	if err != nil && !errors.Is(err, sql.ErrNoRows) {
-		return nil, nil, err
+		return nil, err
+	}
+
+	if len(oids) > 0 && len(oids) == len(orders) {
+		// found all requested orders
+		return orders, nil
+	}
```
Comment (JoeGruffins) [inline server/db/driver/pg/orders.go:1239]: I'm not sure at all, but would it be possible for len to be the same but oids to differ?

File: client/core/core.go [hunk 7]
```diff
@@ -591,6 +591,137 @@ func (dc *dexConnection) compareServerMatches(srvMatches map[order.OrderID]*serv
...
+	for oid, trade := range knownActiveTrades {
+		serverMsgOrder := serverMsgOrders[oid]
+		if serverMsgOrder == nil {
+			// Order not returned by server. Must be inactive now.
+			// Request current status from the DEX.
+			orderStatusRequests = append(orderStatusRequests, &msgjson.OrderStatusRequest{
+				Base:    trade.Base(),
+				Quote:   trade.Quote(),
+				OrderID: oid[:],
+			})
```
Comment (itswisdomagain) [inline client/core/core.go:664]: I've not quite figured it out yet, but there's a problem here. If appending more than 1 request, the value of the last appended request overrides the values of all previously appended requests. I'm constantly seeing 3 items in the slice but all with same value as the last appended item. So instead of getting statuses for 3 orders, I only get for one. Will push a fix once I figure it out.

**Review by JoeGruffins — COMMENTED** [review]
Simnet tests stopped twice in the same place:
```
--- FAIL: TestOrderStatusReconciliation (283.01s)
    trade_simnet_test.go:641: status not updated for client 2 order b9617f72b6cf122d796c9e01d509ccd750a86877629dd618f4d87266ff9abd88, expected revoked, got epoch
```

File: client/core/core.go (hunk 7 above)
Comment (itswisdomagain) [reply client/core/core.go]: Turns out it was because I was using the loop variable oid. Replaced with trade.ID().Bytes() and now all good. Still wondering why it's safe to use the second loop variable (trade) but not oid.

File: server/db/driver/pg/orders.go (hunk 6 above)
Comment (itswisdomagain) [reply server/db/driver/pg/orders.go:1239]: I don't think so, if len(oids) > 0, then those oids are used in the select query, so if equal-length orders are returned, it should match those oids.

**Comment by itswisdomagain** [comment]
@JoeGruffins simnet issue should be fixed now. Noticed it a while ago and just force-pushed 😬 the fix. Didn't think anyone had eyes on this yet.

File: server/db/driver/pg/orders.go (hunk 6 above)
Comment (JoeGruffins) [reply server/db/driver/pg/orders.go:1239]: ok, that makes sense

File: client/core/core.go [hunk 8]
```diff
@@ -2430,9 +2561,23 @@ func (c *Core) authDEX(dc *dexConnection) error {
...
+	if unknownOrdersCount > 0 {
+		details := fmt.Sprintf("%d active orders reported by %s were not found.",
+			unknownOrdersCount, dc.acct.host)
+		c.notify(newDEXAuthNote("DEX reported unknown orders", dc.acct.host, false, details, db.Poke))
+	}
+	if reconciledOrdersCount > 0 {
+		details := fmt.Sprintf("Statuses updated for %d orders.", reconciledOrdersCount)
+		c.notify(newDEXAuthNote("Orders reconciled with DEX", dc.acct.host, false, details, db.Poke))
+	}
+
```
Comment (buck54321) [inline client/core/core.go:2580]: I'm going to bring it up in Element, and I ran into this problem when implementing `match_status`, but hooking in here to resolve status conflicts is not great, because the server may have cached messages coming that would naturally resolve the conflicts.

**Review by buck54321 — COMMENTED** [review]
Just a cursory look with some questions and suggestions.

File: client/core/trade.go [hunk 9]
```diff
@@ -527,6 +527,50 @@ func (t *trackedTrade) counterPartyConfirms(match *matchTracker) (have, needed u
...
+	if t.cancel == nil || t.metaData.Status != order.OrderStatusBooked {
+		log.Debugf("ignoring delete cancel order attempt for order %v in status with pending cancel = %v",
+			t.ID(), t.metaData.Status, t.cancel != nil)
+		return
+	}
+
+	stamp := t.cancel.ServerTime
+	epoch := order.EpochID{Idx: encode.UnixMilliU(stamp) / t.epochLen, Dur: t.epochLen}
+	epochEnd := epoch.End()
+	if time.Since(epochEnd) < 15*time.Minute {
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/trade.go:554]: Sounds good to me. I think I got the 15 minutes idea from @chappjc, didn't ask if he had a rational for it.

File: dex/msgjson/types.go [hunk 10]
```diff
@@ -845,9 +841,18 @@ func (c *Connect) Serialize() []byte {
 	return append(s, uint64Bytes(c.Time)...)
 }
 
+// Order describes an order, its status and fill, and is returned as part of a
+// ConnectResult or as part of a OrderStatusResult.
+type Order struct {
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply dex/msgjson/types.go:846]: I wanted to avoid `OrderStatusResult` because the `connect` response returns this type as well. Now that I read your comment, I think `OrderStatus` works fine. The `OrderStatusResult` is def. not necessary. Added that just to read better.

File: server/db/driver/pg/orders.go [hunk 11]
```diff
@@ -987,26 +937,45 @@ func (a *Archiver) UpdateOrderFilled(ord *order.LimitOrder) error {
 	return a.UpdateOrderFilledByID(ord.ID(), ord.Base(), ord.Quote(), int64(ord.Trade().Filled()))
 }
 
-// UserOrders retrieves all orders for the given account in the market specified
-// by a base and quote asset.
-func (a *Archiver) UserOrders(ctx context.Context, aid account.AccountID, base, quote uint32) ([]order.Order, []order.OrderStatus, error) {
+// AllActiveUserOrders retrieves all active orders for a user across all
+// markets.
+func (a *Archiver) AllActiveUserOrders(aid account.AccountID) ([]*db.Order, error) {
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply server/db/driver/pg/orders.go:942]: Will rename to `db.OrderStatus`

File: client/core/core.go [hunk 12]
```diff
@@ -591,6 +591,137 @@ func (dc *dexConnection) compareServerMatches(srvMatches map[order.OrderID]*serv
...
+		trade.mtx.RUnlock()
+	}
+	dc.tradeMtx.RUnlock()
+
+	updateOrder := func(trade *trackedTrade, msgOrder *msgjson.Order) {
+		reconciledOrdersCount++
+		oid := trade.ID()
+		previousStatus := trade.metaData.Status
+		newStatus := order.OrderStatus(msgOrder.Status)
+		trade.Trade().SetFill(msgOrder.Fill)
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/core.go:640]: Well, the server is also the entity that provides the match info we need to set the fill client-side currently. As long as we have the server signing these messages, shouldn't we be safe? We're also relying on / blindly accepting the order status from the server, if the server wants to play games with the client, the server can do that with the status returned alone, i.e. if we decide to not return the fill.

Although I do have a concern with the client potentially not having details for some matches relating to the order that would have made this fill amount update necessary. If the client has all the matches for the order (even in wrong statuses, which can be corrected with the coming match_status work), the client can calculate and set the fill amount appropriately without requiring this info from the server.

An example to illustrate my above concern is an Epoch limit order getting partially matched while the client is away, client misses the match request, the match gets revoked while client is away say due to maker (the other user) inaction, client's order gets booked, and on reconnect, we're setting the fill to 30% but without any match info to back it up.

**Comment by chappjc** [comment]
Can rebase and resolve with 699 in

**Comment by JoeGruffins** [comment]
simnet test still failing in the same place for me. It definitely passes for you?

**Comment by itswisdomagain** [comment]
It was passing until recently. I now see a `[ERR] CORE: notify: |ERROR| (dex_auth) DEX auth error - 127.0.0.1:17273: 'connect' error: rpc error: error code 7: DB error` before the test fails. Investigating.

**Comment by chappjc** [comment]
`status-integ` is advanced and it says there are conflicts, but it's just whitespace making github fussy.  Worth a rebase anyway.

**Comment by chappjc** [comment]
Still failing for me at `trade_simnet_test.go:631: status not updated for client 2 order ab6568957defb85e522eb372542c92248a0ac60c22b5d6b3210e51561100113f, expected revoked, got epoch`

File: client/core/trade.go [hunk 13]
```diff
@@ -527,6 +527,50 @@ func (t *trackedTrade) counterPartyConfirms(match *matchTracker) (have, needed u
...
+// status for 2 or more epochs after the close of the cancel order's epoch.
+// Deleting the stale cancel order from this trade makes it possible for the
+// client to re-attempt cancelling the order.
+//
+// NOTE:
+// Stale cancel orders would be Executed if their preimage was sent or Revoked
+// if their preimages was not sent. We cannot currently tell whether the cancel
+// order's preimage was revealed, so assume that the cancel order is Executed
+// but unmatched. Consider adding a order.PreimageRevealed field to ensure that
+// the correct final status is set for the cancel order.
```
Comment (chappjc) [inline client/core/trade.go:541]: "Consider adding a order.PreimageRevealed field to ensure that the correct final status is set for the cancel order"
...or allow the server to check status of cancel orders.

File: client/core/trade.go [hunk 14]
```diff
@@ -527,6 +527,50 @@ func (t *trackedTrade) counterPartyConfirms(match *matchTracker) (have, needed u
...
+		log.Debugf("Ignoring delete cancel order attempt for order %v, status %v, pending cancel = %v",
+			t.ID(), t.metaData.Status, t.cancel != nil)
+		return
+	}
+
+	stamp := t.cancel.ServerTime
+	epoch := order.EpochID{Idx: encode.UnixMilliU(stamp) / t.epochLen, Dur: t.epochLen}
+	epochEnd := epoch.End()
+	if time.Since(epochEnd).Milliseconds() < int64(2*t.epochLen) {
+		return // not stuck, yet
```
Comment (chappjc) [inline client/core/trade.go:555]: should `deleteStaleCancelOrder` be called during tick then?

File: client/core/trade.go [hunk 15]
```diff
@@ -527,6 +527,50 @@ func (t *trackedTrade) counterPartyConfirms(match *matchTracker) (have, needed u
...
+
+	log.Infof("Cancel order %v in epoch status with server time stamp %v, epoch end %v (%v ago) considered executed and unmatched.",
+		t.cancel.ID(), t.cancel.ServerTime, epochEnd, time.Since(epochEnd))
+
+	err := t.db.LinkOrder(t.ID(), order.OrderID{})
+	if err != nil {
+		log.Errorf("DB error unlinking cancel order %s for trade %s: %w", t.cancel.ID(), t.ID(), err)
+	}
+	// Clearing the trackedCancel allows this order to be canceled again.
+	t.cancel = nil
```
Comment (chappjc) [inline client/core/trade.go:566]: What if the dexConnection is just down and the trade has been canceled?  Can that happen?  If it does, would the actually-cancelled trade just be reconciled on connect?

**Comment by chappjc** [comment]
A couple of races:

```
==================
WARNING: DATA RACE
Write at 0x00c0012ba1b0 by goroutine 86:
  runtime.mapassign()
      /home/jon/go115/src/runtime/map.go:571 +0x0
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation.func4()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:485 +0x844
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x94

Previous write at 0x00c0012ba1b0 by goroutine 67:
  ??()
      -:0 +0xffffffffffffffff
  go.etcd.io/bbolt.(*Tx).Commit()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:185 +0x3aa
  go.etcd.io/bbolt.(*DB).Update()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:701 +0x17d
  go.etcd.io/bbolt.(*DB).Update-fm()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:677 +0x4b
  decred.org/dcrdex/client/db/bolt.(*BoltDB).withBucket()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:1141 +0xd6
  decred.org/dcrdex/client/db/bolt.(*BoltDB).walletsUpdate()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:1039 +0xb5
  decred.org/dcrdex/client/db/bolt.(*BoltDB).UpdateBalance()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:975 +0xdb
  decred.org/dcrdex/client/core.(*Core).walletBalances()
      /home/jon/github/decred/dcrdex/client/core/core.go:1045 +0x3b9
  decred.org/dcrdex/client/core.(*Core).updateBalances()
      /home/jon/github/decred/dcrdex/client/core/core.go:1080 +0x12a
  decred.org/dcrdex/client/core.(*Core).updateAssetBalance()
      /home/jon/github/decred/dcrdex/client/core/core.go:1092 +0x469
  decred.org/dcrdex/client/core.(*Core).Trade()
      /home/jon/github/decred/dcrdex/client/core/core.go:2206 +0x3ce
  decred.org/dcrdex/client/core.(*tClient).placeOrder()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:1245 +0x5a6
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation.func3()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:435 +0xbe
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x94

Goroutine 86 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x73
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:458 +0x91b
  testing.tRunner()
      /home/jon/go115/src/testing/testing.go:1127 +0x202

Goroutine 67 (finished) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x73
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:432 +0x7b1
  testing.tRunner()
      /home/jon/go115/src/testing/testing.go:1127 +0x202
==================
==================
WARNING: DATA RACE
Write at 0x00c0012ba1e0 by goroutine 86:
  runtime.mapassign()
      /home/jon/go115/src/runtime/map.go:571 +0x0
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation.func4()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:486 +0x8b3
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x94

Previous write at 0x00c0012ba1e0 by goroutine 67:
  ??()
      -:0 +0xffffffffffffffff
  go.etcd.io/bbolt.(*Tx).Commit()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:185 +0x3aa
  go.etcd.io/bbolt.(*DB).Update()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:701 +0x17d
  go.etcd.io/bbolt.(*DB).Update-fm()
      /home/jon/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:677 +0x4b
  decred.org/dcrdex/client/db/bolt.(*BoltDB).withBucket()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:1141 +0xd6
  decred.org/dcrdex/client/db/bolt.(*BoltDB).walletsUpdate()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:1039 +0xb5
  decred.org/dcrdex/client/db/bolt.(*BoltDB).UpdateBalance()
      /home/jon/github/decred/dcrdex/client/db/bolt/db.go:975 +0xdb
  decred.org/dcrdex/client/core.(*Core).walletBalances()
      /home/jon/github/decred/dcrdex/client/core/core.go:1045 +0x3b9
  decred.org/dcrdex/client/core.(*Core).updateBalances()
      /home/jon/github/decred/dcrdex/client/core/core.go:1080 +0x12a
  decred.org/dcrdex/client/core.(*Core).updateAssetBalance()
      /home/jon/github/decred/dcrdex/client/core/core.go:1092 +0x469
  decred.org/dcrdex/client/core.(*Core).Trade()
      /home/jon/github/decred/dcrdex/client/core/core.go:2206 +0x3ce
  decred.org/dcrdex/client/core.(*tClient).placeOrder()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:1245 +0x5a6
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation.func3()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:435 +0xbe
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x94

Goroutine 86 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x73
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:458 +0x91b
  testing.tRunner()
      /home/jon/go115/src/testing/testing.go:1127 +0x202

Goroutine 67 (finished) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /home/jon/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x73
  decred.org/dcrdex/client/core.TestOrderStatusReconciliation()
      /home/jon/github/decred/dcrdex/client/core/trade_simnet_test.go:432 +0x7b1
  testing.tRunner()
      /home/jon/go115/src/testing/testing.go:1127 +0x202
==================
```

File: server/db/driver/pg/orders.go [hunk 16]
```diff
@@ -1009,6 +959,119 @@ func (a *Archiver) UserOrders(ctx context.Context, aid account.AccountID, base,
...
+// in the specified market.
+func (a *Archiver) UserOrderStatuses(aid account.AccountID, base, quote uint32, oids []order.OrderID) ([]*db.OrderStatus, error) {
+	marketSchema, err := a.marketSchema(base, quote)
+	if err != nil {
+		return nil, err
+	}
+
+	// Active orders.
+	fullTable := fullOrderTableName(a.dbName, marketSchema, true)
+	activeOrderStatuses, err := a.userOrderStatusesFromTable(fullTable, aid, oids)
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply server/db/driver/pg/orders.go:977]: So we reject requests exceeding this cap? Or we query the db in batches?

File: server/auth/auth.go [hunk 17]
```diff
@@ -1243,20 +932,20 @@ func (auth *AuthManager) handleOrderStatus(conn comms.Link, msg *msgjson.Message
...
 			return msgjson.NewError(msgjson.RPCInternalError, "DB error")
 		}
-		for _, order := range orderStatuses {
-			results = append(results, &msgjson.OrderStatusResult{
-				OrderID: order.ID.Bytes(),
-				Status:  uint16(order.Status),
-				Fill:    order.Fill,
+		for _, orderStatus := range orderStatuses {
+			results = append(results, &msgjson.OrderStatus{
+				OrderID: orderStatus.OrderID.Bytes(),
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply server/auth/auth.go:946]: It was actually ID, can't recall why I changed it to OrderID but can easily revert that change.

File: client/core/trade.go (hunk 14 above)
Comment (itswisdomagain) [reply client/core/trade.go:555]: Perhaps, but an important prerequisite for the `deleteStaleCancelOrder` method is that the target order must be in status Booked. We're definitely sure of the status of orders after processing the connect response; but we could be wrong at other times. Specifically, if the cancel order's preimage/match/nomatch request was missed while connected to the DEX, it's possible that the target order's status has changed unknown to the client; and we might be wrong to delete the cancel order.

The way I see this working reliably from tick, is add a `hasStaleCancelOrder` method, collect the order ids of all trackedTrades that have stale cancel orders, request their current statuses from the DEX and only delete the stale cancel orders if the order_status response indicates that the target orders are still booked.

Having this done only on connect is still fine to me as it is a recovery measure, which I think should be better left for the dex authentication/connection procedure.

Anyways, the thought of being able to perform order status reconciliation without waiting for a DEX reconnect had come to mind. It'd be a case for #685, as that already lays the foundation for order status reconciliation during tick. Just need to plug in the order_status route and **core** will be quicker to notice stuck/stale orders and request status updates.

File: client/core/trade.go (hunk 15 above)
Comment (itswisdomagain) [reply client/core/trade.go:566]: My reply to your previous comment answers this somewhat. We currently only clear stale cancel orders **after** the server reports the targeted orders as active (Epoch/Booked status) in the connect response.

File: server/db/driver/pg/orders.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply server/db/driver/pg/orders.go:977]: Seems like the query can handle a lot though. I modified the `orders_online_test` to search for millions of oids and only got a out of memory error at 5 million oids. The oids did not exist in the db however, don't know if that makes a difference.

I'm retesting with having thousands/millions of orders in the db and running this query with all the oids and see where there's a bottleneck.

**Comment by itswisdomagain** [comment]
> Still failing for me at `trade_simnet_test.go:631: status not updated for client 2 order ab6568957defb85e522eb372542c92248a0ac60c22b5d6b3210e51561100113f, expected revoked, got epoch`

I'm getting this again, and I know why. I reduced the wait-before-reconnect time to just `BroadcastTimeout+2 Seconds`, which is cutting it close as inaction checks kick in after `BroadcastTimeout`. In one test case, I saw from the dcrdex logs that the last order was revoked 12 seconds after the client reconnected, so when the client reconnected, the server still had the order booked.

File: server/db/driver/pg/orders.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply server/db/driver/pg/orders.go:977]: I modified the `orders_online_test : TestUserOrderStatuses` to save 100,002 records to db. The tests run 3 queries, the first expects 100,000 matches, the second returns 2 matches and the third returns no matches. All worked as expected without issues. Looks like if we're adding a limit to this route, it'll be just to prevent really excessive calls.

File: client/core/core.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/core.go]: It's more just about having a single definition for the fill value. If the definition is "the sum value of all known matches", then that's what it should be. It shouldn't be "Either the sum of all known matches, or whatever the server told us, depending on what happened last".

File: server/db/driver/pg/orders.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (chappjc) [reply server/db/driver/pg/orders.go:977]: k, how about 10k then?  If many people do it at once it could be an attack vector.

File: client/core/trade.go (hunk 14 above)
Comment (chappjc) [reply client/core/trade.go:556]: Ok, we can let this reconciliation be for reconnect for now.

**Review by buck54321 — CHANGES_REQUESTED** [review]

File: server/db/driver/pg/orders.go [hunk 18]
```diff
@@ -1009,6 +959,119 @@ func (a *Archiver) UserOrders(ctx context.Context, aid account.AccountID, base,
...
+}
+
+// Pass nil or empty oids to return statuses for all user orders in the
+// specified table.
+func (a *Archiver) userOrderStatusesFromTable(fullTable string, aid account.AccountID, oids []order.OrderID) ([]*db.OrderStatus, error) {
+	execQuery := func(ctx context.Context) (*sql.Rows, error) {
+		if len(oids) == 0 {
+			stmt := fmt.Sprintf(internal.SelectUserOrderStatuses, fullTable)
+			return a.db.QueryContext(ctx, stmt, aid)
+		}
```
[the remark this answers is not in the document]
Comment (chappjc) [reply server/db/driver/pg/orders.go:1035]: You mean drop the active orders list in the connect response?

[the remark this answers is not in the document]
Comment (buck54321) [reply server/db/driver/pg/orders.go:1035]: Whoops. I was looking at it in terms of the `order_status` request, and thinking that the user could request their entire history by providing no order IDs, and they can request all **active** orders by providing no order IDs (which is out of spec), but they would never get to the archived orders in `UserOrderStatuses`. Should probably have `(*AuthManager).handleOrderStatus` check for empty order ID slice and reject the request.

File: client/core/core.go [hunk 19]
```diff
@@ -591,6 +591,138 @@ func (dc *dexConnection) compareServerMatches(srvMatches map[order.OrderID]*serv
...
+	for _, srvOrderStatus := range srvOrderStatuses {
+		var oid order.OrderID
+		copy(oid[:], srvOrderStatus.ID)
+		if _, tracked := dc.trades[oid]; tracked {
+			srvActiveOrderStatuses[oid] = srvOrderStatus
+		} else {
+			log.Warnf("Unknown order %v reported by DEX %s as active", oid, dc.acct.host)
+			unknownOrdersCount++
+		}
+	}
```
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/core.go:624]: It's logged in this method, just below:
```
knownActiveTrades := make(map[order.OrderID]*trackedTrade)
for oid, trade := range dc.trades {
	trade.mtx.RLock()
	if trade.metaData.Status == order.OrderStatusEpoch || trade.metaData.Status == order.OrderStatusBooked {
		knownActiveTrades[oid] = trade
	} else if srvOrderStatus := srvActiveOrderStatuses[oid]; srvOrderStatus != nil {
		log.Warnf("Inactive order %v, status %s reported by DEX %s as active, status %s",
			oid, trade.metaData.Status, dc.acct.host, order.OrderStatus(srvOrderStatus.Status))
	}
	trade.mtx.RUnlock()
}
```

[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/core.go:624]: Oh yeah. Ignore me.

File: client/core/core.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (itswisdomagain) [reply client/core/core.go]: I see the fill value as the amount we know to be filled; and we typically gather this value from match requests sent by the server. If there are other ways to determine the value, I have no objection to it. Unless, like you say, if it is `the sum value of all known matches`, then we only set fill based on known matches. I think I'm okay either direction. Any preference?

[the remark this answers is not in the document]
Comment (buck54321) [reply client/core/core.go]: Simpler is better. 1 fewer field and 1 fewer definition to track is my preference. Should also avoid accepting the server as a source of truth. It wouldn't be terrible to check the server's reported fill value against our own just for verification and logging purposes, but it's hard to justify the extra field just for logging. I really think we should just remove the field from `msgjson.OrderStatus` until we find a compelling reason to include it.

**Comment by JoeGruffins** [comment]
Still the failure for simnet test.
```
--- FAIL: TestOrderStatusReconciliation (160.60s)
    trade_simnet_test.go:650: status not updated for client 2 order 83d1ee4bc7f7007383e976d1a3b2449860678205ccc5b919beb2f49e8dbb363a, expected revoked, got epoch
FAIL
exit status 1
FAIL    decred.org/dcrdex/client/core   402.266s
[joe@hyrule core]$ git log
commit ecbb7ac3669d2ec446b6e1fb241ca716580078ad (HEAD -> 677)
Author: Wisdom Arerosuoghene <wisdom.arerosuoghene@gmail.com>
Date:   Tue Sep 29 00:39:26 2020 +0100

    validate order_status requests
```

**Comment by itswisdomagain** [comment]
@JoeGruffins, I think it might be a timing issue for your tests. Can you check if your dcrdex logs show the order getting revoked _after_ the tests fail? If so, try increasing the wait-before-reconnect timeout [here](https://github.com/itswisdomagain/dcrdex/blob/ecbb7ac3669d2ec446b6e1fb241ca716580078ad/client/core/trade_simnet_test.go#L626-L631) and let's see if that gets the tests passing for you. I'm cutting it a little close there with 2*bTimeout but I expect that should be enough time for the server to detect and revoke orders for at-fault matches.

Also a good idea to restart the dcrdex harness between tests to prevent previous orders on the book messing up the test.

Btw, I've recently only ran the `TestOrderStatusReconciliation` test specifically using `go test ./client/core -v -tags harness -race -run "TestOrderStatusReconciliation" -count 1`. See if that works for you?

**Review by buck54321 — APPROVED** [review]

**Review by chappjc — APPROVED** [review]
My review items are addressed.

But the core's harness tests still fail for me:

```
trade_simnet_test.go:650: status not updated for client 2 order 6109169027aa12cbebf71c815727613b4649639407a94cca70196d5f04b081ff, expected revoked, got epoch
...
--- FAIL: TestOrderStatusReconciliation (162.28s)
```

@JoeGruffins and I both consistently have trouble with the tests, but we'll have to continue investigating on the `status-integ` branch when this is merged.  To merge `status-integ` with `master`, we will have another PR for that, on which we can test again.

**Comment by chappjc** [comment]
Going to merge since code looks good and `TestOrderStatusReconciliation` **does pass** when run alone (`-run TestOrderStatusReconciliation`), but we need to identify the reason for it's failure when the entire core harness test suite is run.
