### PR TITLE
core: Fix swap/redemption fee info

### LINKED ISSUE #1814: frontend reports same fees for both swap/redeem assets
image

The from/swap asset is correct, but the to/redeem asset's fees is just the other value.

### PR DESCRIPTION
**Pull request by martonp**
Previously, swap fees were displayed in place of redemption fees. Also, for tokens, the token asset was displayed as the fee asset instead of the parent. Both of these issues are fixed. Also, in the exported orders CSV, two new columns are added, one for the base asset's fee asset, and one for the quote asset's fee asset.

Closes #1814

### CODE REVIEW

File: client/core/helpers.go [hunk 1]
```diff
@@ -38,6 +40,34 @@ func (ord *OrderReader) ToSymbol() string {
...
+
+// BaseFeeSymbol is the symbol of the asset used to pay the base asset's
+// network fees.
+func (ord *OrderReader) BaseFeeSymbol() string {
+	return ord.BaseFeeUnitInfo.Conventional.Unit
+}
+
+// QuoteFeeSymbol is the symbol of the asset used to pay the quote asset's
+// network fees.
+func (ord *OrderReader) QuoteFeeSymbol() string {
```
Comment (LasTshaMAN) [inline client/core/helpers.go:67]: maybe use these funcs to simplify `FromFeeSymbol` and `FromFeeSymbol` a bit

File: client/core/helpers.go [hunk 2]
```diff
@@ -303,17 +333,17 @@ func (ord *OrderReader) AverageRateString() string {
...
+	return formatQty(ord.FeesPaid.Swap, ord.QuoteFeeUnitInfo)
 }
 
 // RedemptionFeesString is a formatted string of the paid redemption fees.
 func (ord *OrderReader) RedemptionFeesString() string {
 	if ord.Sell {
-		return formatQty(ord.FeesPaid.Swap, ord.QuoteUnitInfo)
+		return formatQty(ord.FeesPaid.Redemption, ord.QuoteFeeUnitInfo)
 	}
-	return formatQty(ord.FeesPaid.Swap, ord.BaseUnitInfo)
```
Comment (chappjc) [inline client/core/helpers.go:316]: Amazing that went unnoticed so long

**Review by JoeGruffins — COMMENTED** [review]
Working well. These symbols are not appearing for me howerver:
image

**Comment by martonp** [comment]
> Working well. These symbols are not appearing for me howerver:

The file names are case sensitive when using the embedded files but not when using the external site dir.

File: client/asset/driver.go [hunk 3]
```diff
@@ -154,6 +154,16 @@ func DecodeCoinID(assetID uint32, coinID []byte) (cid string, err error) {
...
 
+// IsToken checks if the asset ID is for a token and returns the token's parent
+// ID.
+func IsToken(assetID uint32) (is bool, parentID uint32) {
+	token, is := tokens[assetID]
+	if !is {
+		return
+	}
+	return true, token.ParentID
+}
```
Comment (chappjc) [inline client/asset/driver.go:165]: Will you please move this down next to `func TokenInfo` around line 230?

Also, I think you need to follow the pattern in that function of using `driversMtx` to access the `tokens` map.

Although I think you should just use `asset.TokenInfo`.  See my other comment in core.go.

File: client/core/core.go [hunk 4]
```diff
@@ -7729,14 +7731,42 @@ func (c *Core) deleteOrderFn(ordersFileStr string) (perOrderFn func(*db.MetaOrde
 		if err != nil {
 			return fmt.Errorf("unable to get base unit info for %v: %v", cord.BaseSymbol, err)
 		}
+
+		baseFeeAssetSymbol := unbip(cord.BaseID)
+		baseFeeUnitInfo := baseUnitInfo
+		baseIsToken, baseParent := asset.IsToken(cord.BaseID)
+		if baseIsToken {
```
Comment (chappjc) [inline client/core/core.go:7738]: Could consider just using `asset.TokenInfo` and tightening scope a little:

```go
	baseFeeAssetSymbol := unbip(cord.BaseID)
	baseFeeUnitInfo := baseUnitInfo
	if baseToken := asset.TokenInfo(cord.BaseID); baseToken != nil {
		baseFeeAssetSymbol = unbip(baseToken.ParentID)
		baseFeeUnitInfo, err = asset.UnitInfo(baseToken.ParentID)
		if err != nil {
			return fmt.Errorf("unable to get base fee unit info for %v: %v", baseToken.ParentID, err)
		}
	}
```

**Review by chappjc — APPROVED** [review]

**Comment by chappjc** [comment]
Merging now unless you're mid review @buck54321

**Comment by buck54321** [comment]
Go for it
