### PR TITLE
app: Fix candle chart Y-Axis

### LINKED ISSUE #2114: ui: candles y-axis and high/low rates for ETH and ERC20 markets are shifted
Fresh market with two trades: one at 0.0139 ETH/DCR and a second at 0.0142 ETH/DCR:

image

The second trade (order pair) still in my latest history:

image

### PR DESCRIPTION
**Pull request by martonp**
`RateEncodingFactor * quoteFactor / baseFactor` gives the conventional rate, but
`RateEncodingFactor * baseFactor / quoteFactor` was being used.

Closes #2114

### CODE REVIEW

File: client/webserver/site/src/js/charts.ts [hunk 1]
```diff
@@ -1018,7 +1018,7 @@ export class CandleChart extends Chart {
     if (!data.candles) return
     this.market = market
     const [qFactor, bFactor] = [quoteUnitInfo.conventional.conversionFactor, baseUnitInfo.conventional.conversionFactor]
-    this.rateConversionFactor = RateEncodingFactor * bFactor / qFactor
+    this.rateConversionFactor = RateEncodingFactor * qFactor / bFactor
```
Comment (chappjc) [inline client/webserver/site/src/js/charts.ts:1021]: Does `bconv` in `setHighLow` also need to change or is that inheriting this?

Comment (chappjc) [reply client/webserver/site/src/js/charts.ts:1021]: The USDC market is a good illustration of the shifts:

image

Looks like in the case of `bconv` it's neglecting the `RateEncodingFactor`

Comment (martonp) [reply client/webserver/site/src/js/charts.ts:1021]: It was using `bconv`, but it should be `qconv`.

**Review by JoeGruffins — APPROVED** [review]

**Review by buck54321 — APPROVED** [review]

**Comment by chappjc** [comment]
Not tested but merging with current reviews.  I was sure the `RateEncodingFactor` would be needed instead of `conventional.conversionFactor` in `setHighLow`, but looks like it's working.
